var bs_data=[
    {
        "desc":"Streptomyces sp. NRRL S-325 contig12.1, whole genome shotgun sequence",
        "end":11293,
        "id":"JOIW01000001.1.cluster028",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":397,
                "id":"JOIW01000001.1.cluster028_ORF1",
                "start":199,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":66.5,
                        "code":"PF00005",
                        "end":150,
                        "start":18
                    }
                ],
                "end":2010,
                "id":"JOIW01000001.1.cluster028_ORF2",
                "start":393,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":122.3,
                        "code":"PF01987",
                        "end":215,
                        "start":23
                    }
                ],
                "end":2684,
                "id":"JOIW01000001.1.cluster028_ORF3",
                "start":2006,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":31.4,
                        "code":"PF01981",
                        "end":254,
                        "start":164
                    }
                ],
                "end":3522,
                "id":"JOIW01000001.1.cluster028_ORF4",
                "start":2757,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":70.9,
                        "code":"PF13628",
                        "end":190,
                        "start":54
                    }
                ],
                "end":4446,
                "id":"JOIW01000001.1.cluster028_ORF5",
                "start":3690,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":259.6,
                        "code":"PF05114",
                        "end":271,
                        "start":4
                    }
                ],
                "end":6293,
                "id":"JOIW01000001.1.cluster028_ORF6",
                "start":5000,
                "strand":1
            },
            {
                "domains":[],
                "end":7312,
                "id":"JOIW01000001.1.cluster028_ORF7",
                "start":6298,
                "strand":1
            },
            {
                "domains":[],
                "end":8225,
                "id":"JOIW01000001.1.cluster028_ORF8",
                "start":7448,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":257.5,
                        "code":"PF06778",
                        "end":227,
                        "start":39
                    }
                ],
                "end":9219,
                "id":"JOIW01000001.1.cluster028_ORF9",
                "start":8505,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":144.7,
                        "code":"PF01593",
                        "end":468,
                        "start":22
                    }
                ],
                "end":10711,
                "id":"JOIW01000001.1.cluster028_ORF10",
                "start":9223,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces sp. NRRL B-1347 contig19.1, whole genome shotgun sequence",
        "end":18374,
        "id":"JOJM01000001.1.cluster024",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":70.7,
                        "code":"PF13185",
                        "end":191,
                        "start":51
                    },
                    {
                        "bitscore":58.2,
                        "code":"PF13185",
                        "end":358,
                        "start":219
                    },
                    {
                        "bitscore":41.8,
                        "code":"PF07730",
                        "end":439,
                        "start":374
                    },
                    {
                        "bitscore":34.4,
                        "code":"PF02518",
                        "end":580,
                        "start":480
                    }
                ],
                "end":1876,
                "id":"JOJM01000001.1.cluster024_ORF1",
                "start":127,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.9,
                        "code":"PF00196",
                        "end":224,
                        "start":168
                    },
                    {
                        "bitscore":82.9,
                        "code":"PF00072",
                        "end":132,
                        "start":20
                    }
                ],
                "end":2603,
                "id":"JOJM01000001.1.cluster024_ORF2",
                "start":1886,
                "strand":-1
            },
            {
                "domains":[],
                "end":3534,
                "id":"JOJM01000001.1.cluster024_ORF3",
                "start":3027,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":23.9,
                        "code":"PF05305",
                        "end":147,
                        "start":72
                    }
                ],
                "end":4275,
                "id":"JOJM01000001.1.cluster024_ORF4",
                "start":3831,
                "strand":-1
            },
            {
                "domains":[],
                "end":4632,
                "id":"JOJM01000001.1.cluster024_ORF5",
                "start":4410,
                "strand":-1
            },
            {
                "domains":[],
                "end":4979,
                "id":"JOJM01000001.1.cluster024_ORF6",
                "start":4628,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.8,
                        "code":"PF00392",
                        "end":71,
                        "start":9
                    }
                ],
                "end":5399,
                "id":"JOJM01000001.1.cluster024_ORF7",
                "start":5150,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":61.0,
                        "code":"PF13302",
                        "end":148,
                        "start":12
                    }
                ],
                "end":6054,
                "id":"JOJM01000001.1.cluster024_ORF8",
                "start":5487,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":64.6,
                        "code":"PF13471",
                        "end":204,
                        "start":89
                    }
                ],
                "end":6710,
                "id":"JOJM01000001.1.cluster024_ORF9",
                "start":6050,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":63.5,
                        "code":"PF00733",
                        "end":546,
                        "start":198
                    }
                ],
                "end":8374,
                "id":"JOJM01000001.1.cluster024_ORF10",
                "start":6670,
                "strand":-1
            },
            {
                "domains":[],
                "end":8589,
                "id":"JOJM01000001.1.cluster024_ORF11",
                "start":8454,
                "strand":-1
            },
            {
                "domains":[],
                "end":8923,
                "id":"JOJM01000001.1.cluster024_ORF12",
                "start":8674,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":51.2,
                        "code":"PF00293",
                        "end":151,
                        "start":17
                    }
                ],
                "end":9709,
                "id":"JOJM01000001.1.cluster024_ORF13",
                "start":9187,
                "strand":-1
            },
            {
                "domains":[],
                "end":10498,
                "id":"JOJM01000001.1.cluster024_ORF14",
                "start":9859,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":144.8,
                        "code":"PF19054",
                        "end":235,
                        "start":55
                    }
                ],
                "end":11440,
                "id":"JOJM01000001.1.cluster024_ORF15",
                "start":10714,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":78.0,
                        "code":"PF04149",
                        "end":62,
                        "start":6
                    }
                ],
                "end":11646,
                "id":"JOJM01000001.1.cluster024_ORF16",
                "start":11436,
                "strand":1
            },
            {
                "domains":[],
                "end":11973,
                "id":"JOJM01000001.1.cluster024_ORF17",
                "start":11736,
                "strand":-1
            },
            {
                "domains":[],
                "end":12332,
                "id":"JOJM01000001.1.cluster024_ORF18",
                "start":11969,
                "strand":-1
            },
            {
                "domains":[],
                "end":13543,
                "id":"JOJM01000001.1.cluster024_ORF19",
                "start":12733,
                "strand":-1
            },
            {
                "domains":[],
                "end":14026,
                "id":"JOJM01000001.1.cluster024_ORF20",
                "start":13777,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":153.3,
                        "code":"PF00476",
                        "end":611,
                        "start":243
                    },
                    {
                        "bitscore":40.9,
                        "code":"PF01612",
                        "end":212,
                        "start":15
                    }
                ],
                "end":15880,
                "id":"JOJM01000001.1.cluster024_ORF21",
                "start":14026,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces griseus strain NRRL B-2165 Streptomyces_griseus_NRRL_B-2165_contig_360, whole genome shotgun sequence",
        "end":4040,
        "id":"MDDK01000001.1.cluster053",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":78.7,
                        "code":"PF01522",
                        "end":165,
                        "start":21
                    }
                ],
                "end":714,
                "id":"MDDK01000001.1.cluster053_ORF1",
                "start":1,
                "strand":1
            },
            {
                "domains":[],
                "end":1024,
                "id":"MDDK01000001.1.cluster053_ORF2",
                "start":826,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":122.1,
                        "code":"PF01987",
                        "end":215,
                        "start":23
                    }
                ],
                "end":1784,
                "id":"MDDK01000001.1.cluster053_ORF3",
                "start":1109,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":32.5,
                        "code":"PF01981",
                        "end":250,
                        "start":159
                    }
                ],
                "end":2578,
                "id":"MDDK01000001.1.cluster053_ORF4",
                "start":1825,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":255.5,
                        "code":"PF05114",
                        "end":271,
                        "start":4
                    }
                ],
                "end":4040,
                "id":"MDDK01000001.1.cluster053_ORF5",
                "start":2702,
                "strand":1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
