var bs_data=[
    {
        "desc":"contig_109, whole genome shotgun sequence",
        "end":42958,
        "id":"contig_109.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":142.3,
                        "code":"PF13593",
                        "end":310,
                        "start":8
                    }
                ],
                "end":1606,
                "id":"gnl_Bakta_AIHFAG_00280",
                "start":619,
                "strand":1
            },
            {
                "domains":[],
                "end":1734,
                "id":"gnl_Bakta_AIHFAG_00285",
                "start":1602,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":81.8,
                        "code":"PF03992",
                        "end":78,
                        "start":1
                    }
                ],
                "end":2041,
                "id":"gnl_Bakta_AIHFAG_00290",
                "start":1750,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.5,
                        "code":"PF03480",
                        "end":61,
                        "start":1
                    }
                ],
                "end":3011,
                "id":"gnl_Bakta_AIHFAG_00295",
                "start":2825,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":144.2,
                        "code":"PF03480",
                        "end":132,
                        "start":1
                    }
                ],
                "end":3580,
                "id":"gnl_Bakta_AIHFAG_00300",
                "start":3133,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":66.2,
                        "code":"PF04290",
                        "end":154,
                        "start":24
                    }
                ],
                "end":4217,
                "id":"gnl_Bakta_AIHFAG_00305",
                "start":3686,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":383.1,
                        "code":"PF06808",
                        "end":400,
                        "start":1
                    }
                ],
                "end":5498,
                "id":"gnl_Bakta_AIHFAG_00310",
                "start":4265,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.9,
                        "code":"PF04166",
                        "end":149,
                        "start":35
                    }
                ],
                "end":5969,
                "id":"gnl_Bakta_AIHFAG_00315",
                "start":5504,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":212.6,
                        "code":"PF04166",
                        "end":146,
                        "start":1
                    }
                ],
                "end":6518,
                "id":"pdxA",
                "start":6047,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.1,
                        "code":"PF03446",
                        "end":48,
                        "start":4
                    }
                ],
                "end":6661,
                "id":"gnl_Bakta_AIHFAG_00325",
                "start":6514,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":83.5,
                        "code":"PF03446",
                        "end":112,
                        "start":1
                    },
                    {
                        "bitscore":42.5,
                        "code":"PF14833",
                        "end":184,
                        "start":115
                    }
                ],
                "end":7352,
                "id":"gnl_Bakta_AIHFAG_00330",
                "start":6671,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.8,
                        "code":"PF01177",
                        "end":211,
                        "start":23
                    }
                ],
                "end":8170,
                "id":"gnl_Bakta_AIHFAG_00335",
                "start":7378,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.9,
                        "code":"PF00392",
                        "end":73,
                        "start":11
                    }
                ],
                "end":8654,
                "id":"gntR",
                "start":8198,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":182.0,
                        "code":"PF00370",
                        "end":249,
                        "start":7
                    },
                    {
                        "bitscore":113.9,
                        "code":"PF02782",
                        "end":454,
                        "start":246
                    }
                ],
                "end":10463,
                "id":"gnl_Bakta_AIHFAG_00345",
                "start":8897,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":146.4,
                        "code":"PF00596",
                        "end":187,
                        "start":8
                    }
                ],
                "end":11050,
                "id":"gnl_Bakta_AIHFAG_00350",
                "start":10459,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":128.0,
                        "code":"PF00005",
                        "end":185,
                        "start":37
                    }
                ],
                "end":11892,
                "id":"glnQ",
                "start":11109,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":74.8,
                        "code":"PF00528",
                        "end":362,
                        "start":173
                    }
                ],
                "end":13026,
                "id":"gnl_Bakta_AIHFAG_00360",
                "start":11913,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":51.0,
                        "code":"PF00528",
                        "end":305,
                        "start":126
                    }
                ],
                "end":13960,
                "id":"gnl_Bakta_AIHFAG_00365",
                "start":13033,
                "strand":-1
            },
            {
                "domains":[],
                "end":14214,
                "id":"gnl_Bakta_AIHFAG_00370",
                "start":14007,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":101.4,
                        "code":"PF00497",
                        "end":261,
                        "start":38
                    }
                ],
                "end":15427,
                "id":"gnl_Bakta_AIHFAG_00380",
                "start":14614,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":23.3,
                        "code":"PF07238",
                        "end":135,
                        "start":51
                    }
                ],
                "end":15997,
                "id":"pilZ",
                "start":15580,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":51.2,
                        "code":"PF01648",
                        "end":185,
                        "start":90
                    }
                ],
                "end":16775,
                "id":"gnl_Bakta_AIHFAG_00390",
                "start":16166,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":45.8,
                        "code":"PF07992",
                        "end":359,
                        "start":151
                    }
                ],
                "end":18705,
                "id":"gnl_Bakta_AIHFAG_00395",
                "start":16833,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.3,
                        "code":"PF01717",
                        "end":372,
                        "start":166
                    }
                ],
                "end":19996,
                "id":"gnl_Bakta_AIHFAG_00400",
                "start":18859,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.7,
                        "code":"PF00550",
                        "end":979,
                        "start":911
                    },
                    {
                        "bitscore":44.3,
                        "code":"PF00550",
                        "end":891,
                        "start":828
                    },
                    {
                        "bitscore":52.4,
                        "code":"PF16197",
                        "end":798,
                        "start":731
                    },
                    {
                        "bitscore":143.0,
                        "code":"PF02801",
                        "end":729,
                        "start":612
                    },
                    {
                        "bitscore":212.9,
                        "code":"PF00109",
                        "end":607,
                        "start":381
                    },
                    {
                        "bitscore":21.7,
                        "code":"PF00550",
                        "end":365,
                        "start":306
                    },
                    {
                        "bitscore":40.4,
                        "code":"PF00698",
                        "end":297,
                        "start":7
                    }
                ],
                "end":22958,
                "id":"gnl_Bakta_AIHFAG_00405",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[],
                "end":23166,
                "id":"gnl_Bakta_AIHFAG_00410",
                "start":22971,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":315.8,
                        "code":"PF02685",
                        "end":326,
                        "start":3
                    }
                ],
                "end":24158,
                "id":"gnl_Bakta_AIHFAG_00415",
                "start":23168,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":166.8,
                        "code":"PF13714",
                        "end":253,
                        "start":8
                    }
                ],
                "end":25117,
                "id":"gnl_Bakta_AIHFAG_00420",
                "start":24256,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":374.0,
                        "code":"PF06808",
                        "end":415,
                        "start":7
                    }
                ],
                "end":26395,
                "id":"gnl_Bakta_AIHFAG_00425",
                "start":25123,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":111.3,
                        "code":"PF04290",
                        "end":156,
                        "start":23
                    }
                ],
                "end":26904,
                "id":"gnl_Bakta_AIHFAG_00430",
                "start":26406,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":204.2,
                        "code":"PF03480",
                        "end":314,
                        "start":30
                    }
                ],
                "end":27967,
                "id":"gnl_Bakta_AIHFAG_00435",
                "start":26977,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":79.8,
                        "code":"PF12694",
                        "end":150,
                        "start":5
                    }
                ],
                "end":28565,
                "id":"gnl_Bakta_AIHFAG_00440",
                "start":28103,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":98.6,
                        "code":"PF01558",
                        "end":176,
                        "start":14
                    }
                ],
                "end":29164,
                "id":"korC",
                "start":28612,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":114.6,
                        "code":"PF02775",
                        "end":196,
                        "start":48
                    }
                ],
                "end":29999,
                "id":"gnl_Bakta_AIHFAG_00450",
                "start":29198,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":71.5,
                        "code":"PF17147",
                        "end":370,
                        "start":276
                    },
                    {
                        "bitscore":221.8,
                        "code":"PF01855",
                        "end":246,
                        "start":16
                    }
                ],
                "end":31151,
                "id":"gnl_Bakta_AIHFAG_00455",
                "start":30002,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.1,
                        "code":"PF12838",
                        "end":62,
                        "start":16
                    }
                ],
                "end":31380,
                "id":"gnl_Bakta_AIHFAG_00460",
                "start":31152,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":155.9,
                        "code":"PF13714",
                        "end":258,
                        "start":15
                    }
                ],
                "end":32547,
                "id":"gnl_Bakta_AIHFAG_00465",
                "start":31635,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":134.2,
                        "code":"PF19305",
                        "end":385,
                        "start":198
                    },
                    {
                        "bitscore":135.1,
                        "code":"PF03972",
                        "end":167,
                        "start":11
                    }
                ],
                "end":33785,
                "id":"gnl_Bakta_AIHFAG_00470",
                "start":32546,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":191.4,
                        "code":"PF01970",
                        "end":156,
                        "start":1
                    }
                ],
                "end":34880,
                "id":"contig_109.region001_ORF40",
                "start":34337,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":265.2,
                        "code":"PF01970",
                        "end":280,
                        "start":20
                    }
                ],
                "end":35724,
                "id":"tctA",
                "start":34854,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":64.5,
                        "code":"PF07331",
                        "end":137,
                        "start":5
                    }
                ],
                "end":36175,
                "id":"gnl_Bakta_AIHFAG_00485",
                "start":35734,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":79.9,
                        "code":"PF03401",
                        "end":283,
                        "start":40
                    }
                ],
                "end":37141,
                "id":"gnl_Bakta_AIHFAG_00490",
                "start":36280,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":50.0,
                        "code":"PF07238",
                        "end":138,
                        "start":30
                    }
                ],
                "end":38021,
                "id":"pilZ",
                "start":37589,
                "strand":-1
            },
            {
                "domains":[],
                "end":38572,
                "id":"gnl_Bakta_AIHFAG_00500",
                "start":38290,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":78.1,
                        "code":"PF01592",
                        "end":147,
                        "start":26
                    }
                ],
                "end":39119,
                "id":"gnl_Bakta_AIHFAG_00505",
                "start":38663,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":80.4,
                        "code":"PF02579",
                        "end":104,
                        "start":12
                    }
                ],
                "end":39536,
                "id":"gnl_Bakta_AIHFAG_00510",
                "start":39176,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":66.4,
                        "code":"PF02579",
                        "end":111,
                        "start":18
                    }
                ],
                "end":39947,
                "id":"gnl_Bakta_AIHFAG_00515",
                "start":39557,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":38.9,
                        "code":"PF01656",
                        "end":262,
                        "start":4
                    }
                ],
                "end":40866,
                "id":"cobB",
                "start":39960,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.4,
                        "code":"PF01656",
                        "end":255,
                        "start":3
                    }
                ],
                "end":41741,
                "id":"rsxB",
                "start":40862,
                "strand":-1
            },
            {
                "domains":[],
                "end":42173,
                "id":"gnl_Bakta_AIHFAG_00530",
                "start":41801,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.9,
                        "code":"PF02579",
                        "end":97,
                        "start":8
                    }
                ],
                "end":42538,
                "id":"gnl_Bakta_AIHFAG_00535",
                "start":42196,
                "strand":-1
            },
            {
                "domains":[],
                "end":42796,
                "id":"gnl_Bakta_AIHFAG_00540",
                "start":42667,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_1250, whole genome shotgun sequence",
        "end":42610,
        "id":"contig_1250.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":36.9,
                        "code":"PF12399",
                        "end":74,
                        "start":50
                    }
                ],
                "end":707,
                "id":"gnl_Bakta_MIJOKH_05800",
                "start":473,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":80.6,
                        "code":"PF02653",
                        "end":167,
                        "start":4
                    }
                ],
                "end":1797,
                "id":"contig_1250.region001_ORF3",
                "start":1224,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":119.9,
                        "code":"PF02653",
                        "end":288,
                        "start":15
                    }
                ],
                "end":3079,
                "id":"gnl_Bakta_MIJOKH_05820",
                "start":2182,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":265.2,
                        "code":"PF13458",
                        "end":370,
                        "start":25
                    }
                ],
                "end":4393,
                "id":"gnl_Bakta_MIJOKH_05825",
                "start":3190,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.6,
                        "code":"PF13247",
                        "end":94,
                        "start":36
                    }
                ],
                "end":4905,
                "id":"gnl_Bakta_MIJOKH_05830",
                "start":4563,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":63.5,
                        "code":"PF01568",
                        "end":642,
                        "start":521
                    },
                    {
                        "bitscore":67.4,
                        "code":"PF00384",
                        "end":416,
                        "start":20
                    }
                ],
                "end":6868,
                "id":"gnl_Bakta_MIJOKH_05835",
                "start":4897,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":62.0,
                        "code":"PF04879",
                        "end":64,
                        "start":10
                    }
                ],
                "end":7350,
                "id":"gnl_Bakta_MIJOKH_05840",
                "start":7110,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.4,
                        "code":"PF01047",
                        "end":126,
                        "start":66
                    }
                ],
                "end":7985,
                "id":"marR",
                "start":7448,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":371.5,
                        "code":"PF01053",
                        "end":388,
                        "start":8
                    }
                ],
                "end":9207,
                "id":"gnl_Bakta_MIJOKH_05850",
                "start":8034,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":265.2,
                        "code":"PF06253",
                        "end":479,
                        "start":3
                    }
                ],
                "end":10979,
                "id":"gnl_Bakta_MIJOKH_05855",
                "start":9524,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":60.3,
                        "code":"PF00392",
                        "end":72,
                        "start":10
                    },
                    {
                        "bitscore":67.6,
                        "code":"PF07729",
                        "end":199,
                        "start":82
                    }
                ],
                "end":11832,
                "id":"gnl_Bakta_MIJOKH_05860",
                "start":11142,
                "strand":1
            },
            {
                "domains":[],
                "end":12824,
                "id":"gnl_Bakta_MIJOKH_05865",
                "start":12023,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.3,
                        "code":"PF00266",
                        "end":365,
                        "start":35
                    }
                ],
                "end":14082,
                "id":"gnl_Bakta_MIJOKH_05870",
                "start":12867,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":232.5,
                        "code":"PF01869",
                        "end":252,
                        "start":4
                    }
                ],
                "end":14933,
                "id":"gnl_Bakta_MIJOKH_05875",
                "start":14162,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":264.7,
                        "code":"PF06050",
                        "end":410,
                        "start":48
                    }
                ],
                "end":16165,
                "id":"gnl_Bakta_MIJOKH_05880",
                "start":14929,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":225.7,
                        "code":"PF06050",
                        "end":287,
                        "start":1
                    }
                ],
                "end":17335,
                "id":"hgdB1",
                "start":16471,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":57.3,
                        "code":"PF00440",
                        "end":68,
                        "start":22
                    }
                ],
                "end":18604,
                "id":"gnl_Bakta_MIJOKH_05895",
                "start":17980,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":133.8,
                        "code":"PF01810",
                        "end":209,
                        "start":15
                    }
                ],
                "end":19396,
                "id":"yrhP",
                "start":18760,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":40.7,
                        "code":"PF00698",
                        "end":135,
                        "start":5
                    },
                    {
                        "bitscore":217.6,
                        "code":"PF00109",
                        "end":606,
                        "start":379
                    },
                    {
                        "bitscore":144.2,
                        "code":"PF02801",
                        "end":727,
                        "start":610
                    },
                    {
                        "bitscore":46.7,
                        "code":"PF16197",
                        "end":799,
                        "start":729
                    }
                ],
                "end":22610,
                "id":"gnl_Bakta_MIJOKH_05905",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":34.5,
                        "code":"PF01717",
                        "end":373,
                        "start":138
                    }
                ],
                "end":23935,
                "id":"gnl_Bakta_MIJOKH_05910",
                "start":22789,
                "strand":1
            },
            {
                "domains":[],
                "end":24430,
                "id":"gnl_Bakta_MIJOKH_05915",
                "start":24094,
                "strand":1
            },
            {
                "domains":[],
                "end":25269,
                "id":"gnl_Bakta_MIJOKH_05920",
                "start":25002,
                "strand":1
            },
            {
                "domains":[],
                "end":25835,
                "id":"gnl_Bakta_MIJOKH_05925",
                "start":25343,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":70.2,
                        "code":"PF13622",
                        "end":120,
                        "start":36
                    },
                    {
                        "bitscore":79.8,
                        "code":"PF20789",
                        "end":278,
                        "start":133
                    }
                ],
                "end":26709,
                "id":"gnl_Bakta_MIJOKH_05930",
                "start":25866,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":160.6,
                        "code":"PF12654",
                        "end":257,
                        "start":84
                    },
                    {
                        "bitscore":47.0,
                        "code":"PF04060",
                        "end":46,
                        "start":14
                    }
                ],
                "end":27827,
                "id":"gnl_Bakta_MIJOKH_05935",
                "start":27014,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":70.3,
                        "code":"PF13622",
                        "end":114,
                        "start":30
                    },
                    {
                        "bitscore":129.3,
                        "code":"PF02551",
                        "end":286,
                        "start":153
                    }
                ],
                "end":28865,
                "id":"gnl_Bakta_MIJOKH_05940",
                "start":27980,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":116.1,
                        "code":"PF01551",
                        "end":261,
                        "start":165
                    }
                ],
                "end":29697,
                "id":"gnl_Bakta_MIJOKH_05945",
                "start":28866,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":264.9,
                        "code":"PF00248",
                        "end":362,
                        "start":69
                    }
                ],
                "end":30974,
                "id":"iolS",
                "start":29825,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.7,
                        "code":"PF00892",
                        "end":165,
                        "start":32
                    }
                ],
                "end":31694,
                "id":"gnl_Bakta_MIJOKH_05955",
                "start":31142,
                "strand":-1
            },
            {
                "domains":[],
                "end":32103,
                "id":"gnl_Bakta_MIJOKH_05960",
                "start":31863,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":21.6,
                        "code":"PF06966",
                        "end":258,
                        "start":141
                    }
                ],
                "end":33148,
                "id":"gnl_Bakta_MIJOKH_05965",
                "start":32302,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":154.2,
                        "code":"PF07690",
                        "end":380,
                        "start":20
                    }
                ],
                "end":34995,
                "id":"gnl_Bakta_MIJOKH_05970",
                "start":33654,
                "strand":1
            },
            {
                "domains":[],
                "end":35492,
                "id":"gnl_Bakta_MIJOKH_05975",
                "start":35186,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":82.0,
                        "code":"PF08241",
                        "end":138,
                        "start":40
                    }
                ],
                "end":37276,
                "id":"gnl_Bakta_MIJOKH_05980",
                "start":36472,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":50.3,
                        "code":"PF01850",
                        "end":118,
                        "start":1
                    }
                ],
                "end":38701,
                "id":"vapC",
                "start":38323,
                "strand":-1
            },
            {
                "domains":[],
                "end":39563,
                "id":"gnl_Bakta_MIJOKH_05990",
                "start":38987,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":71.2,
                        "code":"PF05973",
                        "end":98,
                        "start":8
                    }
                ],
                "end":40606,
                "id":"gnl_Bakta_MIJOKH_06000",
                "start":40282,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":46.9,
                        "code":"PF01381",
                        "end":88,
                        "start":35
                    }
                ],
                "end":40878,
                "id":"gnl_Bakta_MIJOKH_06005",
                "start":40602,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":32.7,
                        "code":"PF15919",
                        "end":72,
                        "start":4
                    }
                ],
                "end":41337,
                "id":"gnl_Bakta_MIJOKH_06010",
                "start":41112,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_14627, whole genome shotgun sequence",
        "end":32198,
        "id":"contig_14627.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":44.1,
                        "code":"PF01751",
                        "end":83,
                        "start":1
                    }
                ],
                "end":952,
                "id":"gnl_Bakta_MIJOKH_07685",
                "start":52,
                "strand":1
            },
            {
                "domains":[],
                "end":1884,
                "id":"gnl_Bakta_MIJOKH_07690",
                "start":960,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":14.2,
                        "code":"PF01396",
                        "end":86,
                        "start":67
                    },
                    {
                        "bitscore":39.8,
                        "code":"PF01396",
                        "end":158,
                        "start":127
                    },
                    {
                        "bitscore":14.7,
                        "code":"PF01396",
                        "end":192,
                        "start":166
                    }
                ],
                "end":2659,
                "id":"gnl_Bakta_MIJOKH_07695",
                "start":1861,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":35.8,
                        "code":"PF03682",
                        "end":156,
                        "start":4
                    }
                ],
                "end":3482,
                "id":"gnl_Bakta_MIJOKH_07700",
                "start":2990,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.1,
                        "code":"PF00512",
                        "end":69,
                        "start":3
                    }
                ],
                "end":4028,
                "id":"gnl_Bakta_MIJOKH_07705",
                "start":3644,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":46.8,
                        "code":"PF00072",
                        "end":61,
                        "start":1
                    }
                ],
                "end":4305,
                "id":"gnl_Bakta_MIJOKH_07710",
                "start":4095,
                "strand":-1
            },
            {
                "domains":[],
                "end":5063,
                "id":"gnl_Bakta_MIJOKH_07720",
                "start":4661,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":93.9,
                        "code":"PF08668",
                        "end":214,
                        "start":19
                    }
                ],
                "end":6664,
                "id":"gnl_Bakta_MIJOKH_07725",
                "start":5179,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.4,
                        "code":"PF13490",
                        "end":47,
                        "start":13
                    }
                ],
                "end":7410,
                "id":"gnl_Bakta_MIJOKH_07730",
                "start":7140,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":60.3,
                        "code":"PF08281",
                        "end":192,
                        "start":139
                    },
                    {
                        "bitscore":53.4,
                        "code":"PF04542",
                        "end":99,
                        "start":32
                    }
                ],
                "end":8008,
                "id":"gnl_Bakta_MIJOKH_07735",
                "start":7396,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":54.2,
                        "code":"PF02954",
                        "end":445,
                        "start":404
                    },
                    {
                        "bitscore":215.2,
                        "code":"PF00158",
                        "end":310,
                        "start":144
                    },
                    {
                        "bitscore":105.6,
                        "code":"PF00072",
                        "end":120,
                        "start":10
                    }
                ],
                "end":9682,
                "id":"gnl_Bakta_MIJOKH_07740",
                "start":8311,
                "strand":-1
            },
            {
                "domains":[],
                "end":10382,
                "id":"gnl_Bakta_MIJOKH_07745",
                "start":9686,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":97.6,
                        "code":"PF02518",
                        "end":487,
                        "start":374
                    },
                    {
                        "bitscore":53.1,
                        "code":"PF00512",
                        "end":328,
                        "start":260
                    },
                    {
                        "bitscore":56.7,
                        "code":"PF00672",
                        "end":256,
                        "start":204
                    }
                ],
                "end":11969,
                "id":"gnl_Bakta_MIJOKH_07750",
                "start":10499,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":165.9,
                        "code":"PF03205",
                        "end":133,
                        "start":4
                    }
                ],
                "end":12595,
                "id":"gnl_Bakta_MIJOKH_07755",
                "start":12097,
                "strand":-1
            },
            {
                "domains":[],
                "end":14289,
                "id":"gnl_Bakta_MIJOKH_07760",
                "start":12681,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":172.0,
                        "code":"PF00109",
                        "end":293,
                        "start":8
                    },
                    {
                        "bitscore":105.1,
                        "code":"PF02801",
                        "end":422,
                        "start":301
                    },
                    {
                        "bitscore":95.2,
                        "code":"PF00698",
                        "end":896,
                        "start":597
                    }
                ],
                "end":17947,
                "id":"gnl_Bakta_MIJOKH_07765",
                "start":14614,
                "strand":1
            },
            {
                "domains":[],
                "end":19181,
                "id":"gnl_Bakta_MIJOKH_07770",
                "start":18413,
                "strand":1
            },
            {
                "domains":[],
                "end":19468,
                "id":"gnl_Bakta_MIJOKH_07775",
                "start":19297,
                "strand":-1
            },
            {
                "domains":[],
                "end":20475,
                "id":"gnl_Bakta_MIJOKH_07780",
                "start":19914,
                "strand":-1
            },
            {
                "domains":[],
                "end":21349,
                "id":"gnl_Bakta_MIJOKH_07785",
                "start":20929,
                "strand":-1
            },
            {
                "domains":[],
                "end":21998,
                "id":"gnl_Bakta_MIJOKH_07790",
                "start":21383,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.8,
                        "code":"PF13279",
                        "end":120,
                        "start":1
                    }
                ],
                "end":22422,
                "id":"gnl_Bakta_MIJOKH_07795",
                "start":22035,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":219.6,
                        "code":"PF13382",
                        "end":563,
                        "start":395
                    },
                    {
                        "bitscore":125.9,
                        "code":"PF01979",
                        "end":350,
                        "start":63
                    }
                ],
                "end":24149,
                "id":"gnl_Bakta_MIJOKH_07800",
                "start":22439,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":255.8,
                        "code":"PF01979",
                        "end":410,
                        "start":59
                    }
                ],
                "end":25494,
                "id":"gnl_Bakta_MIJOKH_07805",
                "start":24165,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":63.3,
                        "code":"PF01979",
                        "end":89,
                        "start":1
                    }
                ],
                "end":25849,
                "id":"contig_14627.region001_ORF26",
                "start":25495,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":97.1,
                        "code":"PF01979",
                        "end":184,
                        "start":13
                    }
                ],
                "end":26670,
                "id":"gnl_Bakta_MIJOKH_07815",
                "start":25833,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":45.1,
                        "code":"PF01048",
                        "end":50,
                        "start":1
                    }
                ],
                "end":27373,
                "id":"gnl_Bakta_MIJOKH_07820",
                "start":27220,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":47.3,
                        "code":"PF01257",
                        "end":90,
                        "start":20
                    }
                ],
                "end":28296,
                "id":"gnl_Bakta_MIJOKH_07825",
                "start":27972,
                "strand":1
            },
            {
                "domains":[],
                "end":28875,
                "id":"gnl_Bakta_MIJOKH_07830",
                "start":28521,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":26.3,
                        "code":"PF01257",
                        "end":102,
                        "start":18
                    },
                    {
                        "bitscore":46.9,
                        "code":"PF01512",
                        "end":352,
                        "start":262
                    }
                ],
                "end":30176,
                "id":"gnl_Bakta_MIJOKH_07835",
                "start":28895,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.9,
                        "code":"PF04060",
                        "end":75,
                        "start":43
                    }
                ],
                "end":31142,
                "id":"gnl_Bakta_MIJOKH_07845",
                "start":30779,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":26.5,
                        "code":"PF12837",
                        "end":29,
                        "start":6
                    }
                ],
                "end":31914,
                "id":"gnl_Bakta_MIJOKH_07850",
                "start":31251,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_3532, whole genome shotgun sequence",
        "end":21546,
        "id":"contig_3532.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":101.6,
                        "code":"PF00313",
                        "end":66,
                        "start":2
                    }
                ],
                "end":522,
                "id":"gnl_Bakta_AGEIKA_12415",
                "start":321,
                "strand":1
            },
            {
                "domains":[],
                "end":1231,
                "id":"gnl_Bakta_AGEIKA_12420",
                "start":946,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.5,
                        "code":"PF13436",
                        "end":69,
                        "start":27
                    }
                ],
                "end":1711,
                "id":"gnl_Bakta_AGEIKA_12430",
                "start":1438,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.9,
                        "code":"PF18602",
                        "end":125,
                        "start":32
                    }
                ],
                "end":2165,
                "id":"gnl_Bakta_AGEIKA_12435",
                "start":1781,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":77.9,
                        "code":"PF04028",
                        "end":134,
                        "start":66
                    }
                ],
                "end":3370,
                "id":"gnl_Bakta_AGEIKA_12440",
                "start":2686,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":78.0,
                        "code":"PF03060",
                        "end":659,
                        "start":338
                    },
                    {
                        "bitscore":150.8,
                        "code":"PF00109",
                        "end":986,
                        "start":697
                    },
                    {
                        "bitscore":79.5,
                        "code":"PF02801",
                        "end":1106,
                        "start":994
                    },
                    {
                        "bitscore":184.3,
                        "code":"PF00698",
                        "end":1575,
                        "start":1257
                    },
                    {
                        "bitscore":30.7,
                        "code":"PF00550",
                        "end":1764,
                        "start":1697
                    },
                    {
                        "bitscore":103.6,
                        "code":"PF08659",
                        "end":2254,
                        "start":2031
                    },
                    {
                        "bitscore":40.3,
                        "code":"PF14765",
                        "end":2640,
                        "start":2486
                    }
                ],
                "end":11365,
                "id":"gnl_Bakta_AGEIKA_12445",
                "start":3442,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.3,
                        "code":"PF01648",
                        "end":217,
                        "start":114
                    }
                ],
                "end":12106,
                "id":"gnl_Bakta_AGEIKA_12450",
                "start":11380,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":56.0,
                        "code":"PF21082",
                        "end":818,
                        "start":737
                    },
                    {
                        "bitscore":79.2,
                        "code":"PF00924",
                        "end":729,
                        "start":662
                    },
                    {
                        "bitscore":27.3,
                        "code":"PF21088",
                        "end":661,
                        "start":620
                    }
                ],
                "end":14801,
                "id":"gnl_Bakta_AGEIKA_12455",
                "start":12242,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":50.0,
                        "code":"PF14103",
                        "end":178,
                        "start":8
                    }
                ],
                "end":15582,
                "id":"gnl_Bakta_AGEIKA_12460",
                "start":15000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":110.7,
                        "code":"PF13304",
                        "end":338,
                        "start":25
                    }
                ],
                "end":16754,
                "id":"gnl_Bakta_AGEIKA_12465",
                "start":15578,
                "strand":-1
            },
            {
                "domains":[],
                "end":17281,
                "id":"gnl_Bakta_AGEIKA_12470",
                "start":16696,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":186.4,
                        "code":"PF11737",
                        "end":127,
                        "start":1
                    }
                ],
                "end":18509,
                "id":"gnl_Bakta_AGEIKA_12485",
                "start":18110,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":416.2,
                        "code":"PF00343",
                        "end":261,
                        "start":1
                    }
                ],
                "end":19335,
                "id":"gnl_Bakta_AGEIKA_12490",
                "start":18537,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":103.6,
                        "code":"PF00343",
                        "end":73,
                        "start":1
                    }
                ],
                "end":19553,
                "id":"gnl_Bakta_AGEIKA_12495",
                "start":19331,
                "strand":-1
            },
            {
                "domains":[],
                "end":19965,
                "id":"gnl_Bakta_AGEIKA_12500",
                "start":19623,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":262.8,
                        "code":"PF01081",
                        "end":206,
                        "start":11
                    }
                ],
                "end":20659,
                "id":"gnl_Bakta_AGEIKA_12505",
                "start":20008,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":119.9,
                        "code":"PF00920",
                        "end":137,
                        "start":1
                    }
                ],
                "end":21529,
                "id":"gnl_Bakta_AGEIKA_12510",
                "start":21106,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_5389, whole genome shotgun sequence",
        "end":50505,
        "id":"contig_5389.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":1360,
                "id":"gnl_Bakta_CBDGDI_11385",
                "start":352,
                "strand":1
            },
            {
                "domains":[],
                "end":2009,
                "id":"gnl_Bakta_CBDGDI_11390",
                "start":1871,
                "strand":1
            },
            {
                "domains":[],
                "end":2362,
                "id":"gnl_Bakta_CBDGDI_11395",
                "start":2005,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":56.3,
                        "code":"PF11203",
                        "end":131,
                        "start":40
                    }
                ],
                "end":3341,
                "id":"gnl_Bakta_CBDGDI_11400",
                "start":2375,
                "strand":1
            },
            {
                "domains":[],
                "end":3535,
                "id":"gnl_Bakta_CBDGDI_11405",
                "start":3337,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.2,
                        "code":"PF21545",
                        "end":155,
                        "start":1
                    },
                    {
                        "bitscore":42.6,
                        "code":"PF21545",
                        "end":233,
                        "start":147
                    }
                ],
                "end":4746,
                "id":"eccA2",
                "start":3747,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":69.8,
                        "code":"PF08310",
                        "end":135,
                        "start":84
                    }
                ],
                "end":6070,
                "id":"gnl_Bakta_CBDGDI_11415",
                "start":5470,
                "strand":-1
            },
            {
                "domains":[],
                "end":7026,
                "id":"gnl_Bakta_CBDGDI_11420",
                "start":6096,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":28.1,
                        "code":"PF01744",
                        "end":57,
                        "start":31
                    },
                    {
                        "bitscore":21.5,
                        "code":"PF01744",
                        "end":32,
                        "start":6
                    }
                ],
                "end":8011,
                "id":"gnl_Bakta_CBDGDI_11425",
                "start":7264,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":70.4,
                        "code":"PF13450",
                        "end":88,
                        "start":19
                    },
                    {
                        "bitscore":272.6,
                        "code":"PF03275",
                        "end":373,
                        "start":163
                    }
                ],
                "end":9729,
                "id":"gnl_Bakta_CBDGDI_11430",
                "start":8490,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":145.6,
                        "code":"PF17994",
                        "end":100,
                        "start":1
                    },
                    {
                        "bitscore":92.7,
                        "code":"PF13641",
                        "end":375,
                        "start":104
                    },
                    {
                        "bitscore":283.8,
                        "code":"PF19320",
                        "end":579,
                        "start":386
                    }
                ],
                "end":11676,
                "id":"glfT2",
                "start":9918,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":61.2,
                        "code":"PF01569",
                        "end":179,
                        "start":67
                    }
                ],
                "end":12229,
                "id":"gnl_Bakta_CBDGDI_11440",
                "start":11668,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":81.2,
                        "code":"PF01040",
                        "end":278,
                        "start":32
                    }
                ],
                "end":13130,
                "id":"gnl_Bakta_CBDGDI_11445",
                "start":12215,
                "strand":1
            },
            {
                "domains":[],
                "end":15045,
                "id":"gnl_Bakta_CBDGDI_11450",
                "start":13107,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":150.1,
                        "code":"PF00756",
                        "end":294,
                        "start":44
                    }
                ],
                "end":16201,
                "id":"gnl_Bakta_CBDGDI_11455",
                "start":15301,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.3,
                        "code":"PF05305",
                        "end":149,
                        "start":64
                    }
                ],
                "end":16812,
                "id":"gnl_Bakta_CBDGDI_11460",
                "start":16362,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.1,
                        "code":"PF01083",
                        "end":286,
                        "start":76
                    }
                ],
                "end":17841,
                "id":"gnl_Bakta_CBDGDI_11465",
                "start":16815,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":184.5,
                        "code":"PF00501",
                        "end":432,
                        "start":25
                    }
                ],
                "end":19985,
                "id":"fadD32",
                "start":18092,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":40.5,
                        "code":"PF00550",
                        "end":102,
                        "start":36
                    },
                    {
                        "bitscore":288.4,
                        "code":"PF00109",
                        "end":374,
                        "start":124
                    },
                    {
                        "bitscore":143.4,
                        "code":"PF02801",
                        "end":500,
                        "start":382
                    },
                    {
                        "bitscore":42.7,
                        "code":"PF16197",
                        "end":583,
                        "start":502
                    },
                    {
                        "bitscore":179.6,
                        "code":"PF00698",
                        "end":1067,
                        "start":735
                    },
                    {
                        "bitscore":29.3,
                        "code":"PF00550",
                        "end":1340,
                        "start":1282
                    },
                    {
                        "bitscore":64.6,
                        "code":"PF00975",
                        "end":1741,
                        "start":1584
                    }
                ],
                "end":25571,
                "id":"gnl_Bakta_CBDGDI_11475",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":330.0,
                        "code":"PF01039",
                        "end":380,
                        "start":31
                    }
                ],
                "end":26821,
                "id":"gnl_Bakta_CBDGDI_11480",
                "start":25567,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.0,
                        "code":"PF01039",
                        "end":105,
                        "start":1
                    }
                ],
                "end":27119,
                "id":"gnl_Bakta_CBDGDI_11485",
                "start":26795,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":165.7,
                        "code":"PF00975",
                        "end":236,
                        "start":11
                    }
                ],
                "end":27838,
                "id":"tesA",
                "start":27118,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":204.2,
                        "code":"PF00501",
                        "end":419,
                        "start":12
                    }
                ],
                "end":30092,
                "id":"gnl_Bakta_CBDGDI_11495",
                "start":28349,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":262.4,
                        "code":"PF00109",
                        "end":215,
                        "start":1
                    },
                    {
                        "bitscore":150.9,
                        "code":"PF02801",
                        "end":341,
                        "start":223
                    },
                    {
                        "bitscore":65.4,
                        "code":"PF16197",
                        "end":448,
                        "start":343
                    }
                ],
                "end":32151,
                "id":"gnl_Bakta_CBDGDI_11500",
                "start":30489,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":160.2,
                        "code":"PF08659",
                        "end":336,
                        "start":159
                    }
                ],
                "end":34644,
                "id":"ppsB",
                "start":33165,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":236.8,
                        "code":"PF00109",
                        "end":273,
                        "start":16
                    },
                    {
                        "bitscore":137.5,
                        "code":"PF02801",
                        "end":401,
                        "start":281
                    },
                    {
                        "bitscore":65.8,
                        "code":"PF16197",
                        "end":514,
                        "start":403
                    },
                    {
                        "bitscore":179.1,
                        "code":"PF00698",
                        "end":869,
                        "start":550
                    },
                    {
                        "bitscore":45.3,
                        "code":"PF00550",
                        "end":1002,
                        "start":939
                    },
                    {
                        "bitscore":90.4,
                        "code":"PF00668",
                        "end":1379,
                        "start":1030
                    }
                ],
                "end":39189,
                "id":"gnl_Bakta_CBDGDI_11510",
                "start":34806,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":113.7,
                        "code":"PF00005",
                        "end":171,
                        "start":27
                    }
                ],
                "end":40284,
                "id":"drrA",
                "start":39276,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.3,
                        "code":"PF12698",
                        "end":263,
                        "start":33
                    }
                ],
                "end":41090,
                "id":"gnl_Bakta_CBDGDI_11520",
                "start":40280,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":63.4,
                        "code":"PF01061",
                        "end":232,
                        "start":21
                    }
                ],
                "end":41902,
                "id":"gnl_Bakta_CBDGDI_11525",
                "start":41089,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":193.9,
                        "code":"PF16911",
                        "end":386,
                        "start":199
                    }
                ],
                "end":43209,
                "id":"gnl_Bakta_CBDGDI_11530",
                "start":41961,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":101.8,
                        "code":"PF06974",
                        "end":433,
                        "start":285
                    },
                    {
                        "bitscore":212.8,
                        "code":"PF03007",
                        "end":245,
                        "start":1
                    }
                ],
                "end":44575,
                "id":"gnl_Bakta_CBDGDI_11535",
                "start":43219,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":110.5,
                        "code":"PF00106",
                        "end":157,
                        "start":1
                    }
                ],
                "end":45500,
                "id":"ydfG",
                "start":44831,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":51.0,
                        "code":"PF00593",
                        "end":185,
                        "start":3
                    }
                ],
                "end":47395,
                "id":"gnl_Bakta_CBDGDI_11550",
                "start":46801,
                "strand":-1
            },
            {
                "domains":[],
                "end":47896,
                "id":"gnl_Bakta_CBDGDI_11555",
                "start":47650,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":77.5,
                        "code":"PF01663",
                        "end":88,
                        "start":1
                    }
                ],
                "end":49799,
                "id":"gnl_Bakta_CBDGDI_11560",
                "start":49469,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
