var bs_data=[
    {
        "desc":"Streptomyces spectabilis spectinomycin biosynthesis gene cluster, complete sequence",
        "end":18359,
        "id":"BGC0000715",
        "mibig":true,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":169.2,
                        "code":"PF02668",
                        "end":239,
                        "start":1
                    }
                ],
                "end":744,
                "id":"ABW87795.1",
                "start":1,
                "strand":1
            },
            {
                "domains":[],
                "end":1606,
                "id":"spcZ",
                "start":802,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.5,
                        "code":"PF01636",
                        "end":285,
                        "start":26
                    }
                ],
                "end":2683,
                "id":"spcN",
                "start":1684,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":104.5,
                        "code":"PF07690",
                        "end":376,
                        "start":29
                    }
                ],
                "end":3985,
                "id":"spcT",
                "start":2692,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":198.0,
                        "code":"PF00459",
                        "end":262,
                        "start":10
                    }
                ],
                "end":4784,
                "id":"spcA",
                "start":3989,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":75.7,
                        "code":"PF01408",
                        "end":127,
                        "start":6
                    }
                ],
                "end":6283,
                "id":"spcB",
                "start":5158,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":320.2,
                        "code":"PF00202",
                        "end":431,
                        "start":26
                    }
                ],
                "end":7717,
                "id":"spcS1",
                "start":6388,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":69.5,
                        "code":"PF01261",
                        "end":254,
                        "start":14
                    }
                ],
                "end":8559,
                "id":"speD",
                "start":7758,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":138.9,
                        "code":"PF01547",
                        "end":306,
                        "start":8
                    }
                ],
                "end":9761,
                "id":"speX",
                "start":8570,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":265.0,
                        "code":"PF01041",
                        "end":380,
                        "start":31
                    }
                ],
                "end":11147,
                "id":"spcS2",
                "start":9827,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.3,
                        "code":"PF04055",
                        "end":121,
                        "start":18
                    }
                ],
                "end":12052,
                "id":"speY",
                "start":11143,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.3,
                        "code":"PF00535",
                        "end":183,
                        "start":15
                    }
                ],
                "end":12935,
                "id":"spcG",
                "start":12053,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.2,
                        "code":"PF01555",
                        "end":258,
                        "start":38
                    }
                ],
                "end":13735,
                "id":"spcM",
                "start":12931,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.4,
                        "code":"PF02894",
                        "end":335,
                        "start":132
                    },
                    {
                        "bitscore":63.9,
                        "code":"PF01408",
                        "end":105,
                        "start":1
                    }
                ],
                "end":14838,
                "id":"speH",
                "start":13800,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":97.3,
                        "code":"PF01370",
                        "end":234,
                        "start":17
                    }
                ],
                "end":15988,
                "id":"speI",
                "start":15058,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":241.3,
                        "code":"PF16363",
                        "end":306,
                        "start":4
                    }
                ],
                "end":17010,
                "id":"spcE",
                "start":16017,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":221.8,
                        "code":"PF00483",
                        "end":238,
                        "start":2
                    }
                ],
                "end":17984,
                "id":"spcD",
                "start":17108,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Spectinomycin biosynthetic gene cluster",
        "end":18359,
        "id":"BGC0000715.1.cluster001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":169.2,
                        "code":"PF02668",
                        "end":239,
                        "start":1
                    }
                ],
                "end":744,
                "id":"ABW87795.1",
                "start":1,
                "strand":1
            },
            {
                "domains":[],
                "end":1606,
                "id":"spcZ",
                "start":802,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.5,
                        "code":"PF01636",
                        "end":285,
                        "start":26
                    }
                ],
                "end":2683,
                "id":"spcN",
                "start":1684,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":104.5,
                        "code":"PF07690",
                        "end":376,
                        "start":29
                    }
                ],
                "end":3985,
                "id":"spcT",
                "start":2692,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":198.0,
                        "code":"PF00459",
                        "end":262,
                        "start":10
                    }
                ],
                "end":4784,
                "id":"spcA",
                "start":3989,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":75.7,
                        "code":"PF01408",
                        "end":127,
                        "start":6
                    }
                ],
                "end":6283,
                "id":"spcB",
                "start":5158,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":320.2,
                        "code":"PF00202",
                        "end":431,
                        "start":26
                    }
                ],
                "end":7717,
                "id":"spcS1",
                "start":6388,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":69.5,
                        "code":"PF01261",
                        "end":254,
                        "start":14
                    }
                ],
                "end":8559,
                "id":"speD",
                "start":7758,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":138.9,
                        "code":"PF01547",
                        "end":306,
                        "start":8
                    }
                ],
                "end":9761,
                "id":"speX",
                "start":8570,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":265.0,
                        "code":"PF01041",
                        "end":380,
                        "start":31
                    }
                ],
                "end":11147,
                "id":"spcS2",
                "start":9827,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.3,
                        "code":"PF04055",
                        "end":121,
                        "start":18
                    }
                ],
                "end":12052,
                "id":"speY",
                "start":11143,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.3,
                        "code":"PF00535",
                        "end":183,
                        "start":15
                    }
                ],
                "end":12935,
                "id":"spcG",
                "start":12053,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.2,
                        "code":"PF01555",
                        "end":258,
                        "start":38
                    }
                ],
                "end":13735,
                "id":"spcM",
                "start":12931,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.4,
                        "code":"PF02894",
                        "end":335,
                        "start":132
                    },
                    {
                        "bitscore":63.9,
                        "code":"PF01408",
                        "end":105,
                        "start":1
                    }
                ],
                "end":14838,
                "id":"speH",
                "start":13800,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":97.3,
                        "code":"PF01370",
                        "end":234,
                        "start":17
                    }
                ],
                "end":15988,
                "id":"speI",
                "start":15058,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":241.3,
                        "code":"PF16363",
                        "end":306,
                        "start":4
                    }
                ],
                "end":17010,
                "id":"spcE",
                "start":16017,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":221.8,
                        "code":"PF00483",
                        "end":238,
                        "start":2
                    }
                ],
                "end":17984,
                "id":"spcD",
                "start":17108,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces flavopersicus spectinomycin biosynthesis gene cluster, complete sequence",
        "end":29606,
        "id":"BGC0000716",
        "mibig":true,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":171.7,
                        "code":"PF13546",
                        "end":293,
                        "start":21
                    }
                ],
                "end":1608,
                "id":"insA",
                "start":435,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":130.8,
                        "code":"PF00245",
                        "end":212,
                        "start":59
                    }
                ],
                "end":3466,
                "id":"AAD45540.1",
                "start":2695,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":129.9,
                        "code":"PF04655",
                        "end":289,
                        "start":42
                    }
                ],
                "end":4541,
                "id":"aph_6_",
                "start":3617,
                "strand":1
            },
            {
                "domains":[],
                "end":5263,
                "id":"AAD45542.1",
                "start":4948,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":30.5,
                        "code":"PF02195",
                        "end":93,
                        "start":9
                    },
                    {
                        "bitscore":24.9,
                        "code":"PF13384",
                        "end":211,
                        "start":167
                    }
                ],
                "end":7297,
                "id":"spcR",
                "start":6304,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.5,
                        "code":"PF01636",
                        "end":284,
                        "start":28
                    }
                ],
                "end":8518,
                "id":"spcN",
                "start":7525,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":79.9,
                        "code":"PF07690",
                        "end":377,
                        "start":31
                    }
                ],
                "end":9829,
                "id":"spcT",
                "start":8527,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":189.0,
                        "code":"PF00459",
                        "end":263,
                        "start":9
                    }
                ],
                "end":10700,
                "id":"spcA",
                "start":9899,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.6,
                        "code":"PF01408",
                        "end":144,
                        "start":23
                    }
                ],
                "end":11993,
                "id":"spcB",
                "start":10814,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":315.1,
                        "code":"PF00202",
                        "end":431,
                        "start":25
                    }
                ],
                "end":13345,
                "id":"spcC",
                "start":12019,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.7,
                        "code":"PF01261",
                        "end":253,
                        "start":14
                    }
                ],
                "end":14160,
                "id":"spcD",
                "start":13371,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":138.2,
                        "code":"PF01547",
                        "end":306,
                        "start":8
                    }
                ],
                "end":15451,
                "id":"spcX",
                "start":14257,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":263.5,
                        "code":"PF01041",
                        "end":376,
                        "start":28
                    }
                ],
                "end":16791,
                "id":"spcE",
                "start":15507,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":35.5,
                        "code":"PF04055",
                        "end":155,
                        "start":18
                    }
                ],
                "end":17721,
                "id":"spcY",
                "start":16812,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.5,
                        "code":"PF00535",
                        "end":182,
                        "start":10
                    }
                ],
                "end":18536,
                "id":"spcF",
                "start":17723,
                "strand":1
            },
            {
                "domains":[],
                "end":19383,
                "id":"spcG",
                "start":18564,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.2,
                        "code":"PF02894",
                        "end":337,
                        "start":133
                    },
                    {
                        "bitscore":72.4,
                        "code":"PF01408",
                        "end":121,
                        "start":1
                    }
                ],
                "end":20498,
                "id":"spcH",
                "start":19457,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":129.5,
                        "code":"PF01370",
                        "end":235,
                        "start":18
                    }
                ],
                "end":21629,
                "id":"spcI",
                "start":20690,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":244.6,
                        "code":"PF16363",
                        "end":307,
                        "start":4
                    }
                ],
                "end":22680,
                "id":"spcJ",
                "start":21693,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":221.3,
                        "code":"PF00483",
                        "end":238,
                        "start":2
                    }
                ],
                "end":23770,
                "id":"spcK",
                "start":22858,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":25.8,
                        "code":"PF09299",
                        "end":550,
                        "start":483
                    }
                ],
                "end":27161,
                "id":"AAD45557.1",
                "start":25121,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Amycolatopsis mediterranei strain DSM 46096 contig034, whole genome shotgun sequence",
        "end":18460,
        "id":"JMQG01000002.1.cluster016",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":35.0,
                        "code":"PF13229",
                        "end":328,
                        "start":140
                    }
                ],
                "end":1317,
                "id":"KDU89986.1",
                "start":1,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":87.7,
                        "code":"PF18029",
                        "end":109,
                        "start":7
                    }
                ],
                "end":1823,
                "id":"KDU89987.1",
                "start":1445,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":91.7,
                        "code":"PF14417",
                        "end":129,
                        "start":1
                    }
                ],
                "end":2734,
                "id":"KDU89988.1",
                "start":1969,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":43.5,
                        "code":"PF01186",
                        "end":282,
                        "start":181
                    }
                ],
                "end":3632,
                "id":"KDU89989.1",
                "start":2690,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":272.1,
                        "code":"PF02350",
                        "end":378,
                        "start":46
                    }
                ],
                "end":4970,
                "id":"KDU89990.1",
                "start":3794,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":135.0,
                        "code":"PF01593",
                        "end":408,
                        "start":16
                    }
                ],
                "end":6250,
                "id":"KDU89991.1",
                "start":4939,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":92.3,
                        "code":"PF00535",
                        "end":201,
                        "start":31
                    }
                ],
                "end":7085,
                "id":"KDU89992.1",
                "start":6254,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":205.4,
                        "code":"PF02397",
                        "end":472,
                        "start":290
                    }
                ],
                "end":8830,
                "id":"KDU89993.1",
                "start":7399,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":273.1,
                        "code":"PF14885",
                        "end":370,
                        "start":87
                    }
                ],
                "end":10218,
                "id":"KDU89994.1",
                "start":8811,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":101.4,
                        "code":"PF13692",
                        "end":332,
                        "start":191
                    },
                    {
                        "bitscore":65.2,
                        "code":"PF13439",
                        "end":183,
                        "start":12
                    }
                ],
                "end":11480,
                "id":"KDU89995.1",
                "start":10349,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":113.1,
                        "code":"PF13692",
                        "end":327,
                        "start":190
                    },
                    {
                        "bitscore":102.5,
                        "code":"PF13579",
                        "end":166,
                        "start":12
                    }
                ],
                "end":12586,
                "id":"KDU89996.1",
                "start":11476,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":137.7,
                        "code":"PF13440",
                        "end":336,
                        "start":47
                    }
                ],
                "end":14049,
                "id":"KDU89997.1",
                "start":12582,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":55.0,
                        "code":"PF09594",
                        "end":286,
                        "start":44
                    }
                ],
                "end":15116,
                "id":"KDU89998.1",
                "start":14003,
                "strand":-1
            },
            {
                "domains":[],
                "end":16201,
                "id":"KDU89999.1",
                "start":15346,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":121.5,
                        "code":"PF13692",
                        "end":296,
                        "start":162
                    },
                    {
                        "bitscore":52.2,
                        "code":"PF13439",
                        "end":142,
                        "start":2
                    }
                ],
                "end":17196,
                "id":"KDU90000.1",
                "start":16197,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":71.8,
                        "code":"PF04932",
                        "end":331,
                        "start":188
                    }
                ],
                "end":18460,
                "id":"KDU90001.1",
                "start":17224,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces sp. NRRL B-1347 contig11.1, whole genome shotgun sequence",
        "end":32368,
        "id":"JOJM01000001.1.cluster017",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2070,
                "id":"JOJM01000001.1.cluster017_ORF1",
                "start":1176,
                "strand":-1
            },
            {
                "domains":[],
                "end":3673,
                "id":"JOJM01000001.1.cluster017_ORF2",
                "start":2146,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":58.4,
                        "code":"PF07729",
                        "end":213,
                        "start":91
                    },
                    {
                        "bitscore":54.2,
                        "code":"PF00392",
                        "end":81,
                        "start":19
                    }
                ],
                "end":4471,
                "id":"JOJM01000001.1.cluster017_ORF3",
                "start":3766,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":167.8,
                        "code":"PF07690",
                        "end":392,
                        "start":45
                    }
                ],
                "end":6007,
                "id":"JOJM01000001.1.cluster017_ORF4",
                "start":4705,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":216.4,
                        "code":"PF07286",
                        "end":206,
                        "start":64
                    }
                ],
                "end":6772,
                "id":"JOJM01000001.1.cluster017_ORF5",
                "start":6124,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":330.5,
                        "code":"PF03746",
                        "end":244,
                        "start":6
                    }
                ],
                "end":7610,
                "id":"JOJM01000001.1.cluster017_ORF6",
                "start":6845,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":185.4,
                        "code":"PF02682",
                        "end":200,
                        "start":10
                    }
                ],
                "end":8248,
                "id":"JOJM01000001.1.cluster017_ORF7",
                "start":7606,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":86.9,
                        "code":"PF13472",
                        "end":184,
                        "start":8
                    }
                ],
                "end":10004,
                "id":"JOJM01000001.1.cluster017_ORF9",
                "start":9014,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":91.4,
                        "code":"PF00534",
                        "end":425,
                        "start":260
                    },
                    {
                        "bitscore":60.2,
                        "code":"PF13439",
                        "end":254,
                        "start":87
                    }
                ],
                "end":11383,
                "id":"JOJM01000001.1.cluster017_ORF10",
                "start":10000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":86.4,
                        "code":"PF00534",
                        "end":345,
                        "start":187
                    },
                    {
                        "bitscore":96.3,
                        "code":"PF13439",
                        "end":181,
                        "start":14
                    }
                ],
                "end":12531,
                "id":"JOJM01000001.1.cluster017_ORF11",
                "start":11406,
                "strand":-1
            },
            {
                "domains":[],
                "end":14103,
                "id":"JOJM01000001.1.cluster017_ORF12",
                "start":12684,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":55.0,
                        "code":"PF12796",
                        "end":107,
                        "start":16
                    }
                ],
                "end":14797,
                "id":"JOJM01000001.1.cluster017_ORF13",
                "start":14404,
                "strand":-1
            },
            {
                "domains":[],
                "end":15316,
                "id":"JOJM01000001.1.cluster017_ORF14",
                "start":15121,
                "strand":1
            },
            {
                "domains":[],
                "end":16931,
                "id":"JOJM01000001.1.cluster017_ORF15",
                "start":15353,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":110.8,
                        "code":"PF00155",
                        "end":475,
                        "start":135
                    },
                    {
                        "bitscore":45.3,
                        "code":"PF00392",
                        "end":96,
                        "start":34
                    }
                ],
                "end":18546,
                "id":"JOJM01000001.1.cluster017_ORF16",
                "start":17049,
                "strand":-1
            },
            {
                "domains":[],
                "end":19364,
                "id":"JOJM01000001.1.cluster017_ORF17",
                "start":18644,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":164.2,
                        "code":"PF03009",
                        "end":243,
                        "start":20
                    }
                ],
                "end":20128,
                "id":"JOJM01000001.1.cluster017_ORF18",
                "start":19360,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":147.5,
                        "code":"PF13397",
                        "end":107,
                        "start":4
                    }
                ],
                "end":20805,
                "id":"JOJM01000001.1.cluster017_ORF19",
                "start":20430,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":88.8,
                        "code":"PF04186",
                        "end":137,
                        "start":25
                    }
                ],
                "end":21517,
                "id":"JOJM01000001.1.cluster017_ORF20",
                "start":20929,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":99.4,
                        "code":"PF00535",
                        "end":190,
                        "start":24
                    }
                ],
                "end":22368,
                "id":"JOJM01000001.1.cluster017_ORF21",
                "start":21564,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":326.9,
                        "code":"PF07969",
                        "end":538,
                        "start":57
                    }
                ],
                "end":24517,
                "id":"JOJM01000001.1.cluster017_ORF22",
                "start":22885,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":58.5,
                        "code":"PF01037",
                        "end":137,
                        "start":67
                    },
                    {
                        "bitscore":60.2,
                        "code":"PF13404",
                        "end":42,
                        "start":1
                    }
                ],
                "end":25045,
                "id":"JOJM01000001.1.cluster017_ORF23",
                "start":24604,
                "strand":-1
            },
            {
                "domains":[],
                "end":25878,
                "id":"JOJM01000001.1.cluster017_ORF24",
                "start":25431,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":86.2,
                        "code":"PF01636",
                        "end":302,
                        "start":37
                    }
                ],
                "end":27040,
                "id":"JOJM01000001.1.cluster017_ORF25",
                "start":25948,
                "strand":-1
            },
            {
                "domains":[],
                "end":28203,
                "id":"JOJM01000001.1.cluster017_ORF26",
                "start":27075,
                "strand":-1
            },
            {
                "domains":[],
                "end":29129,
                "id":"JOJM01000001.1.cluster017_ORF27",
                "start":28496,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":180.2,
                        "code":"PF00441",
                        "end":385,
                        "start":236
                    },
                    {
                        "bitscore":95.1,
                        "code":"PF02770",
                        "end":224,
                        "start":130
                    },
                    {
                        "bitscore":88.5,
                        "code":"PF02771",
                        "end":126,
                        "start":15
                    }
                ],
                "end":30293,
                "id":"JOJM01000001.1.cluster017_ORF28",
                "start":29120,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":275.7,
                        "code":"PF00704",
                        "end":404,
                        "start":52
                    }
                ],
                "end":31947,
                "id":"JOJM01000001.1.cluster017_ORF29",
                "start":30699,
                "strand":1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
