#!/usr/bin/env python3

import json
import pandas as pd
import argparse

parser= argparse.ArgumentParser(description='extract BGCs categories from bigscape run_data.js')
parser.add_argument('--i', dest="filename", metavar='run_data.js', type=str, help='JSON data from JS file generated by bigscape', required=True)
parser.add_argument('--o', dest="output", metavar='bgc_count.tsv', type=str, help='name for output file containing BGCs categories', required=True)
args= parser.parse_args()

filename = args.filename
output = args.output

# extract the run_data object from the file (js object with bigscape results)
def extract_run_data(filename):
    with open(filename) as dataFile:
        data = dataFile.read()
        obj = data[data.find('{'): data.rfind('}') + 1]
        jsonObj = json.loads(obj)
        return jsonObj

# extract the run_data object
run_data = extract_run_data(filename)

# create a DataFrame to store the data
data = {class_obj["label"]: [0] * len(run_data["input"]["accession"]) for class_obj in run_data["input"]["classes"]}
data["genome"] = [accession["label"] for accession in run_data["input"]["accession"]]
df = pd.DataFrame(data)

# fill the table with the count of BGCs for each genome
for bgc in run_data["input"]["bgc"]:
    bgc_genome_id = bgc["acc"]                                      # ID of the genome associated with the BGC
    bgc_class = bgc["class"]                                        # Class of the BGC
    class_label = run_data["input"]["classes"][bgc_class]["label"]  # Label of the BGC class
    
    # find the label of the genome associated with the BGC
    bgc_genome_label = None
    for accession in run_data["input"]["accession"]:
        if accession["id"] == f"genome_{bgc_genome_id}":
            bgc_genome_label = accession["label"]
            break
    
    # if the genome label is found, update the count in the table
    if bgc_genome_label:
        df.loc[df["genome"] == bgc_genome_label, class_label] += 1
    else:
        print("Genome label not found for BGC:", bgc)

#print(df)

df.to_csv(output, sep='\t', index=False)
print("File saved successfully:", output)

# print the sum of each BGC category
print("\nSum of each category:")
for column in df.columns[:-1]: 
    print(f"{column}: {df[column].sum()}")
    
total_sum = df.iloc[:, :-1].sum().sum() 
print(f"Total: {total_sum}")
