var bs_data=[
    {
        "desc":"contig_9736, whole genome shotgun sequence",
        "end":25977,
        "id":"1018_sub.region001.contig_9736",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":653,
                "id":"gnl_Bakta_AAIDNF_12240",
                "start":263,
                "strand":-1
            },
            {
                "domains":[],
                "end":1331,
                "id":"gnl_Bakta_AAIDNF_12245",
                "start":1025,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":148.7,
                        "code":"PF00698",
                        "end":1374,
                        "start":1063
                    },
                    {
                        "bitscore":94.2,
                        "code":"PF02801",
                        "end":912,
                        "start":800
                    },
                    {
                        "bitscore":152.2,
                        "code":"PF00109",
                        "end":792,
                        "start":503
                    },
                    {
                        "bitscore":44.1,
                        "code":"PF03060",
                        "end":476,
                        "start":218
                    }
                ],
                "end":5977,
                "id":"1018_sub.region001.contig_9736_ORF3",
                "start":1339,
                "strand":-1
            },
            {
                "domains":[],
                "end":6560,
                "id":"gnl_Bakta_AAIDNF_12255",
                "start":5936,
                "strand":-1
            },
            {
                "domains":[],
                "end":7351,
                "id":"gnl_Bakta_AAIDNF_12260",
                "start":7150,
                "strand":1
            },
            {
                "domains":[],
                "end":8106,
                "id":"gnl_Bakta_AAIDNF_12265",
                "start":7845,
                "strand":-1
            },
            {
                "domains":[],
                "end":8593,
                "id":"gnl_Bakta_AAIDNF_12270",
                "start":8371,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":126.6,
                        "code":"PF01937",
                        "end":215,
                        "start":1
                    }
                ],
                "end":9841,
                "id":"gnl_Bakta_AAIDNF_12275",
                "start":9139,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":163.4,
                        "code":"PF01300",
                        "end":293,
                        "start":118
                    }
                ],
                "end":10815,
                "id":"gnl_Bakta_AAIDNF_12280",
                "start":9879,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":209.3,
                        "code":"PF00480",
                        "end":321,
                        "start":7
                    }
                ],
                "end":11808,
                "id":"gnl_Bakta_AAIDNF_12285",
                "start":10818,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":81.6,
                        "code":"PF10604",
                        "end":138,
                        "start":1
                    }
                ],
                "end":12293,
                "id":"gnl_Bakta_AAIDNF_12290",
                "start":11873,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":154.4,
                        "code":"PF01738",
                        "end":244,
                        "start":23
                    }
                ],
                "end":13143,
                "id":"gnl_Bakta_AAIDNF_12295",
                "start":12393,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":201.4,
                        "code":"PF01041",
                        "end":175,
                        "start":13
                    },
                    {
                        "bitscore":145.7,
                        "code":"PF01041",
                        "end":434,
                        "start":222
                    }
                ],
                "end":14484,
                "id":"gnl_Bakta_AAIDNF_12300",
                "start":13164,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":457.3,
                        "code":"PF00909",
                        "end":404,
                        "start":7
                    }
                ],
                "end":15983,
                "id":"gnl_Bakta_AAIDNF_12305",
                "start":14762,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":153.9,
                        "code":"PF00543",
                        "end":108,
                        "start":1
                    }
                ],
                "end":16340,
                "id":"gnl_Bakta_AAIDNF_12310",
                "start":16001,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":30.9,
                        "code":"PF09694",
                        "end":204,
                        "start":48
                    }
                ],
                "end":17289,
                "id":"gnl_Bakta_AAIDNF_12315",
                "start":16392,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":104.0,
                        "code":"PF17179",
                        "end":356,
                        "start":262
                    }
                ],
                "end":18685,
                "id":"gnl_Bakta_AAIDNF_12320",
                "start":17524,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":37.0,
                        "code":"PF00027",
                        "end":119,
                        "start":31
                    }
                ],
                "end":19127,
                "id":"gnl_Bakta_AAIDNF_12325",
                "start":18671,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.4,
                        "code":"PF00175",
                        "end":231,
                        "start":127
                    },
                    {
                        "bitscore":39.0,
                        "code":"PF10418",
                        "end":281,
                        "start":248
                    }
                ],
                "end":19986,
                "id":"gnl_Bakta_AAIDNF_12330",
                "start":19116,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":89.0,
                        "code":"PF01058",
                        "end":153,
                        "start":16
                    }
                ],
                "end":20677,
                "id":"gnl_Bakta_AAIDNF_12335",
                "start":19987,
                "strand":1
            },
            {
                "domains":[],
                "end":21234,
                "id":"gnl_Bakta_AAIDNF_12340",
                "start":20838,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":37.5,
                        "code":"PF13524",
                        "end":108,
                        "start":10
                    }
                ],
                "end":21814,
                "id":"gnl_Bakta_AAIDNF_12345",
                "start":21469,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":59.6,
                        "code":"PF00374",
                        "end":133,
                        "start":43
                    }
                ],
                "end":22651,
                "id":"1018_sub.region001.contig_9736_ORF23",
                "start":21955,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.5,
                        "code":"PF00374",
                        "end":209,
                        "start":25
                    }
                ],
                "end":23252,
                "id":"gnl_Bakta_AAIDNF_12355",
                "start":22595,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":69.2,
                        "code":"PF00581",
                        "end":109,
                        "start":14
                    },
                    {
                        "bitscore":31.4,
                        "code":"PF02915",
                        "end":274,
                        "start":130
                    }
                ],
                "end":24433,
                "id":"gnl_Bakta_AAIDNF_12360",
                "start":23596,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":43.4,
                        "code":"PF01243",
                        "end":109,
                        "start":18
                    }
                ],
                "end":24896,
                "id":"gnl_Bakta_AAIDNF_12365",
                "start":24419,
                "strand":1
            },
            {
                "domains":[],
                "end":25679,
                "id":"gnl_Bakta_AAIDNF_12370",
                "start":25418,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_10405, whole genome shotgun sequence",
        "end":28669,
        "id":"CONCOCT.30_sub.region001.contig_10405",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":629,
                "id":"gnl_Bakta_JDCMNE_01095",
                "start":299,
                "strand":-1
            },
            {
                "domains":[],
                "end":898,
                "id":"gnl_Bakta_JDCMNE_01100",
                "start":706,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":91.0,
                        "code":"PF00849",
                        "end":146,
                        "start":25
                    }
                ],
                "end":1827,
                "id":"gnl_Bakta_JDCMNE_01105",
                "start":1194,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":120.8,
                        "code":"PF01252",
                        "end":144,
                        "start":5
                    }
                ],
                "end":2605,
                "id":"lspA",
                "start":2119,
                "strand":-1
            },
            {
                "domains":[],
                "end":3484,
                "id":"gnl_Bakta_JDCMNE_01125",
                "start":2857,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":92.8,
                        "code":"PF11799",
                        "end":236,
                        "start":129
                    },
                    {
                        "bitscore":30.5,
                        "code":"PF11798",
                        "end":85,
                        "start":54
                    }
                ],
                "end":4616,
                "id":"gnl_Bakta_JDCMNE_01130",
                "start":3644,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":38.9,
                        "code":"PF08264",
                        "end":181,
                        "start":75
                    }
                ],
                "end":6104,
                "id":"gnl_Bakta_JDCMNE_01140",
                "start":5066,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.2,
                        "code":"PF00133",
                        "end":334,
                        "start":1
                    }
                ],
                "end":7788,
                "id":"gnl_Bakta_JDCMNE_01150",
                "start":6543,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":324.8,
                        "code":"PF03176",
                        "end":316,
                        "start":1
                    }
                ],
                "end":10941,
                "id":"gnl_Bakta_JDCMNE_01165",
                "start":8640,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":196.0,
                        "code":"PF03176",
                        "end":222,
                        "start":1
                    }
                ],
                "end":11602,
                "id":"mmpL8",
                "start":10903,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":71.9,
                        "code":"PF11139",
                        "end":117,
                        "start":5
                    }
                ],
                "end":12049,
                "id":"gnl_Bakta_JDCMNE_01175",
                "start":11653,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":74.3,
                        "code":"PF11139",
                        "end":79,
                        "start":1
                    }
                ],
                "end":12373,
                "id":"gnl_Bakta_JDCMNE_01180",
                "start":12127,
                "strand":1
            },
            {
                "domains":[],
                "end":13858,
                "id":"gnl_Bakta_JDCMNE_01185",
                "start":12448,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":215.4,
                        "code":"PF08237",
                        "end":275,
                        "start":41
                    }
                ],
                "end":15491,
                "id":"gnl_Bakta_JDCMNE_01195",
                "start":14417,
                "strand":1
            },
            {
                "domains":[],
                "end":17182,
                "id":"gnl_Bakta_JDCMNE_01205",
                "start":15817,
                "strand":-1
            },
            {
                "domains":[],
                "end":17449,
                "id":"gnl_Bakta_JDCMNE_01210",
                "start":17194,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":63.5,
                        "code":"PF00668",
                        "end":388,
                        "start":67
                    }
                ],
                "end":20000,
                "id":"gnl_Bakta_JDCMNE_01220",
                "start":17813,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":33.7,
                        "code":"PF00550",
                        "end":1871,
                        "start":1811
                    },
                    {
                        "bitscore":198.6,
                        "code":"PF08659",
                        "end":1724,
                        "start":1546
                    },
                    {
                        "bitscore":79.4,
                        "code":"PF00107",
                        "end":1483,
                        "start":1351
                    },
                    {
                        "bitscore":22.8,
                        "code":"PF08240",
                        "end":1302,
                        "start":1228
                    },
                    {
                        "bitscore":81.5,
                        "code":"PF14765",
                        "end":975,
                        "start":814
                    },
                    {
                        "bitscore":78.8,
                        "code":"PF21089",
                        "end":789,
                        "start":689
                    },
                    {
                        "bitscore":331.5,
                        "code":"PF00698",
                        "end":646,
                        "start":329
                    },
                    {
                        "bitscore":45.6,
                        "code":"PF16197",
                        "end":296,
                        "start":176
                    },
                    {
                        "bitscore":130.6,
                        "code":"PF02801",
                        "end":173,
                        "start":59
                    },
                    {
                        "bitscore":48.3,
                        "code":"PF00109",
                        "end":51,
                        "start":1
                    }
                ],
                "end":25700,
                "id":"gnl_Bakta_JDCMNE_01225",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[],
                "end":26463,
                "id":"gnl_Bakta_JDCMNE_01235",
                "start":25827,
                "strand":1
            },
            {
                "domains":[],
                "end":27550,
                "id":"gnl_Bakta_JDCMNE_01240",
                "start":27379,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":168.3,
                        "code":"PF00144",
                        "end":250,
                        "start":28
                    }
                ],
                "end":28653,
                "id":"gnl_Bakta_JDCMNE_01245",
                "start":27756,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_23314, whole genome shotgun sequence",
        "end":25516,
        "id":"CONCOCT.30_sub.region001.contig_23314",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":695,
                "id":"gnl_Bakta_JDCMNE_32525",
                "start":452,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":38.7,
                        "code":"PF02627",
                        "end":105,
                        "start":30
                    }
                ],
                "end":1622,
                "id":"gnl_Bakta_JDCMNE_32530",
                "start":1121,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":245.6,
                        "code":"PF03007",
                        "end":271,
                        "start":7
                    },
                    {
                        "bitscore":102.2,
                        "code":"PF06974",
                        "end":459,
                        "start":311
                    }
                ],
                "end":4067,
                "id":"gnl_Bakta_JDCMNE_32535",
                "start":2633,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":149.1,
                        "code":"PF16911",
                        "end":386,
                        "start":199
                    }
                ],
                "end":5326,
                "id":"gnl_Bakta_JDCMNE_32540",
                "start":4132,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":63.4,
                        "code":"PF01061",
                        "end":232,
                        "start":21
                    }
                ],
                "end":6198,
                "id":"gnl_Bakta_JDCMNE_32545",
                "start":5385,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":42.3,
                        "code":"PF12698",
                        "end":263,
                        "start":33
                    }
                ],
                "end":7007,
                "id":"gnl_Bakta_JDCMNE_32550",
                "start":6197,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":113.7,
                        "code":"PF00005",
                        "end":171,
                        "start":27
                    }
                ],
                "end":8011,
                "id":"drrA",
                "start":7003,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":31.6,
                        "code":"PF00668",
                        "end":121,
                        "start":2
                    }
                ],
                "end":8753,
                "id":"gnl_Bakta_JDCMNE_32565",
                "start":8339,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.1,
                        "code":"PF00668",
                        "end":402,
                        "start":188
                    },
                    {
                        "bitscore":47.6,
                        "code":"PF00550",
                        "end":160,
                        "start":97
                    }
                ],
                "end":9954,
                "id":"gnl_Bakta_JDCMNE_32570",
                "start":8730,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":58.9,
                        "code":"PF00698",
                        "end":141,
                        "start":1
                    }
                ],
                "end":10444,
                "id":"gnl_Bakta_JDCMNE_32575",
                "start":9925,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.7,
                        "code":"PF00698",
                        "end":617,
                        "start":550
                    },
                    {
                        "bitscore":67.3,
                        "code":"PF16197",
                        "end":514,
                        "start":403
                    },
                    {
                        "bitscore":139.0,
                        "code":"PF02801",
                        "end":401,
                        "start":281
                    },
                    {
                        "bitscore":238.8,
                        "code":"PF00109",
                        "end":273,
                        "start":16
                    }
                ],
                "end":12482,
                "id":"ppsE",
                "start":10460,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.3,
                        "code":"PF00550",
                        "end":157,
                        "start":90
                    }
                ],
                "end":13081,
                "id":"gnl_Bakta_JDCMNE_32585",
                "start":12478,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":327.0,
                        "code":"PF00698",
                        "end":836,
                        "start":520
                    },
                    {
                        "bitscore":66.6,
                        "code":"PF16197",
                        "end":476,
                        "start":363
                    },
                    {
                        "bitscore":149.2,
                        "code":"PF02801",
                        "end":361,
                        "start":243
                    },
                    {
                        "bitscore":281.1,
                        "code":"PF00109",
                        "end":235,
                        "start":1
                    }
                ],
                "end":16856,
                "id":"gnl_Bakta_JDCMNE_32590",
                "start":13061,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":100.3,
                        "code":"PF00501",
                        "end":237,
                        "start":1
                    }
                ],
                "end":18392,
                "id":"CONCOCT.30_sub.region001.contig_23314_ORF15",
                "start":17477,
                "strand":-1
            },
            {
                "domains":[],
                "end":18939,
                "id":"gnl_Bakta_JDCMNE_32600",
                "start":18813,
                "strand":-1
            },
            {
                "domains":[],
                "end":19600,
                "id":"gnl_Bakta_JDCMNE_32605",
                "start":19450,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":50.3,
                        "code":"PF00975",
                        "end":47,
                        "start":1
                    }
                ],
                "end":19933,
                "id":"gnl_Bakta_JDCMNE_32610",
                "start":19765,
                "strand":-1
            },
            {
                "domains":[],
                "end":20166,
                "id":"gnl_Bakta_JDCMNE_32615",
                "start":20031,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":48.7,
                        "code":"PF01039",
                        "end":107,
                        "start":1
                    }
                ],
                "end":20495,
                "id":"gnl_Bakta_JDCMNE_32620",
                "start":20165,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":175.2,
                        "code":"PF01039",
                        "end":144,
                        "start":1
                    }
                ],
                "end":20937,
                "id":"gnl_Bakta_JDCMNE_32625",
                "start":20469,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":96.0,
                        "code":"PF01039",
                        "end":107,
                        "start":1
                    }
                ],
                "end":21257,
                "id":"gnl_Bakta_JDCMNE_32630",
                "start":20933,
                "strand":-1
            },
            {
                "domains":[],
                "end":21760,
                "id":"gnl_Bakta_JDCMNE_32635",
                "start":21352,
                "strand":1
            },
            {
                "domains":[],
                "end":22257,
                "id":"CONCOCT.30_sub.region001.contig_23314_ORF24",
                "start":21723,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":68.6,
                        "code":"PF00975",
                        "end":197,
                        "start":88
                    }
                ],
                "end":22807,
                "id":"gnl_Bakta_JDCMNE_32645",
                "start":22204,
                "strand":-1
            },
            {
                "domains":[],
                "end":23328,
                "id":"gnl_Bakta_JDCMNE_32650",
                "start":22869,
                "strand":-1
            },
            {
                "domains":[],
                "end":24339,
                "id":"gnl_Bakta_JDCMNE_32655",
                "start":23592,
                "strand":-1
            },
            {
                "domains":[],
                "end":24679,
                "id":"gnl_Bakta_JDCMNE_32660",
                "start":24364,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.2,
                        "code":"PF00698",
                        "end":79,
                        "start":4
                    }
                ],
                "end":25074,
                "id":"gnl_Bakta_JDCMNE_32665",
                "start":24696,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
