var bs_data=[
    {
        "desc":"contig_2220, whole genome shotgun sequence",
        "end":20924,
        "id":"bins.011_sub.region001.contig_2220",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":405,
                "id":"gnl_Bakta_OCBKLD_13295",
                "start":297,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":80.7,
                        "code":"PF00107",
                        "end":209,
                        "start":74
                    }
                ],
                "end":1998,
                "id":"bins.011_sub.region001.contig_2220_ORF2",
                "start":1257,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.4,
                        "code":"PF00107",
                        "end":328,
                        "start":162
                    },
                    {
                        "bitscore":40.3,
                        "code":"PF08240",
                        "end":96,
                        "start":11
                    }
                ],
                "end":3754,
                "id":"gnl_Bakta_OCBKLD_13310",
                "start":2590,
                "strand":-1
            },
            {
                "domains":[],
                "end":4473,
                "id":"gnl_Bakta_OCBKLD_13315",
                "start":4236,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":96.6,
                        "code":"PF03492",
                        "end":255,
                        "start":1
                    }
                ],
                "end":5565,
                "id":"gnl_Bakta_OCBKLD_13320",
                "start":4776,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":60.4,
                        "code":"PF19328",
                        "end":354,
                        "start":144
                    },
                    {
                        "bitscore":25.9,
                        "code":"PF01113",
                        "end":94,
                        "start":3
                    }
                ],
                "end":6641,
                "id":"gnl_Bakta_OCBKLD_13325",
                "start":5567,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":95.8,
                        "code":"PF19299",
                        "end":75,
                        "start":5
                    }
                ],
                "end":6873,
                "id":"gnl_Bakta_OCBKLD_13330",
                "start":6642,
                "strand":-1
            },
            {
                "domains":[],
                "end":7655,
                "id":"gnl_Bakta_OCBKLD_13335",
                "start":7493,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":131.7,
                        "code":"PF01593",
                        "end":482,
                        "start":34
                    }
                ],
                "end":9196,
                "id":"gnl_Bakta_OCBKLD_13340",
                "start":7654,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":62.3,
                        "code":"PF01209",
                        "end":211,
                        "start":10
                    }
                ],
                "end":9863,
                "id":"gnl_Bakta_OCBKLD_13345",
                "start":9206,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":232.4,
                        "code":"PF00494",
                        "end":288,
                        "start":27
                    }
                ],
                "end":10924,
                "id":"gnl_Bakta_OCBKLD_13350",
                "start":10000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.1,
                        "code":"PF01593",
                        "end":181,
                        "start":18
                    }
                ],
                "end":11526,
                "id":"gnl_Bakta_OCBKLD_13355",
                "start":10920,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":66.2,
                        "code":"PF01593",
                        "end":271,
                        "start":42
                    }
                ],
                "end":12455,
                "id":"gnl_Bakta_OCBKLD_13360",
                "start":11636,
                "strand":-1
            },
            {
                "domains":[],
                "end":12623,
                "id":"gnl_Bakta_OCBKLD_13365",
                "start":12482,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":179.4,
                        "code":"PF13561",
                        "end":244,
                        "start":13
                    }
                ],
                "end":14502,
                "id":"gnl_Bakta_OCBKLD_13370",
                "start":13758,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.0,
                        "code":"PF05305",
                        "end":101,
                        "start":24
                    }
                ],
                "end":14850,
                "id":"gnl_Bakta_OCBKLD_13375",
                "start":14514,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":194.8,
                        "code":"PF16877",
                        "end":152,
                        "start":34
                    }
                ],
                "end":15358,
                "id":"gnl_Bakta_OCBKLD_13380",
                "start":14899,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.3,
                        "code":"PF12680",
                        "end":105,
                        "start":7
                    }
                ],
                "end":15744,
                "id":"gnl_Bakta_OCBKLD_13385",
                "start":15354,
                "strand":1
            },
            {
                "domains":[],
                "end":16993,
                "id":"gnl_Bakta_OCBKLD_13390",
                "start":15994,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.6,
                        "code":"PF13810",
                        "end":170,
                        "start":1
                    }
                ],
                "end":17866,
                "id":"gnl_Bakta_OCBKLD_13395",
                "start":17326,
                "strand":1
            },
            {
                "domains":[],
                "end":19110,
                "id":"gnl_Bakta_OCBKLD_13400",
                "start":18300,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.0,
                        "code":"PF04945",
                        "end":103,
                        "start":67
                    }
                ],
                "end":20398,
                "id":"gnl_Bakta_OCBKLD_13405",
                "start":19633,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_3452, whole genome shotgun sequence",
        "end":20873,
        "id":"bins.011_sub.region001.contig_3452",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":503,
                "id":"gnl_Bakta_OCBKLD_25225",
                "start":8,
                "strand":1
            },
            {
                "domains":[],
                "end":1184,
                "id":"gnl_Bakta_OCBKLD_25230",
                "start":596,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":77.4,
                        "code":"PF01145",
                        "end":145,
                        "start":8
                    }
                ],
                "end":1958,
                "id":"gnl_Bakta_OCBKLD_25235",
                "start":1355,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":79.5,
                        "code":"PF01145",
                        "end":165,
                        "start":1
                    }
                ],
                "end":2887,
                "id":"hflK",
                "start":2125,
                "strand":-1
            },
            {
                "domains":[],
                "end":3872,
                "id":"gnl_Bakta_OCBKLD_25245",
                "start":3440,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":89.4,
                        "code":"PF16360",
                        "end":134,
                        "start":71
                    },
                    {
                        "bitscore":75.4,
                        "code":"PF13167",
                        "end":69,
                        "start":10
                    }
                ],
                "end":4604,
                "id":"gnl_Bakta_OCBKLD_25250",
                "start":4133,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":102.9,
                        "code":"PF17209",
                        "end":69,
                        "start":7
                    }
                ],
                "end":5107,
                "id":"gnl_Bakta_OCBKLD_25255",
                "start":4600,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":90.3,
                        "code":"PF00677",
                        "end":184,
                        "start":100
                    },
                    {
                        "bitscore":76.0,
                        "code":"PF00677",
                        "end":87,
                        "start":3
                    }
                ],
                "end":5995,
                "id":"gnl_Bakta_OCBKLD_25260",
                "start":5257,
                "strand":-1
            },
            {
                "domains":[],
                "end":6187,
                "id":"gnl_Bakta_OCBKLD_25265",
                "start":6052,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.4,
                        "code":"PF01872",
                        "end":80,
                        "start":38
                    }
                ],
                "end":6861,
                "id":"gnl_Bakta_OCBKLD_25270",
                "start":6525,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":30.9,
                        "code":"PF03477",
                        "end":132,
                        "start":44
                    }
                ],
                "end":7713,
                "id":"gnl_Bakta_OCBKLD_25275",
                "start":7206,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.3,
                        "code":"PF00464",
                        "end":54,
                        "start":1
                    }
                ],
                "end":8032,
                "id":"gnl_Bakta_OCBKLD_25280",
                "start":7765,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":113.7,
                        "code":"PF00464",
                        "end":137,
                        "start":1
                    }
                ],
                "end":8682,
                "id":"gnl_Bakta_OCBKLD_25285",
                "start":8043,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":68.6,
                        "code":"PF00464",
                        "end":51,
                        "start":1
                    }
                ],
                "end":8909,
                "id":"gnl_Bakta_OCBKLD_25290",
                "start":8678,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":80.1,
                        "code":"PF13489",
                        "end":213,
                        "start":33
                    }
                ],
                "end":9956,
                "id":"gnl_Bakta_OCBKLD_25295",
                "start":9212,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":105.3,
                        "code":"PF00494",
                        "end":264,
                        "start":11
                    }
                ],
                "end":10873,
                "id":"gnl_Bakta_OCBKLD_25300",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":121.6,
                        "code":"PF00106",
                        "end":209,
                        "start":13
                    }
                ],
                "end":12090,
                "id":"gnl_Bakta_OCBKLD_25305",
                "start":10869,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":204.4,
                        "code":"PF13561",
                        "end":284,
                        "start":51
                    }
                ],
                "end":13186,
                "id":"gnl_Bakta_OCBKLD_25310",
                "start":12289,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":96.6,
                        "code":"PF17954",
                        "end":170,
                        "start":85
                    },
                    {
                        "bitscore":82.7,
                        "code":"PF02678",
                        "end":58,
                        "start":1
                    }
                ],
                "end":13726,
                "id":"gnl_Bakta_OCBKLD_25315",
                "start":13207,
                "strand":-1
            },
            {
                "domains":[],
                "end":13908,
                "id":"gnl_Bakta_OCBKLD_25320",
                "start":13713,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":128.3,
                        "code":"PF06897",
                        "end":161,
                        "start":60
                    }
                ],
                "end":14726,
                "id":"gnl_Bakta_OCBKLD_25325",
                "start":14213,
                "strand":-1
            },
            {
                "domains":[],
                "end":15335,
                "id":"gnl_Bakta_OCBKLD_25330",
                "start":15053,
                "strand":-1
            },
            {
                "domains":[],
                "end":16205,
                "id":"gnl_Bakta_OCBKLD_25335",
                "start":15377,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":125.7,
                        "code":"PF13365",
                        "end":224,
                        "start":90
                    },
                    {
                        "bitscore":52.8,
                        "code":"PF13180",
                        "end":354,
                        "start":263
                    },
                    {
                        "bitscore":40.7,
                        "code":"PF17820",
                        "end":457,
                        "start":403
                    }
                ],
                "end":17964,
                "id":"gnl_Bakta_OCBKLD_25340",
                "start":16545,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":84.5,
                        "code":"PF00072",
                        "end":113,
                        "start":3
                    },
                    {
                        "bitscore":99.8,
                        "code":"PF00486",
                        "end":221,
                        "start":146
                    }
                ],
                "end":18996,
                "id":"phoB",
                "start":18321,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":39.2,
                        "code":"PF00672",
                        "end":270,
                        "start":217
                    },
                    {
                        "bitscore":37.8,
                        "code":"PF00512",
                        "end":344,
                        "start":275
                    },
                    {
                        "bitscore":92.5,
                        "code":"PF02518",
                        "end":498,
                        "start":389
                    }
                ],
                "end":20633,
                "id":"gnl_Bakta_OCBKLD_25350",
                "start":18992,
                "strand":1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
