var bs_data=[
    {
        "desc":"contig_3230, whole genome shotgun sequence",
        "end":29689,
        "id":"CONCOCT.10.region001.contig_3230",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":43.4,
                        "code":"PF14572",
                        "end":120,
                        "start":9
                    }
                ],
                "end":1261,
                "id":"gnl_Bakta_DNKOAA_17795",
                "start":898,
                "strand":1
            },
            {
                "domains":[],
                "end":2068,
                "id":"gnl_Bakta_DNKOAA_17805",
                "start":1486,
                "strand":-1
            },
            {
                "domains":[],
                "end":2730,
                "id":"gnl_Bakta_DNKOAA_17810",
                "start":2409,
                "strand":1
            },
            {
                "domains":[],
                "end":3061,
                "id":"CONCOCT.10.region001.contig_3230_ORF5",
                "start":2830,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":85.4,
                        "code":"PF01871",
                        "end":169,
                        "start":20
                    }
                ],
                "end":4675,
                "id":"gnl_Bakta_DNKOAA_17825",
                "start":4153,
                "strand":1
            },
            {
                "domains":[],
                "end":5080,
                "id":"gnl_Bakta_DNKOAA_17830",
                "start":4867,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":51.5,
                        "code":"PF00072",
                        "end":95,
                        "start":25
                    }
                ],
                "end":5651,
                "id":"gnl_Bakta_DNKOAA_17835",
                "start":5363,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.6,
                        "code":"PF00512",
                        "end":88,
                        "start":22
                    }
                ],
                "end":6401,
                "id":"gnl_Bakta_DNKOAA_17840",
                "start":5702,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":98.1,
                        "code":"PF00072",
                        "end":117,
                        "start":7
                    }
                ],
                "end":6789,
                "id":"gnl_Bakta_DNKOAA_17845",
                "start":6369,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":79.6,
                        "code":"PF02518",
                        "end":711,
                        "start":593
                    },
                    {
                        "bitscore":28.9,
                        "code":"PF00512",
                        "end":546,
                        "start":489
                    },
                    {
                        "bitscore":88.4,
                        "code":"PF08668",
                        "end":213,
                        "start":19
                    }
                ],
                "end":8973,
                "id":"gnl_Bakta_DNKOAA_17850",
                "start":6798,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.4,
                        "code":"PF13490",
                        "end":47,
                        "start":13
                    }
                ],
                "end":9717,
                "id":"gnl_Bakta_DNKOAA_17855",
                "start":9447,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":55.4,
                        "code":"PF04542",
                        "end":99,
                        "start":32
                    }
                ],
                "end":10316,
                "id":"CONCOCT.10.region001.contig_3230_ORF14",
                "start":9800,
                "strand":-1
            },
            {
                "domains":[],
                "end":10443,
                "id":"gnl_Bakta_DNKOAA_17865",
                "start":10353,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":58.6,
                        "code":"PF02954",
                        "end":94,
                        "start":53
                    }
                ],
                "end":10874,
                "id":"gnl_Bakta_DNKOAA_17870",
                "start":10556,
                "strand":-1
            },
            {
                "domains":[],
                "end":11646,
                "id":"gnl_Bakta_DNKOAA_17875",
                "start":11184,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.5,
                        "code":"PF02518",
                        "end":170,
                        "start":94
                    }
                ],
                "end":13284,
                "id":"gnl_Bakta_DNKOAA_17885",
                "start":12699,
                "strand":-1
            },
            {
                "domains":[],
                "end":13781,
                "id":"gnl_Bakta_DNKOAA_17890",
                "start":13640,
                "strand":1
            },
            {
                "domains":[],
                "end":14249,
                "id":"gnl_Bakta_DNKOAA_17895",
                "start":13847,
                "strand":-1
            },
            {
                "domains":[],
                "end":14717,
                "id":"gnl_Bakta_DNKOAA_17900",
                "start":14537,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":166.1,
                        "code":"PF03205",
                        "end":133,
                        "start":4
                    }
                ],
                "end":15378,
                "id":"gnl_Bakta_DNKOAA_17905",
                "start":14886,
                "strand":-1
            },
            {
                "domains":[],
                "end":15706,
                "id":"gnl_Bakta_DNKOAA_17910",
                "start":15478,
                "strand":1
            },
            {
                "domains":[],
                "end":16225,
                "id":"gnl_Bakta_DNKOAA_17915",
                "start":15790,
                "strand":-1
            },
            {
                "domains":[],
                "end":16944,
                "id":"gnl_Bakta_DNKOAA_17920",
                "start":16395,
                "strand":-1
            },
            {
                "domains":[],
                "end":18079,
                "id":"gnl_Bakta_DNKOAA_17925",
                "start":17209,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":88.9,
                        "code":"PF00109",
                        "end":157,
                        "start":8
                    }
                ],
                "end":18920,
                "id":"gnl_Bakta_DNKOAA_17930",
                "start":18404,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":93.7,
                        "code":"PF00109",
                        "end":112,
                        "start":2
                    },
                    {
                        "bitscore":105.6,
                        "code":"PF02801",
                        "end":241,
                        "start":120
                    },
                    {
                        "bitscore":97.0,
                        "code":"PF00698",
                        "end":711,
                        "start":416
                    }
                ],
                "end":21202,
                "id":"gnl_Bakta_DNKOAA_17935",
                "start":18949,
                "strand":1
            },
            {
                "domains":[],
                "end":21573,
                "id":"gnl_Bakta_DNKOAA_17940",
                "start":21261,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":21.4,
                        "code":"PF00550",
                        "end":132,
                        "start":64
                    }
                ],
                "end":22291,
                "id":"gnl_Bakta_DNKOAA_17945",
                "start":21607,
                "strand":1
            },
            {
                "domains":[],
                "end":22467,
                "id":"gnl_Bakta_DNKOAA_17950",
                "start":22287,
                "strand":1
            },
            {
                "domains":[],
                "end":23228,
                "id":"gnl_Bakta_DNKOAA_17955",
                "start":22463,
                "strand":1
            },
            {
                "domains":[],
                "end":24181,
                "id":"gnl_Bakta_DNKOAA_17960",
                "start":23200,
                "strand":1
            },
            {
                "domains":[],
                "end":24972,
                "id":"gnl_Bakta_DNKOAA_17965",
                "start":24144,
                "strand":-1
            },
            {
                "domains":[],
                "end":25486,
                "id":"gnl_Bakta_DNKOAA_17970",
                "start":25342,
                "strand":1
            },
            {
                "domains":[],
                "end":26139,
                "id":"CONCOCT.10.region001.contig_3230_ORF37",
                "start":25482,
                "strand":1
            },
            {
                "domains":[],
                "end":26473,
                "id":"gnl_Bakta_DNKOAA_17980",
                "start":26164,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":71.0,
                        "code":"PF13382",
                        "end":168,
                        "start":100
                    },
                    {
                        "bitscore":32.3,
                        "code":"PF13382",
                        "end":64,
                        "start":10
                    }
                ],
                "end":27130,
                "id":"gnl_Bakta_DNKOAA_17985",
                "start":26593,
                "strand":-1
            },
            {
                "domains":[],
                "end":27402,
                "id":"gnl_Bakta_DNKOAA_17990",
                "start":27183,
                "strand":1
            },
            {
                "domains":[],
                "end":27704,
                "id":"gnl_Bakta_DNKOAA_17995",
                "start":27557,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_424, whole genome shotgun sequence",
        "end":27951,
        "id":"CONCOCT.10.region001.contig_424",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":765,
                "id":"gnl_Bakta_DNKOAA_21930",
                "start":597,
                "strand":-1
            },
            {
                "domains":[],
                "end":1198,
                "id":"gnl_Bakta_DNKOAA_21935",
                "start":829,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":40.8,
                        "code":"PF07690",
                        "end":132,
                        "start":3
                    }
                ],
                "end":2002,
                "id":"gnl_Bakta_DNKOAA_21945",
                "start":1519,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":35.2,
                        "code":"PF00582",
                        "end":91,
                        "start":4
                    }
                ],
                "end":2996,
                "id":"gnl_Bakta_DNKOAA_21955",
                "start":2690,
                "strand":-1
            },
            {
                "domains":[],
                "end":3962,
                "id":"gnl_Bakta_DNKOAA_21960",
                "start":3461,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":126.9,
                        "code":"PF02801",
                        "end":142,
                        "start":25
                    },
                    {
                        "bitscore":34.6,
                        "code":"PF16197",
                        "end":217,
                        "start":144
                    }
                ],
                "end":4939,
                "id":"gnl_Bakta_DNKOAA_21965",
                "start":4084,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":74.8,
                        "code":"PF00109",
                        "end":169,
                        "start":31
                    },
                    {
                        "bitscore":74.3,
                        "code":"PF02801",
                        "end":296,
                        "start":177
                    }
                ],
                "end":7951,
                "id":"gnl_Bakta_DNKOAA_21975",
                "start":5074,
                "strand":1
            },
            {
                "domains":[],
                "end":8133,
                "id":"gnl_Bakta_DNKOAA_21980",
                "start":7998,
                "strand":1
            },
            {
                "domains":[],
                "end":8734,
                "id":"gnl_Bakta_DNKOAA_21985",
                "start":8134,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.4,
                        "code":"PF07977",
                        "end":133,
                        "start":1
                    }
                ],
                "end":9408,
                "id":"gnl_Bakta_DNKOAA_21990",
                "start":8724,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":123.4,
                        "code":"PF07977",
                        "end":181,
                        "start":45
                    }
                ],
                "end":10390,
                "id":"gnl_Bakta_DNKOAA_22000",
                "start":9805,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":102.8,
                        "code":"PF00561",
                        "end":242,
                        "start":12
                    }
                ],
                "end":11207,
                "id":"gnl_Bakta_DNKOAA_22005",
                "start":10478,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":67.8,
                        "code":"PF00501",
                        "end":161,
                        "start":1
                    }
                ],
                "end":12040,
                "id":"gnl_Bakta_DNKOAA_22010",
                "start":11554,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":79.2,
                        "code":"PF00501",
                        "end":169,
                        "start":1
                    }
                ],
                "end":12840,
                "id":"gnl_Bakta_DNKOAA_22015",
                "start":12036,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":74.3,
                        "code":"PF01073",
                        "end":134,
                        "start":1
                    }
                ],
                "end":13511,
                "id":"gnl_Bakta_DNKOAA_22025",
                "start":13070,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":35.6,
                        "code":"PF01073",
                        "end":61,
                        "start":1
                    }
                ],
                "end":14017,
                "id":"gnl_Bakta_DNKOAA_22030",
                "start":13624,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":32.0,
                        "code":"PF10114",
                        "end":80,
                        "start":1
                    }
                ],
                "end":14493,
                "id":"pocR",
                "start":14202,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":74.2,
                        "code":"PF01595",
                        "end":173,
                        "start":37
                    }
                ],
                "end":15212,
                "id":"CONCOCT.10.region001.contig_424_ORF24",
                "start":14690,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":22.5,
                        "code":"PF00571",
                        "end":118,
                        "start":63
                    }
                ],
                "end":15911,
                "id":"gnl_Bakta_DNKOAA_22050",
                "start":15377,
                "strand":1
            },
            {
                "domains":[],
                "end":16820,
                "id":"gnl_Bakta_DNKOAA_22055",
                "start":16310,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":116.3,
                        "code":"PF02540",
                        "end":143,
                        "start":1
                    }
                ],
                "end":17394,
                "id":"CONCOCT.10.region001.contig_424_ORF27",
                "start":16959,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":32.3,
                        "code":"PF00571",
                        "end":286,
                        "start":245
                    },
                    {
                        "bitscore":30.2,
                        "code":"PF02272",
                        "end":236,
                        "start":102
                    }
                ],
                "end":18922,
                "id":"gnl_Bakta_DNKOAA_22070",
                "start":17800,
                "strand":-1
            },
            {
                "domains":[],
                "end":19591,
                "id":"CONCOCT.10.region001.contig_424_ORF31",
                "start":19138,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":46.9,
                        "code":"PF13740",
                        "end":76,
                        "start":2
                    },
                    {
                        "bitscore":24.6,
                        "code":"PF13740",
                        "end":173,
                        "start":93
                    }
                ],
                "end":20855,
                "id":"gnl_Bakta_DNKOAA_22090",
                "start":20300,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":86.4,
                        "code":"PF05167",
                        "end":112,
                        "start":12
                    }
                ],
                "end":21270,
                "id":"gnl_Bakta_DNKOAA_22095",
                "start":20877,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":455.9,
                        "code":"PF05167",
                        "end":308,
                        "start":1
                    }
                ],
                "end":22253,
                "id":"gnl_Bakta_DNKOAA_22100",
                "start":21233,
                "strand":1
            },
            {
                "domains":[],
                "end":23035,
                "id":"gnl_Bakta_DNKOAA_22105",
                "start":22501,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.1,
                        "code":"PF13304",
                        "end":39,
                        "start":1
                    }
                ],
                "end":23832,
                "id":"gnl_Bakta_DNKOAA_22115",
                "start":23391,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.5,
                        "code":"PF00005",
                        "end":101,
                        "start":1
                    }
                ],
                "end":24206,
                "id":"gnl_Bakta_DNKOAA_22120",
                "start":23897,
                "strand":-1
            },
            {
                "domains":[],
                "end":24603,
                "id":"gnl_Bakta_DNKOAA_22125",
                "start":24501,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.4,
                        "code":"PF07885",
                        "end":49,
                        "start":1
                    }
                ],
                "end":24898,
                "id":"gnl_Bakta_DNKOAA_22130",
                "start":24616,
                "strand":1
            },
            {
                "domains":[],
                "end":25443,
                "id":"trkA",
                "start":25110,
                "strand":1
            },
            {
                "domains":[],
                "end":26565,
                "id":"gnl_Bakta_DNKOAA_22145",
                "start":25572,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.3,
                        "code":"PF00160",
                        "end":78,
                        "start":1
                    }
                ],
                "end":27167,
                "id":"gnl_Bakta_DNKOAA_22150",
                "start":26918,
                "strand":1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
