var bs_data=[
    {
        "desc":"contig_213, whole genome shotgun sequence",
        "end":35228,
        "id":"502.region001.contig_213",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":796,
                "id":"gnl_Bakta_PEOBOA_12080",
                "start":142,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":136.2,
                        "code":"PF00698",
                        "end":290,
                        "start":93
                    }
                ],
                "end":1794,
                "id":"gnl_Bakta_PEOBOA_12085",
                "start":912,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":86.8,
                        "code":"PF02801",
                        "end":251,
                        "start":139
                    },
                    {
                        "bitscore":94.2,
                        "code":"PF00109",
                        "end":131,
                        "start":2
                    }
                ],
                "end":2723,
                "id":"gnl_Bakta_PEOBOA_12090",
                "start":1961,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":63.3,
                        "code":"PF00109",
                        "end":230,
                        "start":83
                    }
                ],
                "end":3447,
                "id":"gnl_Bakta_PEOBOA_12095",
                "start":2685,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":57.4,
                        "code":"PF03060",
                        "end":163,
                        "start":4
                    }
                ],
                "end":4100,
                "id":"gnl_Bakta_PEOBOA_12100",
                "start":3503,
                "strand":-1
            },
            {
                "domains":[],
                "end":5268,
                "id":"gnl_Bakta_PEOBOA_12105",
                "start":4104,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":78.4,
                        "code":"PF04028",
                        "end":134,
                        "start":66
                    }
                ],
                "end":6052,
                "id":"gnl_Bakta_PEOBOA_12110",
                "start":5452,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":42.4,
                        "code":"PF18602",
                        "end":112,
                        "start":19
                    }
                ],
                "end":6961,
                "id":"gnl_Bakta_PEOBOA_12115",
                "start":6616,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.5,
                        "code":"PF13436",
                        "end":69,
                        "start":27
                    }
                ],
                "end":7304,
                "id":"gnl_Bakta_PEOBOA_12120",
                "start":7031,
                "strand":1
            },
            {
                "domains":[],
                "end":7799,
                "id":"gnl_Bakta_PEOBOA_12130",
                "start":7472,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":101.6,
                        "code":"PF00313",
                        "end":66,
                        "start":2
                    }
                ],
                "end":8425,
                "id":"gnl_Bakta_PEOBOA_12135",
                "start":8224,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.9,
                        "code":"PF14765",
                        "end":292,
                        "start":131
                    }
                ],
                "end":9682,
                "id":"gnl_Bakta_PEOBOA_12140",
                "start":8743,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":99.2,
                        "code":"PF08659",
                        "end":122,
                        "start":3
                    }
                ],
                "end":10223,
                "id":"gnl_Bakta_PEOBOA_12145",
                "start":9662,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.0,
                        "code":"PF00550",
                        "end":71,
                        "start":2
                    }
                ],
                "end":11516,
                "id":"gnl_Bakta_PEOBOA_12150",
                "start":10922,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.6,
                        "code":"PF00550",
                        "end":67,
                        "start":1
                    }
                ],
                "end":11833,
                "id":"gnl_Bakta_PEOBOA_12155",
                "start":11515,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":128.8,
                        "code":"PF00698",
                        "end":873,
                        "start":549
                    },
                    {
                        "bitscore":39.4,
                        "code":"PF16197",
                        "end":473,
                        "start":383
                    },
                    {
                        "bitscore":142.4,
                        "code":"PF02801",
                        "end":381,
                        "start":263
                    },
                    {
                        "bitscore":166.5,
                        "code":"PF00109",
                        "end":255,
                        "start":1
                    }
                ],
                "end":15228,
                "id":"gnl_Bakta_PEOBOA_12160",
                "start":11832,
                "strand":-1
            },
            {
                "domains":[],
                "end":16147,
                "id":"gnl_Bakta_PEOBOA_12165",
                "start":15553,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":110.7,
                        "code":"PF21607",
                        "end":403,
                        "start":324
                    },
                    {
                        "bitscore":46.2,
                        "code":"PF03060",
                        "end":318,
                        "start":17
                    }
                ],
                "end":17623,
                "id":"gnl_Bakta_PEOBOA_12170",
                "start":16150,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":179.2,
                        "code":"PF00589",
                        "end":287,
                        "start":113
                    },
                    {
                        "bitscore":61.5,
                        "code":"PF02899",
                        "end":92,
                        "start":9
                    }
                ],
                "end":18866,
                "id":"xerC",
                "start":17966,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":239.8,
                        "code":"PF00557",
                        "end":354,
                        "start":151
                    },
                    {
                        "bitscore":75.1,
                        "code":"PF01321",
                        "end":144,
                        "start":8
                    }
                ],
                "end":19997,
                "id":"gnl_Bakta_PEOBOA_12180",
                "start":18884,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":78.0,
                        "code":"PF01590",
                        "end":168,
                        "start":29
                    },
                    {
                        "bitscore":65.9,
                        "code":"PF03861",
                        "end":231,
                        "start":178
                    }
                ],
                "end":21040,
                "id":"gnl_Bakta_PEOBOA_12185",
                "start":20326,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":34.5,
                        "code":"PF01645",
                        "end":411,
                        "start":271
                    }
                ],
                "end":22887,
                "id":"gnl_Bakta_PEOBOA_12190",
                "start":21303,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.3,
                        "code":"PF07883",
                        "end":431,
                        "start":360
                    },
                    {
                        "bitscore":53.9,
                        "code":"PF01381",
                        "end":312,
                        "start":258
                    }
                ],
                "end":24323,
                "id":"gnl_Bakta_PEOBOA_12195",
                "start":23021,
                "strand":-1
            },
            {
                "domains":[],
                "end":25740,
                "id":"gnl_Bakta_PEOBOA_12200",
                "start":24549,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":44.9,
                        "code":"PF12773",
                        "end":345,
                        "start":300
                    },
                    {
                        "bitscore":213.3,
                        "code":"PF13421",
                        "end":234,
                        "start":23
                    }
                ],
                "end":26920,
                "id":"gnl_Bakta_PEOBOA_12205",
                "start":25783,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":317.4,
                        "code":"PF02618",
                        "end":331,
                        "start":45
                    }
                ],
                "end":27994,
                "id":"gnl_Bakta_PEOBOA_12210",
                "start":26983,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.8,
                        "code":"PF12838",
                        "end":61,
                        "start":15
                    }
                ],
                "end":28679,
                "id":"gnl_Bakta_PEOBOA_12215",
                "start":28475,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":215.5,
                        "code":"PF01855",
                        "end":248,
                        "start":16
                    },
                    {
                        "bitscore":69.3,
                        "code":"PF17147",
                        "end":370,
                        "start":276
                    }
                ],
                "end":29837,
                "id":"gnl_Bakta_PEOBOA_12220",
                "start":28688,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":111.6,
                        "code":"PF02775",
                        "end":196,
                        "start":48
                    }
                ],
                "end":30644,
                "id":"gnl_Bakta_PEOBOA_12225",
                "start":29840,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":112.5,
                        "code":"PF01558",
                        "end":174,
                        "start":12
                    }
                ],
                "end":31192,
                "id":"korC",
                "start":30646,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":76.8,
                        "code":"PF07603",
                        "end":448,
                        "start":335
                    },
                    {
                        "bitscore":125.5,
                        "code":"PF00069",
                        "end":274,
                        "start":7
                    }
                ],
                "end":32741,
                "id":"gnl_Bakta_PEOBOA_12235",
                "start":31382,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.3,
                        "code":"PF12850",
                        "end":209,
                        "start":1
                    }
                ],
                "end":33546,
                "id":"gnl_Bakta_PEOBOA_12240",
                "start":32814,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":87.6,
                        "code":"PF01478",
                        "end":214,
                        "start":105
                    },
                    {
                        "bitscore":115.4,
                        "code":"PF06750",
                        "end":95,
                        "start":12
                    }
                ],
                "end":34368,
                "id":"gnl_Bakta_PEOBOA_12245",
                "start":33597,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_838, whole genome shotgun sequence",
        "end":47141,
        "id":"502.region001.contig_838",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":311.7,
                        "code":"PF00282",
                        "end":379,
                        "start":28
                    }
                ],
                "end":3433,
                "id":"gnl_Bakta_PEOBOA_27985",
                "start":2038,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.5,
                        "code":"PF21082",
                        "end":61,
                        "start":1
                    }
                ],
                "end":4416,
                "id":"gnl_Bakta_PEOBOA_27990",
                "start":4080,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":101.4,
                        "code":"PF13847",
                        "end":202,
                        "start":75
                    }
                ],
                "end":5548,
                "id":"gnl_Bakta_PEOBOA_27995",
                "start":4936,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":94.6,
                        "code":"PF01565",
                        "end":190,
                        "start":55
                    },
                    {
                        "bitscore":41.2,
                        "code":"PF08031",
                        "end":471,
                        "start":426
                    }
                ],
                "end":7369,
                "id":"gnl_Bakta_PEOBOA_28000",
                "start":5938,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":51.7,
                        "code":"PF12441",
                        "end":72,
                        "start":14
                    }
                ],
                "end":8301,
                "id":"copG",
                "start":8028,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":67.6,
                        "code":"PF05726",
                        "end":274,
                        "start":177
                    },
                    {
                        "bitscore":101.6,
                        "code":"PF02678",
                        "end":124,
                        "start":18
                    }
                ],
                "end":10045,
                "id":"gnl_Bakta_PEOBOA_28010",
                "start":9151,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":39.8,
                        "code":"PF02566",
                        "end":84,
                        "start":1
                    }
                ],
                "end":10343,
                "id":"gnl_Bakta_PEOBOA_28015",
                "start":10082,
                "strand":-1
            },
            {
                "domains":[],
                "end":10501,
                "id":"gnl_Bakta_PEOBOA_28020",
                "start":10339,
                "strand":-1
            },
            {
                "domains":[],
                "end":11049,
                "id":"gnl_Bakta_PEOBOA_28030",
                "start":10785,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":46.0,
                        "code":"PF00106",
                        "end":63,
                        "start":6
                    }
                ],
                "end":11566,
                "id":"gnl_Bakta_PEOBOA_28035",
                "start":11368,
                "strand":-1
            },
            {
                "domains":[],
                "end":13175,
                "id":"gnl_Bakta_PEOBOA_28040",
                "start":12500,
                "strand":-1
            },
            {
                "domains":[],
                "end":13601,
                "id":"gnl_Bakta_PEOBOA_28045",
                "start":13214,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":48.8,
                        "code":"PF02405",
                        "end":118,
                        "start":27
                    }
                ],
                "end":14545,
                "id":"gnl_Bakta_PEOBOA_28050",
                "start":13753,
                "strand":-1
            },
            {
                "domains":[],
                "end":14896,
                "id":"gnl_Bakta_PEOBOA_28055",
                "start":14575,
                "strand":-1
            },
            {
                "domains":[],
                "end":15729,
                "id":"gnl_Bakta_PEOBOA_28065",
                "start":15021,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":62.9,
                        "code":"PF00263",
                        "end":548,
                        "start":445
                    },
                    {
                        "bitscore":49.1,
                        "code":"PF03958",
                        "end":358,
                        "start":280
                    },
                    {
                        "bitscore":47.2,
                        "code":"PF03958",
                        "end":275,
                        "start":201
                    },
                    {
                        "bitscore":47.8,
                        "code":"PF03958",
                        "end":198,
                        "start":137
                    },
                    {
                        "bitscore":87.4,
                        "code":"PF21305",
                        "end":109,
                        "start":40
                    }
                ],
                "end":17640,
                "id":"gnl_Bakta_PEOBOA_28075",
                "start":15957,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.2,
                        "code":"PF17820",
                        "end":278,
                        "start":224
                    },
                    {
                        "bitscore":63.7,
                        "code":"PF11356",
                        "end":154,
                        "start":7
                    }
                ],
                "end":18529,
                "id":"gnl_Bakta_PEOBOA_28080",
                "start":17656,
                "strand":-1
            },
            {
                "domains":[],
                "end":19476,
                "id":"gnl_Bakta_PEOBOA_28085",
                "start":18621,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":160.4,
                        "code":"PF00109",
                        "end":269,
                        "start":4
                    },
                    {
                        "bitscore":119.1,
                        "code":"PF02801",
                        "end":394,
                        "start":277
                    }
                ],
                "end":21215,
                "id":"gnl_Bakta_PEOBOA_28090",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":135.7,
                        "code":"PF00109",
                        "end":317,
                        "start":39
                    },
                    {
                        "bitscore":82.7,
                        "code":"PF02801",
                        "end":437,
                        "start":325
                    },
                    {
                        "bitscore":23.3,
                        "code":"PF07977",
                        "end":1311,
                        "start":1181
                    },
                    {
                        "bitscore":109.1,
                        "code":"PF07977",
                        "end":1527,
                        "start":1390
                    },
                    {
                        "bitscore":24.8,
                        "code":"PF07977",
                        "end":1733,
                        "start":1598
                    },
                    {
                        "bitscore":111.4,
                        "code":"PF07977",
                        "end":1930,
                        "start":1794
                    }
                ],
                "end":27141,
                "id":"gnl_Bakta_PEOBOA_28095",
                "start":21321,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":28.0,
                        "code":"PF08545",
                        "end":150,
                        "start":57
                    },
                    {
                        "bitscore":49.6,
                        "code":"PF08541",
                        "end":286,
                        "start":198
                    }
                ],
                "end":28307,
                "id":"gnl_Bakta_PEOBOA_28105",
                "start":27446,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":104.5,
                        "code":"PF00561",
                        "end":293,
                        "start":45
                    }
                ],
                "end":29230,
                "id":"gnl_Bakta_PEOBOA_28110",
                "start":28300,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":173.2,
                        "code":"PF00501",
                        "end":435,
                        "start":46
                    }
                ],
                "end":31067,
                "id":"gnl_Bakta_PEOBOA_28115",
                "start":29300,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":181.1,
                        "code":"PF01073",
                        "end":267,
                        "start":13
                    }
                ],
                "end":32101,
                "id":"gnl_Bakta_PEOBOA_28120",
                "start":31063,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.1,
                        "code":"PF10114",
                        "end":165,
                        "start":5
                    }
                ],
                "end":32880,
                "id":"pocR",
                "start":32361,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":40.7,
                        "code":"PF07992",
                        "end":170,
                        "start":5
                    }
                ],
                "end":33980,
                "id":"gnl_Bakta_PEOBOA_28135",
                "start":33005,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":30.6,
                        "code":"PF13187",
                        "end":224,
                        "start":180
                    },
                    {
                        "bitscore":107.8,
                        "code":"PF02662",
                        "end":373,
                        "start":252
                    }
                ],
                "end":35639,
                "id":"gnl_Bakta_PEOBOA_28140",
                "start":34505,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":39.4,
                        "code":"PF13183",
                        "end":95,
                        "start":33
                    }
                ],
                "end":36377,
                "id":"gnl_Bakta_PEOBOA_28145",
                "start":35642,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.9,
                        "code":"PF02754",
                        "end":114,
                        "start":20
                    }
                ],
                "end":36908,
                "id":"gnl_Bakta_PEOBOA_28150",
                "start":36470,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.6,
                        "code":"PF13740",
                        "end":78,
                        "start":3
                    },
                    {
                        "bitscore":34.4,
                        "code":"PF13740",
                        "end":173,
                        "start":93
                    }
                ],
                "end":37459,
                "id":"gnl_Bakta_PEOBOA_28155",
                "start":36904,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":586.4,
                        "code":"PF05167",
                        "end":427,
                        "start":12
                    }
                ],
                "end":38871,
                "id":"gnl_Bakta_PEOBOA_28160",
                "start":37497,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":78.3,
                        "code":"PF00528",
                        "end":271,
                        "start":89
                    }
                ],
                "end":39788,
                "id":"gnl_Bakta_PEOBOA_28165",
                "start":38966,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":179.5,
                        "code":"PF00497",
                        "end":269,
                        "start":48
                    }
                ],
                "end":40718,
                "id":"gnl_Bakta_PEOBOA_28170",
                "start":39884,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.7,
                        "code":"PF00528",
                        "end":291,
                        "start":80
                    }
                ],
                "end":41657,
                "id":"gnl_Bakta_PEOBOA_28175",
                "start":40760,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":78.5,
                        "code":"PF00582",
                        "end":130,
                        "start":1
                    }
                ],
                "end":42123,
                "id":"uspA",
                "start":41730,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":20.8,
                        "code":"PF13432",
                        "end":951,
                        "start":887
                    },
                    {
                        "bitscore":21.4,
                        "code":"PF13432",
                        "end":759,
                        "start":695
                    },
                    {
                        "bitscore":16.0,
                        "code":"PF13432",
                        "end":530,
                        "start":488
                    }
                ],
                "end":45423,
                "id":"gnl_Bakta_PEOBOA_28185",
                "start":42525,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":121.2,
                        "code":"PF12850",
                        "end":150,
                        "start":10
                    }
                ],
                "end":46203,
                "id":"gnl_Bakta_PEOBOA_28190",
                "start":45705,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.8,
                        "code":"PF02527",
                        "end":226,
                        "start":162
                    },
                    {
                        "bitscore":110.8,
                        "code":"PF02527",
                        "end":159,
                        "start":34
                    }
                ],
                "end":47006,
                "id":"gnl_Bakta_PEOBOA_28195",
                "start":46226,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_1735, whole genome shotgun sequence",
        "end":21893,
        "id":"CONCOCT.4_sub.region001.contig_1735",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":55.9,
                        "code":"PF08915",
                        "end":74,
                        "start":3
                    }
                ],
                "end":757,
                "id":"CONCOCT.4_sub.region001.contig_1735_ORF1",
                "start":532,
                "strand":1
            },
            {
                "domains":[],
                "end":1523,
                "id":"gnl_Bakta_FEECGD_06080",
                "start":1400,
                "strand":-1
            },
            {
                "domains":[],
                "end":1930,
                "id":"gnl_Bakta_FEECGD_06085",
                "start":1519,
                "strand":-1
            },
            {
                "domains":[],
                "end":2679,
                "id":"gnl_Bakta_FEECGD_06090",
                "start":2493,
                "strand":-1
            },
            {
                "domains":[],
                "end":3923,
                "id":"gnl_Bakta_FEECGD_06095",
                "start":3299,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.7,
                        "code":"PF04011",
                        "end":79,
                        "start":32
                    }
                ],
                "end":4299,
                "id":"gnl_Bakta_FEECGD_06100",
                "start":4059,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":110.7,
                        "code":"PF04011",
                        "end":101,
                        "start":1
                    }
                ],
                "end":4607,
                "id":"lemA",
                "start":4298,
                "strand":1
            },
            {
                "domains":[],
                "end":5045,
                "id":"gnl_Bakta_FEECGD_06110",
                "start":4766,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":112.8,
                        "code":"PF20990",
                        "end":389,
                        "start":112
                    }
                ],
                "end":6391,
                "id":"gnl_Bakta_FEECGD_06115",
                "start":5221,
                "strand":1
            },
            {
                "domains":[],
                "end":7258,
                "id":"gnl_Bakta_FEECGD_06120",
                "start":6727,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":73.4,
                        "code":"PF00011",
                        "end":147,
                        "start":46
                    }
                ],
                "end":7775,
                "id":"gnl_Bakta_FEECGD_06125",
                "start":7295,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":118.7,
                        "code":"PF21607",
                        "end":468,
                        "start":389
                    }
                ],
                "end":9853,
                "id":"gnl_Bakta_FEECGD_06130",
                "start":8221,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":195.2,
                        "code":"PF00109",
                        "end":295,
                        "start":15
                    },
                    {
                        "bitscore":82.6,
                        "code":"PF02801",
                        "end":387,
                        "start":303
                    }
                ],
                "end":11076,
                "id":"gnl_Bakta_FEECGD_06135",
                "start":9849,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":39.0,
                        "code":"PF16197",
                        "end":130,
                        "start":17
                    }
                ],
                "end":11572,
                "id":"gnl_Bakta_FEECGD_06140",
                "start":11062,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":67.2,
                        "code":"PF00698",
                        "end":161,
                        "start":1
                    }
                ],
                "end":12137,
                "id":"gnl_Bakta_FEECGD_06145",
                "start":11591,
                "strand":1
            },
            {
                "domains":[],
                "end":13266,
                "id":"gnl_Bakta_FEECGD_06150",
                "start":12195,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":40.9,
                        "code":"PF00550",
                        "end":117,
                        "start":48
                    },
                    {
                        "bitscore":37.0,
                        "code":"PF00550",
                        "end":216,
                        "start":147
                    },
                    {
                        "bitscore":29.7,
                        "code":"PF00550",
                        "end":294,
                        "start":243
                    }
                ],
                "end":14362,
                "id":"gnl_Bakta_FEECGD_06155",
                "start":13390,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":68.0,
                        "code":"PF08659",
                        "end":279,
                        "start":114
                    }
                ],
                "end":15547,
                "id":"gnl_Bakta_FEECGD_06160",
                "start":14704,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":34.2,
                        "code":"PF08659",
                        "end":52,
                        "start":1
                    },
                    {
                        "bitscore":31.6,
                        "code":"PF21089",
                        "end":203,
                        "start":108
                    }
                ],
                "end":16388,
                "id":"gnl_Bakta_FEECGD_06165",
                "start":15560,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":26.9,
                        "code":"PF14765",
                        "end":104,
                        "start":4
                    }
                ],
                "end":16770,
                "id":"gnl_Bakta_FEECGD_06170",
                "start":16404,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.7,
                        "code":"PF00109",
                        "end":51,
                        "start":4
                    }
                ],
                "end":16931,
                "id":"gnl_Bakta_FEECGD_06175",
                "start":16772,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.6,
                        "code":"PF00109",
                        "end":178,
                        "start":1
                    },
                    {
                        "bitscore":63.1,
                        "code":"PF02801",
                        "end":268,
                        "start":186
                    }
                ],
                "end":18453,
                "id":"gnl_Bakta_FEECGD_06180",
                "start":17055,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":101.4,
                        "code":"PF00109",
                        "end":197,
                        "start":1
                    },
                    {
                        "bitscore":41.8,
                        "code":"PF02801",
                        "end":321,
                        "start":265
                    }
                ],
                "end":19667,
                "id":"gnl_Bakta_FEECGD_06185",
                "start":18431,
                "strand":1
            },
            {
                "domains":[],
                "end":20414,
                "id":"gnl_Bakta_FEECGD_06190",
                "start":19979,
                "strand":1
            },
            {
                "domains":[],
                "end":21486,
                "id":"gnl_Bakta_FEECGD_06195",
                "start":20595,
                "strand":1
            },
            {
                "domains":[],
                "end":21886,
                "id":"gnl_Bakta_FEECGD_06200",
                "start":21475,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_1854, whole genome shotgun sequence",
        "end":29416,
        "id":"CONCOCT.4_sub.region001.contig_1854",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":46.9,
                        "code":"PF00707",
                        "end":50,
                        "start":1
                    }
                ],
                "end":397,
                "id":"gnl_Bakta_FEECGD_06205",
                "start":235,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":108.7,
                        "code":"PF05198",
                        "end":117,
                        "start":48
                    }
                ],
                "end":879,
                "id":"gnl_Bakta_FEECGD_06210",
                "start":456,
                "strand":-1
            },
            {
                "domains":[],
                "end":1279,
                "id":"gnl_Bakta_FEECGD_06215",
                "start":1075,
                "strand":-1
            },
            {
                "domains":[],
                "end":1601,
                "id":"gnl_Bakta_FEECGD_06220",
                "start":1280,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.0,
                        "code":"PF00587",
                        "end":83,
                        "start":1
                    }
                ],
                "end":1852,
                "id":"gnl_Bakta_FEECGD_06225",
                "start":1588,
                "strand":-1
            },
            {
                "domains":[],
                "end":2798,
                "id":"gnl_Bakta_FEECGD_06230",
                "start":2129,
                "strand":-1
            },
            {
                "domains":[],
                "end":3984,
                "id":"gnl_Bakta_FEECGD_06240",
                "start":3483,
                "strand":1
            },
            {
                "domains":[],
                "end":4797,
                "id":"gnl_Bakta_FEECGD_06250",
                "start":4473,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":63.7,
                        "code":"PF12169",
                        "end":373,
                        "start":232
                    },
                    {
                        "bitscore":157.0,
                        "code":"PF13177",
                        "end":179,
                        "start":20
                    }
                ],
                "end":6038,
                "id":"gnl_Bakta_FEECGD_06255",
                "start":4793,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":30.9,
                        "code":"PF00300",
                        "end":163,
                        "start":80
                    }
                ],
                "end":7242,
                "id":"gnl_Bakta_FEECGD_06270",
                "start":6546,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.9,
                        "code":"PF13454",
                        "end":107,
                        "start":1
                    }
                ],
                "end":7810,
                "id":"gnl_Bakta_FEECGD_06275",
                "start":7471,
                "strand":1
            },
            {
                "domains":[],
                "end":8267,
                "id":"gnl_Bakta_FEECGD_06280",
                "start":7781,
                "strand":1
            },
            {
                "domains":[],
                "end":8957,
                "id":"gnl_Bakta_FEECGD_06285",
                "start":8348,
                "strand":1
            },
            {
                "domains":[],
                "end":9430,
                "id":"gnl_Bakta_FEECGD_06290",
                "start":9244,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.1,
                        "code":"PF00462",
                        "end":68,
                        "start":4
                    },
                    {
                        "bitscore":25.8,
                        "code":"PF02943",
                        "end":159,
                        "start":85
                    }
                ],
                "end":10753,
                "id":"gnl_Bakta_FEECGD_06295",
                "start":10249,
                "strand":1
            },
            {
                "domains":[],
                "end":11082,
                "id":"gnl_Bakta_FEECGD_06300",
                "start":10881,
                "strand":-1
            },
            {
                "domains":[],
                "end":12106,
                "id":"gnl_Bakta_FEECGD_06305",
                "start":11470,
                "strand":1
            },
            {
                "domains":[],
                "end":12776,
                "id":"gnl_Bakta_FEECGD_06315",
                "start":12422,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.8,
                        "code":"PF00195",
                        "end":78,
                        "start":1
                    }
                ],
                "end":13221,
                "id":"gnl_Bakta_FEECGD_06320",
                "start":12801,
                "strand":1
            },
            {
                "domains":[],
                "end":13704,
                "id":"gnl_Bakta_FEECGD_06330",
                "start":13470,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":56.4,
                        "code":"PF04140",
                        "end":59,
                        "start":1
                    }
                ],
                "end":14003,
                "id":"gnl_Bakta_FEECGD_06335",
                "start":13796,
                "strand":1
            },
            {
                "domains":[],
                "end":14547,
                "id":"gnl_Bakta_FEECGD_06340",
                "start":14322,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":99.4,
                        "code":"PF02322",
                        "end":160,
                        "start":1
                    }
                ],
                "end":15302,
                "id":"gnl_Bakta_FEECGD_06345",
                "start":14786,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":91.5,
                        "code":"PF02322",
                        "end":105,
                        "start":39
                    }
                ],
                "end":15920,
                "id":"gnl_Bakta_FEECGD_06350",
                "start":15395,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":108.6,
                        "code":"PF01654",
                        "end":159,
                        "start":2
                    }
                ],
                "end":16435,
                "id":"gnl_Bakta_FEECGD_06355",
                "start":15955,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":214.6,
                        "code":"PF01654",
                        "end":235,
                        "start":3
                    }
                ],
                "end":17123,
                "id":"CONCOCT.4_sub.region001.contig_1854_ORF30",
                "start":16415,
                "strand":-1
            },
            {
                "domains":[],
                "end":18012,
                "id":"gnl_Bakta_FEECGD_06370",
                "start":17700,
                "strand":1
            },
            {
                "domains":[],
                "end":19432,
                "id":"gnl_Bakta_FEECGD_06375",
                "start":18856,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":81.2,
                        "code":"PF17147",
                        "end":99,
                        "start":1
                    }
                ],
                "end":19873,
                "id":"gnl_Bakta_FEECGD_06380",
                "start":19465,
                "strand":-1
            },
            {
                "domains":[],
                "end":20106,
                "id":"gnl_Bakta_FEECGD_06385",
                "start":19869,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":168.9,
                        "code":"PF01855",
                        "end":173,
                        "start":14
                    }
                ],
                "end":20672,
                "id":"CONCOCT.4_sub.region001.contig_1854_ORF36",
                "start":20138,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":31.3,
                        "code":"PF00037",
                        "end":264,
                        "start":241
                    },
                    {
                        "bitscore":61.5,
                        "code":"PF01558",
                        "end":151,
                        "start":1
                    }
                ],
                "end":21514,
                "id":"gnl_Bakta_FEECGD_06395",
                "start":20668,
                "strand":-1
            },
            {
                "domains":[],
                "end":22313,
                "id":"gnl_Bakta_FEECGD_06400",
                "start":22043,
                "strand":1
            },
            {
                "domains":[],
                "end":22735,
                "id":"gnl_Bakta_FEECGD_06405",
                "start":22588,
                "strand":-1
            },
            {
                "domains":[],
                "end":23676,
                "id":"gnl_Bakta_FEECGD_06415",
                "start":23145,
                "strand":1
            },
            {
                "domains":[],
                "end":24054,
                "id":"gnl_Bakta_FEECGD_06420",
                "start":23724,
                "strand":1
            },
            {
                "domains":[],
                "end":24331,
                "id":"gnl_Bakta_FEECGD_06425",
                "start":24079,
                "strand":1
            },
            {
                "domains":[],
                "end":24751,
                "id":"gnl_Bakta_FEECGD_06430",
                "start":24625,
                "strand":1
            },
            {
                "domains":[],
                "end":25068,
                "id":"gnl_Bakta_FEECGD_06435",
                "start":24774,
                "strand":-1
            },
            {
                "domains":[],
                "end":25733,
                "id":"gnl_Bakta_FEECGD_06440",
                "start":25226,
                "strand":1
            },
            {
                "domains":[],
                "end":28464,
                "id":"gnl_Bakta_FEECGD_06450",
                "start":28158,
                "strand":-1
            },
            {
                "domains":[],
                "end":28908,
                "id":"gnl_Bakta_FEECGD_06455",
                "start":28818,
                "strand":-1
            },
            {
                "domains":[],
                "end":29057,
                "id":"gnl_Bakta_FEECGD_06460",
                "start":28907,
                "strand":-1
            },
            {
                "domains":[],
                "end":29241,
                "id":"gnl_Bakta_FEECGD_06465",
                "start":29091,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_3482, whole genome shotgun sequence",
        "end":41098,
        "id":"bins.24.region001.contig_3482",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":156.1,
                        "code":"PF13478",
                        "end":355,
                        "start":213
                    },
                    {
                        "bitscore":38.7,
                        "code":"PF02625",
                        "end":190,
                        "start":128
                    },
                    {
                        "bitscore":85.4,
                        "code":"PF02625",
                        "end":90,
                        "start":23
                    }
                ],
                "end":1578,
                "id":"gnl_Bakta_CBPBPM_08475",
                "start":435,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":77.0,
                        "code":"PF06240",
                        "end":147,
                        "start":5
                    }
                ],
                "end":2360,
                "id":"gnl_Bakta_CBPBPM_08480",
                "start":1712,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":140.2,
                        "code":"PF00941",
                        "end":156,
                        "start":1
                    },
                    {
                        "bitscore":85.0,
                        "code":"PF03450",
                        "end":262,
                        "start":161
                    }
                ],
                "end":3304,
                "id":"gnl_Bakta_CBPBPM_08485",
                "start":2494,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":23.9,
                        "code":"PF00111",
                        "end":78,
                        "start":5
                    },
                    {
                        "bitscore":109.2,
                        "code":"PF01799",
                        "end":146,
                        "start":73
                    }
                ],
                "end":3786,
                "id":"gnl_Bakta_CBPBPM_08490",
                "start":3306,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":125.0,
                        "code":"PF01315",
                        "end":140,
                        "start":31
                    },
                    {
                        "bitscore":251.0,
                        "code":"PF02738",
                        "end":409,
                        "start":159
                    },
                    {
                        "bitscore":301.5,
                        "code":"PF20256",
                        "end":723,
                        "start":436
                    }
                ],
                "end":6179,
                "id":"gnl_Bakta_CBPBPM_08495",
                "start":3782,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.3,
                        "code":"PF02625",
                        "end":80,
                        "start":13
                    },
                    {
                        "bitscore":77.3,
                        "code":"PF13478",
                        "end":227,
                        "start":116
                    }
                ],
                "end":7084,
                "id":"gnl_Bakta_CBPBPM_08500",
                "start":6175,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.9,
                        "code":"PF07728",
                        "end":193,
                        "start":41
                    }
                ],
                "end":7965,
                "id":"gnl_Bakta_CBPBPM_08505",
                "start":7080,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":185.7,
                        "code":"PF05762",
                        "end":380,
                        "start":162
                    }
                ],
                "end":9169,
                "id":"gnl_Bakta_CBPBPM_08510",
                "start":7957,
                "strand":1
            },
            {
                "domains":[],
                "end":9383,
                "id":"gnl_Bakta_CBPBPM_08515",
                "start":9245,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":38.9,
                        "code":"PF06902",
                        "end":162,
                        "start":101
                    },
                    {
                        "bitscore":55.8,
                        "code":"PF09360",
                        "end":79,
                        "start":20
                    }
                ],
                "end":10293,
                "id":"gnl_Bakta_CBPBPM_08520",
                "start":9696,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":133.7,
                        "code":"PF01066",
                        "end":185,
                        "start":18
                    }
                ],
                "end":11002,
                "id":"gnl_Bakta_CBPBPM_08525",
                "start":10390,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":106.8,
                        "code":"PF05949",
                        "end":272,
                        "start":125
                    }
                ],
                "end":11832,
                "id":"gnl_Bakta_CBPBPM_08530",
                "start":10998,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":112.3,
                        "code":"PF06947",
                        "end":108,
                        "start":21
                    }
                ],
                "end":12161,
                "id":"gnl_Bakta_CBPBPM_08535",
                "start":11828,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":113.4,
                        "code":"PF05949",
                        "end":236,
                        "start":110
                    }
                ],
                "end":12878,
                "id":"gnl_Bakta_CBPBPM_08540",
                "start":12167,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":134.7,
                        "code":"PF01597",
                        "end":127,
                        "start":6
                    }
                ],
                "end":13358,
                "id":"gnl_Bakta_CBPBPM_08545",
                "start":12974,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.5,
                        "code":"PF00498",
                        "end":101,
                        "start":40
                    }
                ],
                "end":13971,
                "id":"gnl_Bakta_CBPBPM_08550",
                "start":13626,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.4,
                        "code":"PF13411",
                        "end":91,
                        "start":18
                    }
                ],
                "end":14726,
                "id":"gnl_Bakta_CBPBPM_08555",
                "start":13967,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":141.5,
                        "code":"PF02577",
                        "end":130,
                        "start":20
                    }
                ],
                "end":15357,
                "id":"gnl_Bakta_CBPBPM_08560",
                "start":14790,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":52.4,
                        "code":"PF13411",
                        "end":121,
                        "start":49
                    }
                ],
                "end":16216,
                "id":"gnl_Bakta_CBPBPM_08565",
                "start":15556,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":582.0,
                        "code":"PF02347",
                        "end":456,
                        "start":32
                    }
                ],
                "end":18502,
                "id":"gnl_Bakta_CBPBPM_08570",
                "start":16438,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":191.5,
                        "code":"PF21478",
                        "end":233,
                        "start":112
                    }
                ],
                "end":19364,
                "id":"gnl_Bakta_CBPBPM_08575",
                "start":18491,
                "strand":1
            },
            {
                "domains":[],
                "end":19975,
                "id":"rlmH",
                "start":19375,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":57.7,
                        "code":"PF08392",
                        "end":231,
                        "start":70
                    },
                    {
                        "bitscore":62.1,
                        "code":"PF02797",
                        "end":365,
                        "start":224
                    }
                ],
                "end":21098,
                "id":"gnl_Bakta_CBPBPM_08585",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":86.9,
                        "code":"PF04140",
                        "end":170,
                        "start":78
                    }
                ],
                "end":21642,
                "id":"gnl_Bakta_CBPBPM_08590",
                "start":21102,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.9,
                        "code":"PF01494",
                        "end":208,
                        "start":1
                    }
                ],
                "end":22673,
                "id":"gnl_Bakta_CBPBPM_08595",
                "start":21638,
                "strand":1
            },
            {
                "domains":[],
                "end":23178,
                "id":"gnl_Bakta_CBPBPM_08600",
                "start":22692,
                "strand":-1
            },
            {
                "domains":[],
                "end":23829,
                "id":"gnl_Bakta_CBPBPM_08605",
                "start":23550,
                "strand":-1
            },
            {
                "domains":[],
                "end":24003,
                "id":"gnl_Bakta_CBPBPM_08610",
                "start":23856,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":481.9,
                        "code":"PF01268",
                        "end":395,
                        "start":24
                    }
                ],
                "end":25271,
                "id":"gnl_Bakta_CBPBPM_08615",
                "start":24083,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.8,
                        "code":"PF01546",
                        "end":210,
                        "start":72
                    }
                ],
                "end":26024,
                "id":"gnl_Bakta_CBPBPM_08620",
                "start":25379,
                "strand":1
            },
            {
                "domains":[],
                "end":26551,
                "id":"gnl_Bakta_CBPBPM_08625",
                "start":26023,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.0,
                        "code":"PF03009",
                        "end":197,
                        "start":1
                    }
                ],
                "end":27493,
                "id":"gnl_Bakta_CBPBPM_08635",
                "start":26854,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":107.1,
                        "code":"PF11700",
                        "end":153,
                        "start":12
                    },
                    {
                        "bitscore":134.8,
                        "code":"PF11700",
                        "end":378,
                        "start":151
                    }
                ],
                "end":28622,
                "id":"gnl_Bakta_CBPBPM_08640",
                "start":27485,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":139.7,
                        "code":"PF13397",
                        "end":107,
                        "start":4
                    }
                ],
                "end":29393,
                "id":"rbpA",
                "start":29039,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.3,
                        "code":"PF04186",
                        "end":90,
                        "start":39
                    }
                ],
                "end":29842,
                "id":"gnl_Bakta_CBPBPM_08655",
                "start":29401,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":120.5,
                        "code":"PF00535",
                        "end":173,
                        "start":7
                    }
                ],
                "end":30612,
                "id":"gnl_Bakta_CBPBPM_08660",
                "start":29871,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":28.5,
                        "code":"PF00795",
                        "end":421,
                        "start":206
                    },
                    {
                        "bitscore":96.5,
                        "code":"PF20154",
                        "end":163,
                        "start":9
                    }
                ],
                "end":32107,
                "id":"gnl_Bakta_CBPBPM_08670",
                "start":30781,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":23.6,
                        "code":"PF03061",
                        "end":103,
                        "start":28
                    }
                ],
                "end":32720,
                "id":"gnl_Bakta_CBPBPM_08675",
                "start":32306,
                "strand":-1
            },
            {
                "domains":[],
                "end":33118,
                "id":"gnl_Bakta_CBPBPM_08680",
                "start":32716,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":260.5,
                        "code":"PF09043",
                        "end":157,
                        "start":1
                    }
                ],
                "end":34515,
                "id":"gnl_Bakta_CBPBPM_08685",
                "start":33735,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":105.5,
                        "code":"PF09043",
                        "end":141,
                        "start":1
                    }
                ],
                "end":35129,
                "id":"gnl_Bakta_CBPBPM_08690",
                "start":34694,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.8,
                        "code":"PF07969",
                        "end":109,
                        "start":1
                    }
                ],
                "end":35543,
                "id":"gnl_Bakta_CBPBPM_08695",
                "start":35171,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":193.7,
                        "code":"PF07969",
                        "end":411,
                        "start":47
                    }
                ],
                "end":36792,
                "id":"gnl_Bakta_CBPBPM_08700",
                "start":35550,
                "strand":-1
            },
            {
                "domains":[],
                "end":37862,
                "id":"gnl_Bakta_CBPBPM_08705",
                "start":36788,
                "strand":-1
            },
            {
                "domains":[],
                "end":39488,
                "id":"gnl_Bakta_CBPBPM_08710",
                "start":38030,
                "strand":1
            },
            {
                "domains":[],
                "end":40358,
                "id":"gnl_Bakta_CBPBPM_08715",
                "start":39902,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":32.2,
                        "code":"PF00211",
                        "end":176,
                        "start":18
                    }
                ],
                "end":40905,
                "id":"gnl_Bakta_CBPBPM_08720",
                "start":40371,
                "strand":1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
