var bs_data=[
    {
        "desc":"contig_10184, whole genome shotgun sequence",
        "end":42958,
        "id":"contig_10184.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":1212,
                "id":"pilZ",
                "start":867,
                "strand":1
            },
            {
                "domains":[],
                "end":1363,
                "id":"gnl_Bakta_EMEBFO_00255",
                "start":1225,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":81.9,
                        "code":"PF03992",
                        "end":78,
                        "start":1
                    }
                ],
                "end":2048,
                "id":"gnl_Bakta_EMEBFO_00260",
                "start":1757,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":77.1,
                        "code":"PF03480",
                        "end":123,
                        "start":17
                    }
                ],
                "end":3021,
                "id":"gnl_Bakta_EMEBFO_00265",
                "start":2649,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":123.0,
                        "code":"PF03480",
                        "end":121,
                        "start":1
                    }
                ],
                "end":3590,
                "id":"gnl_Bakta_EMEBFO_00270",
                "start":3176,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.8,
                        "code":"PF04290",
                        "end":154,
                        "start":24
                    }
                ],
                "end":4229,
                "id":"gnl_Bakta_EMEBFO_00275",
                "start":3698,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":381.2,
                        "code":"PF06808",
                        "end":400,
                        "start":1
                    }
                ],
                "end":5510,
                "id":"gnl_Bakta_EMEBFO_00280",
                "start":4277,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":285.9,
                        "code":"PF04166",
                        "end":327,
                        "start":35
                    }
                ],
                "end":6530,
                "id":"pdxA",
                "start":5516,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":132.7,
                        "code":"PF03446",
                        "end":164,
                        "start":4
                    },
                    {
                        "bitscore":61.5,
                        "code":"PF14833",
                        "end":288,
                        "start":167
                    }
                ],
                "end":7423,
                "id":"gnl_Bakta_EMEBFO_00290",
                "start":6526,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.9,
                        "code":"PF01177",
                        "end":210,
                        "start":9
                    }
                ],
                "end":8093,
                "id":"gnl_Bakta_EMEBFO_00295",
                "start":7433,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":57.9,
                        "code":"PF00392",
                        "end":73,
                        "start":11
                    },
                    {
                        "bitscore":78.6,
                        "code":"PF07729",
                        "end":207,
                        "start":83
                    }
                ],
                "end":8844,
                "id":"gnl_Bakta_EMEBFO_00300",
                "start":8205,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":196.0,
                        "code":"PF00370",
                        "end":249,
                        "start":7
                    },
                    {
                        "bitscore":114.1,
                        "code":"PF02782",
                        "end":454,
                        "start":246
                    }
                ],
                "end":10467,
                "id":"gnl_Bakta_EMEBFO_00305",
                "start":8901,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":146.4,
                        "code":"PF00596",
                        "end":187,
                        "start":8
                    }
                ],
                "end":11054,
                "id":"gnl_Bakta_EMEBFO_00310",
                "start":10463,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":128.0,
                        "code":"PF00005",
                        "end":185,
                        "start":37
                    }
                ],
                "end":11895,
                "id":"glnQ",
                "start":11112,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":74.8,
                        "code":"PF00528",
                        "end":362,
                        "start":173
                    }
                ],
                "end":13029,
                "id":"gnl_Bakta_EMEBFO_00320",
                "start":11916,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":50.0,
                        "code":"PF00528",
                        "end":389,
                        "start":211
                    }
                ],
                "end":14215,
                "id":"gnl_Bakta_EMEBFO_00325",
                "start":13036,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":79.4,
                        "code":"PF00497",
                        "end":200,
                        "start":10
                    }
                ],
                "end":15243,
                "id":"gnl_Bakta_EMEBFO_00330",
                "start":14397,
                "strand":-1
            },
            {
                "domains":[],
                "end":16112,
                "id":"gnl_Bakta_EMEBFO_00340",
                "start":15581,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":51.1,
                        "code":"PF01648",
                        "end":185,
                        "start":90
                    }
                ],
                "end":16775,
                "id":"gnl_Bakta_EMEBFO_00345",
                "start":16166,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":45.1,
                        "code":"PF07992",
                        "end":347,
                        "start":139
                    }
                ],
                "end":18669,
                "id":"gnl_Bakta_EMEBFO_00350",
                "start":16833,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.3,
                        "code":"PF01717",
                        "end":372,
                        "start":166
                    }
                ],
                "end":19996,
                "id":"gnl_Bakta_EMEBFO_00355",
                "start":18859,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.7,
                        "code":"PF00550",
                        "end":979,
                        "start":911
                    },
                    {
                        "bitscore":45.1,
                        "code":"PF00550",
                        "end":891,
                        "start":828
                    },
                    {
                        "bitscore":52.4,
                        "code":"PF16197",
                        "end":798,
                        "start":731
                    },
                    {
                        "bitscore":143.0,
                        "code":"PF02801",
                        "end":729,
                        "start":612
                    },
                    {
                        "bitscore":212.7,
                        "code":"PF00109",
                        "end":607,
                        "start":381
                    },
                    {
                        "bitscore":21.0,
                        "code":"PF00550",
                        "end":365,
                        "start":306
                    },
                    {
                        "bitscore":40.0,
                        "code":"PF00698",
                        "end":298,
                        "start":7
                    }
                ],
                "end":22958,
                "id":"gnl_Bakta_EMEBFO_00360",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":196.6,
                        "code":"PF02685",
                        "end":194,
                        "start":1
                    }
                ],
                "end":23762,
                "id":"gnl_Bakta_EMEBFO_00365",
                "start":23168,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":90.5,
                        "code":"PF02685",
                        "end":117,
                        "start":3
                    }
                ],
                "end":24159,
                "id":"gnl_Bakta_EMEBFO_00370",
                "start":23799,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":155.4,
                        "code":"PF13714",
                        "end":234,
                        "start":1
                    }
                ],
                "end":25061,
                "id":"gnl_Bakta_EMEBFO_00375",
                "start":24257,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":265.8,
                        "code":"PF06808",
                        "end":305,
                        "start":1
                    }
                ],
                "end":26066,
                "id":"gnl_Bakta_EMEBFO_00380",
                "start":25124,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":111.3,
                        "code":"PF04290",
                        "end":156,
                        "start":23
                    }
                ],
                "end":26904,
                "id":"gnl_Bakta_EMEBFO_00385",
                "start":26406,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":204.2,
                        "code":"PF03480",
                        "end":314,
                        "start":30
                    }
                ],
                "end":27966,
                "id":"gnl_Bakta_EMEBFO_00390",
                "start":26976,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":79.3,
                        "code":"PF12694",
                        "end":150,
                        "start":5
                    }
                ],
                "end":28562,
                "id":"gnl_Bakta_EMEBFO_00395",
                "start":28100,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":97.8,
                        "code":"PF01558",
                        "end":176,
                        "start":14
                    }
                ],
                "end":29161,
                "id":"korC",
                "start":28609,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":82.4,
                        "code":"PF02775",
                        "end":106,
                        "start":1
                    }
                ],
                "end":29726,
                "id":"gnl_Bakta_EMEBFO_00405",
                "start":29195,
                "strand":-1
            },
            {
                "domains":[],
                "end":29997,
                "id":"gnl_Bakta_EMEBFO_00410",
                "start":29718,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.2,
                        "code":"PF17147",
                        "end":326,
                        "start":276
                    },
                    {
                        "bitscore":221.8,
                        "code":"PF01855",
                        "end":246,
                        "start":16
                    }
                ],
                "end":31150,
                "id":"gnl_Bakta_EMEBFO_00415",
                "start":29986,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.1,
                        "code":"PF12838",
                        "end":62,
                        "start":16
                    }
                ],
                "end":31379,
                "id":"gnl_Bakta_EMEBFO_00420",
                "start":31151,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":155.9,
                        "code":"PF13714",
                        "end":258,
                        "start":15
                    }
                ],
                "end":32545,
                "id":"gnl_Bakta_EMEBFO_00425",
                "start":31633,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":134.3,
                        "code":"PF19305",
                        "end":483,
                        "start":296
                    },
                    {
                        "bitscore":213.8,
                        "code":"PF03972",
                        "end":265,
                        "start":19
                    }
                ],
                "end":34077,
                "id":"gnl_Bakta_EMEBFO_00430",
                "start":32544,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":498.6,
                        "code":"PF01970",
                        "end":440,
                        "start":20
                    }
                ],
                "end":35719,
                "id":"gnl_Bakta_EMEBFO_00435",
                "start":34213,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":88.0,
                        "code":"PF03401",
                        "end":319,
                        "start":40
                    }
                ],
                "end":37136,
                "id":"gnl_Bakta_EMEBFO_00445",
                "start":36170,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":50.0,
                        "code":"PF07238",
                        "end":138,
                        "start":30
                    }
                ],
                "end":38016,
                "id":"pilZ",
                "start":37584,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.4,
                        "code":"PF01592",
                        "end":133,
                        "start":26
                    }
                ],
                "end":38581,
                "id":"nifU",
                "start":38179,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":76.7,
                        "code":"PF01592",
                        "end":147,
                        "start":26
                    }
                ],
                "end":39113,
                "id":"gnl_Bakta_EMEBFO_00460",
                "start":38657,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":80.4,
                        "code":"PF02579",
                        "end":104,
                        "start":12
                    }
                ],
                "end":39530,
                "id":"gnl_Bakta_EMEBFO_00465",
                "start":39170,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":66.4,
                        "code":"PF02579",
                        "end":109,
                        "start":16
                    }
                ],
                "end":39935,
                "id":"gnl_Bakta_EMEBFO_00470",
                "start":39551,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":39.3,
                        "code":"PF01656",
                        "end":262,
                        "start":4
                    }
                ],
                "end":40860,
                "id":"cobB",
                "start":39954,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.4,
                        "code":"PF01656",
                        "end":255,
                        "start":3
                    }
                ],
                "end":41735,
                "id":"rsxB",
                "start":40856,
                "strand":-1
            },
            {
                "domains":[],
                "end":42167,
                "id":"gnl_Bakta_EMEBFO_00485",
                "start":41795,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.6,
                        "code":"PF02579",
                        "end":97,
                        "start":8
                    }
                ],
                "end":42532,
                "id":"gnl_Bakta_EMEBFO_00490",
                "start":42190,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_12276, whole genome shotgun sequence",
        "end":29540,
        "id":"contig_12276.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":92.0,
                        "code":"PF00756",
                        "end":171,
                        "start":39
                    }
                ],
                "end":1063,
                "id":"contig_12276.region001_ORF1",
                "start":538,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.7,
                        "code":"PF00756",
                        "end":115,
                        "start":3
                    }
                ],
                "end":1422,
                "id":"gnl_Bakta_MMFHPB_03100",
                "start":1059,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":25.1,
                        "code":"PF05305",
                        "end":134,
                        "start":49
                    }
                ],
                "end":2035,
                "id":"gnl_Bakta_MMFHPB_03105",
                "start":1630,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.1,
                        "code":"PF01083",
                        "end":286,
                        "start":76
                    }
                ],
                "end":3064,
                "id":"gnl_Bakta_MMFHPB_03110",
                "start":2038,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":124.9,
                        "code":"PF00501",
                        "end":271,
                        "start":2
                    }
                ],
                "end":5211,
                "id":"gnl_Bakta_MMFHPB_03115",
                "start":3801,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":40.9,
                        "code":"PF00550",
                        "end":102,
                        "start":36
                    },
                    {
                        "bitscore":288.9,
                        "code":"PF00109",
                        "end":374,
                        "start":124
                    },
                    {
                        "bitscore":143.9,
                        "code":"PF02801",
                        "end":500,
                        "start":382
                    },
                    {
                        "bitscore":43.1,
                        "code":"PF16197",
                        "end":583,
                        "start":502
                    },
                    {
                        "bitscore":180.2,
                        "code":"PF00698",
                        "end":1067,
                        "start":735
                    },
                    {
                        "bitscore":29.7,
                        "code":"PF00550",
                        "end":1340,
                        "start":1282
                    }
                ],
                "end":9540,
                "id":"gnl_Bakta_MMFHPB_03120",
                "start":5226,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":68.5,
                        "code":"PF00975",
                        "end":285,
                        "start":88
                    }
                ],
                "end":10747,
                "id":"gnl_Bakta_MMFHPB_03125",
                "start":9664,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":487.0,
                        "code":"PF01039",
                        "end":514,
                        "start":31
                    }
                ],
                "end":12294,
                "id":"gnl_Bakta_MMFHPB_03130",
                "start":10743,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":165.7,
                        "code":"PF00975",
                        "end":236,
                        "start":11
                    }
                ],
                "end":13013,
                "id":"tesA",
                "start":12293,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":203.7,
                        "code":"PF00501",
                        "end":419,
                        "start":12
                    }
                ],
                "end":15267,
                "id":"gnl_Bakta_MMFHPB_03140",
                "start":13524,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.4,
                        "code":"PF00550",
                        "end":79,
                        "start":13
                    },
                    {
                        "bitscore":308.4,
                        "code":"PF00109",
                        "end":348,
                        "start":98
                    },
                    {
                        "bitscore":150.6,
                        "code":"PF02801",
                        "end":474,
                        "start":356
                    },
                    {
                        "bitscore":65.1,
                        "code":"PF16197",
                        "end":581,
                        "start":476
                    }
                ],
                "end":17222,
                "id":"ppsA",
                "start":15263,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":289.1,
                        "code":"PF00698",
                        "end":304,
                        "start":1
                    },
                    {
                        "bitscore":159.4,
                        "code":"PF08659",
                        "end":715,
                        "start":538
                    }
                ],
                "end":19557,
                "id":"ppsB",
                "start":17199,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":54.2,
                        "code":"PF00550",
                        "end":108,
                        "start":41
                    }
                ],
                "end":19981,
                "id":"gnl_Bakta_MMFHPB_03155",
                "start":19525,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":240.6,
                        "code":"PF00109",
                        "end":273,
                        "start":16
                    },
                    {
                        "bitscore":140.2,
                        "code":"PF02801",
                        "end":401,
                        "start":281
                    }
                ],
                "end":21207,
                "id":"gnl_Bakta_MMFHPB_03160",
                "start":19977,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.6,
                        "code":"PF16197",
                        "end":97,
                        "start":3
                    },
                    {
                        "bitscore":178.8,
                        "code":"PF00698",
                        "end":452,
                        "start":133
                    },
                    {
                        "bitscore":45.8,
                        "code":"PF00550",
                        "end":585,
                        "start":522
                    },
                    {
                        "bitscore":100.2,
                        "code":"PF00668",
                        "end":1053,
                        "start":613
                    }
                ],
                "end":24437,
                "id":"gnl_Bakta_MMFHPB_03165",
                "start":21230,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":113.9,
                        "code":"PF00005",
                        "end":171,
                        "start":27
                    }
                ],
                "end":25381,
                "id":"gnl_Bakta_MMFHPB_03170",
                "start":24448,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":39.6,
                        "code":"PF12698",
                        "end":245,
                        "start":21
                    },
                    {
                        "bitscore":60.8,
                        "code":"PF01061",
                        "end":484,
                        "start":273
                    }
                ],
                "end":27078,
                "id":"gnl_Bakta_MMFHPB_03175",
                "start":25509,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":194.1,
                        "code":"PF16911",
                        "end":386,
                        "start":199
                    }
                ],
                "end":28331,
                "id":"gnl_Bakta_MMFHPB_03180",
                "start":27137,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_1353, whole genome shotgun sequence",
        "end":19196,
        "id":"contig_1353.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":119.9,
                        "code":"PF00920",
                        "end":137,
                        "start":1
                    }
                ],
                "end":447,
                "id":"gnl_Bakta_GLNBBO_03325",
                "start":24,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":262.8,
                        "code":"PF01081",
                        "end":206,
                        "start":11
                    }
                ],
                "end":1545,
                "id":"gnl_Bakta_GLNBBO_03330",
                "start":894,
                "strand":1
            },
            {
                "domains":[],
                "end":1930,
                "id":"gnl_Bakta_GLNBBO_03335",
                "start":1588,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":103.6,
                        "code":"PF00343",
                        "end":73,
                        "start":1
                    }
                ],
                "end":2222,
                "id":"gnl_Bakta_GLNBBO_03340",
                "start":2000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":417.5,
                        "code":"PF00343",
                        "end":261,
                        "start":1
                    }
                ],
                "end":3016,
                "id":"gnl_Bakta_GLNBBO_03345",
                "start":2218,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":186.4,
                        "code":"PF11737",
                        "end":127,
                        "start":1
                    }
                ],
                "end":3443,
                "id":"gnl_Bakta_GLNBBO_03350",
                "start":3044,
                "strand":1
            },
            {
                "domains":[],
                "end":4857,
                "id":"gnl_Bakta_GLNBBO_03365",
                "start":4272,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":110.7,
                        "code":"PF13304",
                        "end":338,
                        "start":25
                    }
                ],
                "end":5975,
                "id":"gnl_Bakta_GLNBBO_03370",
                "start":4799,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.0,
                        "code":"PF14103",
                        "end":178,
                        "start":8
                    }
                ],
                "end":6553,
                "id":"gnl_Bakta_GLNBBO_03375",
                "start":5971,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.3,
                        "code":"PF21088",
                        "end":661,
                        "start":620
                    },
                    {
                        "bitscore":79.2,
                        "code":"PF00924",
                        "end":729,
                        "start":662
                    },
                    {
                        "bitscore":56.0,
                        "code":"PF21082",
                        "end":818,
                        "start":737
                    }
                ],
                "end":9311,
                "id":"gnl_Bakta_GLNBBO_03380",
                "start":6752,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.3,
                        "code":"PF01648",
                        "end":217,
                        "start":114
                    }
                ],
                "end":10173,
                "id":"gnl_Bakta_GLNBBO_03385",
                "start":9447,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":40.3,
                        "code":"PF14765",
                        "end":2640,
                        "start":2486
                    },
                    {
                        "bitscore":103.6,
                        "code":"PF08659",
                        "end":2254,
                        "start":2031
                    },
                    {
                        "bitscore":30.7,
                        "code":"PF00550",
                        "end":1764,
                        "start":1697
                    },
                    {
                        "bitscore":184.3,
                        "code":"PF00698",
                        "end":1575,
                        "start":1257
                    },
                    {
                        "bitscore":79.5,
                        "code":"PF02801",
                        "end":1106,
                        "start":994
                    },
                    {
                        "bitscore":150.8,
                        "code":"PF00109",
                        "end":986,
                        "start":697
                    },
                    {
                        "bitscore":78.0,
                        "code":"PF03060",
                        "end":659,
                        "start":338
                    }
                ],
                "end":18111,
                "id":"gnl_Bakta_GLNBBO_03390",
                "start":10188,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":77.9,
                        "code":"PF04028",
                        "end":134,
                        "start":66
                    }
                ],
                "end":18867,
                "id":"gnl_Bakta_GLNBBO_03395",
                "start":18183,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_3019, whole genome shotgun sequence",
        "end":30763,
        "id":"contig_3019.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2346,
                "id":"gnl_Bakta_BELDHM_24345",
                "start":1335,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":98.6,
                        "code":"PF00698",
                        "end":151,
                        "start":1
                    }
                ],
                "end":4533,
                "id":"gnl_Bakta_BELDHM_24350",
                "start":3840,
                "strand":-1
            },
            {
                "domains":[],
                "end":7066,
                "id":"gnl_Bakta_BELDHM_24360",
                "start":6244,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":72.5,
                        "code":"PF00698",
                        "end":599,
                        "start":475
                    },
                    {
                        "bitscore":47.5,
                        "code":"PF16197",
                        "end":418,
                        "start":297
                    },
                    {
                        "bitscore":101.9,
                        "code":"PF02801",
                        "end":293,
                        "start":175
                    },
                    {
                        "bitscore":224.2,
                        "code":"PF00109",
                        "end":167,
                        "start":1
                    }
                ],
                "end":10763,
                "id":"gnl_Bakta_BELDHM_24365",
                "start":8945,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.9,
                        "code":"PF00109",
                        "end":84,
                        "start":48
                    }
                ],
                "end":11159,
                "id":"gnl_Bakta_BELDHM_24370",
                "start":10904,
                "strand":-1
            },
            {
                "domains":[],
                "end":12243,
                "id":"gnl_Bakta_BELDHM_24375",
                "start":11331,
                "strand":1
            },
            {
                "domains":[],
                "end":12712,
                "id":"contig_3019.region001_ORF8",
                "start":12346,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":146.7,
                        "code":"PF03176",
                        "end":152,
                        "start":1
                    }
                ],
                "end":13669,
                "id":"gnl_Bakta_BELDHM_24385",
                "start":13198,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.5,
                        "code":"PF03176",
                        "end":75,
                        "start":11
                    }
                ],
                "end":14422,
                "id":"gnl_Bakta_BELDHM_24390",
                "start":13711,
                "strand":1
            },
            {
                "domains":[],
                "end":15825,
                "id":"gnl_Bakta_BELDHM_24395",
                "start":15018,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":191.7,
                        "code":"PF08237",
                        "end":185,
                        "start":2
                    }
                ],
                "end":16981,
                "id":"gnl_Bakta_BELDHM_24400",
                "start":16249,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":173.5,
                        "code":"PF11139",
                        "end":212,
                        "start":5
                    }
                ],
                "end":17638,
                "id":"gnl_Bakta_BELDHM_24405",
                "start":16993,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":117.7,
                        "code":"PF01613",
                        "end":160,
                        "start":15
                    }
                ],
                "end":18191,
                "id":"gnl_Bakta_BELDHM_24410",
                "start":17708,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":32.4,
                        "code":"PF13183",
                        "end":216,
                        "start":140
                    },
                    {
                        "bitscore":90.5,
                        "code":"PF13085",
                        "end":109,
                        "start":6
                    }
                ],
                "end":18956,
                "id":"gnl_Bakta_BELDHM_24415",
                "start":18203,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":92.4,
                        "code":"PF02910",
                        "end":616,
                        "start":493
                    },
                    {
                        "bitscore":290.6,
                        "code":"PF00890",
                        "end":434,
                        "start":10
                    }
                ],
                "end":20888,
                "id":"gnl_Bakta_BELDHM_24420",
                "start":18956,
                "strand":-1
            },
            {
                "domains":[],
                "end":21440,
                "id":"contig_3019.region001_ORF17",
                "start":20921,
                "strand":-1
            },
            {
                "domains":[],
                "end":22115,
                "id":"gnl_Bakta_BELDHM_24430",
                "start":21818,
                "strand":-1
            },
            {
                "domains":[],
                "end":22700,
                "id":"gnl_Bakta_BELDHM_24435",
                "start":22604,
                "strand":1
            },
            {
                "domains":[],
                "end":23014,
                "id":"gnl_Bakta_BELDHM_24440",
                "start":22885,
                "strand":1
            },
            {
                "domains":[],
                "end":24427,
                "id":"esxD",
                "start":24274,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.0,
                        "code":"PF06013",
                        "end":88,
                        "start":4
                    }
                ],
                "end":24744,
                "id":"gnl_Bakta_BELDHM_24450",
                "start":24456,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":92.0,
                        "code":"PF14011",
                        "end":259,
                        "start":5
                    }
                ],
                "end":25659,
                "id":"gnl_Bakta_BELDHM_24455",
                "start":24825,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.0,
                        "code":"PF01656",
                        "end":294,
                        "start":80
                    }
                ],
                "end":26649,
                "id":"gnl_Bakta_BELDHM_24460",
                "start":25662,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.7,
                        "code":"PF08817",
                        "end":89,
                        "start":9
                    }
                ],
                "end":27554,
                "id":"gnl_Bakta_BELDHM_24465",
                "start":26648,
                "strand":1
            },
            {
                "domains":[],
                "end":29040,
                "id":"gnl_Bakta_BELDHM_24470",
                "start":27594,
                "strand":1
            },
            {
                "domains":[],
                "end":29821,
                "id":"gnl_Bakta_BELDHM_24475",
                "start":29395,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":49.2,
                        "code":"PF03471",
                        "end":169,
                        "start":91
                    }
                ],
                "end":30603,
                "id":"gnl_Bakta_BELDHM_24480",
                "start":30039,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_4667, whole genome shotgun sequence",
        "end":44359,
        "id":"contig_4667.region002",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":1283,
                "id":"gnl_Bakta_GOCHMJ_15365",
                "start":542,
                "strand":-1
            },
            {
                "domains":[],
                "end":2243,
                "id":"gnl_Bakta_GOCHMJ_15370",
                "start":1427,
                "strand":1
            },
            {
                "domains":[],
                "end":3229,
                "id":"gnl_Bakta_GOCHMJ_15375",
                "start":2239,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":124.2,
                        "code":"PF13365",
                        "end":224,
                        "start":86
                    }
                ],
                "end":4328,
                "id":"gnl_Bakta_GOCHMJ_15380",
                "start":3341,
                "strand":1
            },
            {
                "domains":[],
                "end":4598,
                "id":"gnl_Bakta_GOCHMJ_15385",
                "start":4490,
                "strand":1
            },
            {
                "domains":[],
                "end":5296,
                "id":"gnl_Bakta_GOCHMJ_15390",
                "start":5044,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.5,
                        "code":"PF03965",
                        "end":66,
                        "start":5
                    }
                ],
                "end":6871,
                "id":"gnl_Bakta_GOCHMJ_15395",
                "start":6649,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":49.6,
                        "code":"PF00989",
                        "end":161,
                        "start":54
                    },
                    {
                        "bitscore":147.8,
                        "code":"PF00990",
                        "end":332,
                        "start":175
                    }
                ],
                "end":9415,
                "id":"gnl_Bakta_GOCHMJ_15400",
                "start":8017,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":85.4,
                        "code":"PF13328",
                        "end":155,
                        "start":13
                    }
                ],
                "end":10517,
                "id":"gnl_Bakta_GOCHMJ_15405",
                "start":9542,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":123.6,
                        "code":"PF11138",
                        "end":106,
                        "start":1
                    }
                ],
                "end":10866,
                "id":"gnl_Bakta_GOCHMJ_15410",
                "start":10533,
                "strand":-1
            },
            {
                "domains":[],
                "end":11616,
                "id":"gnl_Bakta_GOCHMJ_15420",
                "start":11031,
                "strand":-1
            },
            {
                "domains":[],
                "end":12377,
                "id":"gnl_Bakta_GOCHMJ_15430",
                "start":11960,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":167.2,
                        "code":"PF00291",
                        "end":199,
                        "start":6
                    }
                ],
                "end":13472,
                "id":"gnl_Bakta_GOCHMJ_15435",
                "start":12779,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":32.8,
                        "code":"PF13432",
                        "end":205,
                        "start":144
                    }
                ],
                "end":14842,
                "id":"gnl_Bakta_GOCHMJ_15440",
                "start":13498,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.8,
                        "code":"PF07228",
                        "end":748,
                        "start":643
                    },
                    {
                        "bitscore":35.8,
                        "code":"PF17820",
                        "end":103,
                        "start":49
                    }
                ],
                "end":17362,
                "id":"gnl_Bakta_GOCHMJ_15445",
                "start":14980,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":67.4,
                        "code":"PF02771",
                        "end":120,
                        "start":7
                    },
                    {
                        "bitscore":76.1,
                        "code":"PF02770",
                        "end":219,
                        "start":124
                    },
                    {
                        "bitscore":118.8,
                        "code":"PF00441",
                        "end":382,
                        "start":232
                    }
                ],
                "end":19268,
                "id":"gnl_Bakta_GOCHMJ_15450",
                "start":17612,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":96.4,
                        "code":"PF00109",
                        "end":162,
                        "start":7
                    }
                ],
                "end":19772,
                "id":"gnl_Bakta_GOCHMJ_15455",
                "start":19283,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":39.4,
                        "code":"PF00109",
                        "end":56,
                        "start":1
                    },
                    {
                        "bitscore":101.5,
                        "code":"PF02801",
                        "end":182,
                        "start":64
                    },
                    {
                        "bitscore":35.8,
                        "code":"PF16197",
                        "end":256,
                        "start":184
                    },
                    {
                        "bitscore":159.1,
                        "code":"PF00698",
                        "end":674,
                        "start":360
                    },
                    {
                        "bitscore":38.8,
                        "code":"PF00109",
                        "end":1120,
                        "start":988
                    },
                    {
                        "bitscore":22.3,
                        "code":"PF02801",
                        "end":1249,
                        "start":1133
                    }
                ],
                "end":24359,
                "id":"gnl_Bakta_GOCHMJ_15460",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":68.1,
                        "code":"PF08659",
                        "end":667,
                        "start":492
                    },
                    {
                        "bitscore":42.4,
                        "code":"PF21089",
                        "end":841,
                        "start":745
                    },
                    {
                        "bitscore":47.5,
                        "code":"PF14765",
                        "end":1021,
                        "start":869
                    }
                ],
                "end":27409,
                "id":"gnl_Bakta_GOCHMJ_15465",
                "start":24304,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.1,
                        "code":"PF01648",
                        "end":170,
                        "start":97
                    }
                ],
                "end":28150,
                "id":"gnl_Bakta_GOCHMJ_15470",
                "start":27481,
                "strand":1
            },
            {
                "domains":[],
                "end":28904,
                "id":"gnl_Bakta_GOCHMJ_15475",
                "start":28490,
                "strand":-1
            },
            {
                "domains":[],
                "end":29185,
                "id":"gnl_Bakta_GOCHMJ_15480",
                "start":28948,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":57.3,
                        "code":"PF03544",
                        "end":811,
                        "start":732
                    },
                    {
                        "bitscore":147.2,
                        "code":"PF00069",
                        "end":458,
                        "start":187
                    }
                ],
                "end":31677,
                "id":"gnl_Bakta_GOCHMJ_15485",
                "start":29238,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":126.2,
                        "code":"PF04055",
                        "end":183,
                        "start":17
                    },
                    {
                        "bitscore":128.0,
                        "code":"PF06463",
                        "end":315,
                        "start":188
                    }
                ],
                "end":33601,
                "id":"gnl_Bakta_GOCHMJ_15490",
                "start":32596,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":39.1,
                        "code":"PF07238",
                        "end":124,
                        "start":20
                    }
                ],
                "end":34454,
                "id":"pilZ",
                "start":33761,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":75.0,
                        "code":"PF13688",
                        "end":407,
                        "start":195
                    }
                ],
                "end":35889,
                "id":"gnl_Bakta_GOCHMJ_15500",
                "start":34464,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":87.1,
                        "code":"PF13641",
                        "end":317,
                        "start":98
                    }
                ],
                "end":37753,
                "id":"gnl_Bakta_GOCHMJ_15505",
                "start":36175,
                "strand":1
            },
            {
                "domains":[],
                "end":39260,
                "id":"gnl_Bakta_GOCHMJ_15510",
                "start":37757,
                "strand":1
            },
            {
                "domains":[],
                "end":39847,
                "id":"gnl_Bakta_GOCHMJ_15515",
                "start":39394,
                "strand":1
            },
            {
                "domains":[],
                "end":40566,
                "id":"gnl_Bakta_GOCHMJ_15520",
                "start":40164,
                "strand":1
            },
            {
                "domains":[],
                "end":41584,
                "id":"gnl_Bakta_GOCHMJ_15525",
                "start":40774,
                "strand":1
            },
            {
                "domains":[],
                "end":42357,
                "id":"gnl_Bakta_GOCHMJ_15530",
                "start":41772,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.2,
                        "code":"PF13180",
                        "end":108,
                        "start":15
                    }
                ],
                "end":42802,
                "id":"gnl_Bakta_GOCHMJ_15535",
                "start":42466,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":342.7,
                        "code":"PF01244",
                        "end":375,
                        "start":15
                    }
                ],
                "end":44104,
                "id":"gnl_Bakta_GOCHMJ_15540",
                "start":42952,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_8973, whole genome shotgun sequence",
        "end":14937,
        "id":"contig_8973.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":526,
                "id":"gnl_Bakta_GFOFGJ_66750",
                "start":4,
                "strand":1
            },
            {
                "domains":[],
                "end":1446,
                "id":"gnl_Bakta_GFOFGJ_66760",
                "start":1197,
                "strand":1
            },
            {
                "domains":[],
                "end":1730,
                "id":"gnl_Bakta_GFOFGJ_66765",
                "start":1562,
                "strand":-1
            },
            {
                "domains":[],
                "end":2603,
                "id":"gnl_Bakta_GFOFGJ_66770",
                "start":2102,
                "strand":1
            },
            {
                "domains":[],
                "end":3105,
                "id":"gnl_Bakta_GFOFGJ_66775",
                "start":2901,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":53.2,
                        "code":"PF13276",
                        "end":141,
                        "start":84
                    }
                ],
                "end":4062,
                "id":"gnl_Bakta_GFOFGJ_66780",
                "start":3330,
                "strand":-1
            },
            {
                "domains":[],
                "end":5039,
                "id":"gnl_Bakta_GFOFGJ_66785",
                "start":4202,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":107.6,
                        "code":"PF17131",
                        "end":241,
                        "start":66
                    }
                ],
                "end":6094,
                "id":"gnl_Bakta_GFOFGJ_66790",
                "start":5368,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":75.1,
                        "code":"PF00975",
                        "end":625,
                        "start":356
                    },
                    {
                        "bitscore":43.9,
                        "code":"PF00550",
                        "end":317,
                        "start":251
                    },
                    {
                        "bitscore":176.9,
                        "code":"PF08659",
                        "end":154,
                        "start":1
                    }
                ],
                "end":8004,
                "id":"gnl_Bakta_GFOFGJ_66795",
                "start":6102,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":84.6,
                        "code":"PF00107",
                        "end":311,
                        "start":178
                    },
                    {
                        "bitscore":24.9,
                        "code":"PF08240",
                        "end":123,
                        "start":55
                    }
                ],
                "end":9199,
                "id":"gnl_Bakta_GFOFGJ_66800",
                "start":7966,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":73.9,
                        "code":"PF08242",
                        "end":122,
                        "start":22
                    }
                ],
                "end":10424,
                "id":"gnl_Bakta_GFOFGJ_66805",
                "start":9170,
                "strand":-1
            },
            {
                "domains":[],
                "end":10943,
                "id":"gnl_Bakta_GFOFGJ_66810",
                "start":10715,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":80.1,
                        "code":"PF14765",
                        "end":821,
                        "start":682
                    },
                    {
                        "bitscore":67.4,
                        "code":"PF21089",
                        "end":660,
                        "start":564
                    },
                    {
                        "bitscore":258.0,
                        "code":"PF00698",
                        "end":522,
                        "start":204
                    },
                    {
                        "bitscore":56.1,
                        "code":"PF16197",
                        "end":167,
                        "start":46
                    },
                    {
                        "bitscore":43.0,
                        "code":"PF02801",
                        "end":43,
                        "start":1
                    }
                ],
                "end":13546,
                "id":"gnl_Bakta_GFOFGJ_66815",
                "start":11053,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":47.6,
                        "code":"PF02801",
                        "end":127,
                        "start":66
                    },
                    {
                        "bitscore":73.1,
                        "code":"PF00109",
                        "end":58,
                        "start":1
                    }
                ],
                "end":13964,
                "id":"gnl_Bakta_GFOFGJ_66820",
                "start":13547,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":67.0,
                        "code":"PF00109",
                        "end":82,
                        "start":1
                    }
                ],
                "end":14286,
                "id":"gnl_Bakta_GFOFGJ_66825",
                "start":13989,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
