var bs_data=[
    {
        "desc":"Streptomyces rimosus strain R6-500MV9 contig001, whole genome shotgun sequence",
        "end":96569,
        "id":"JMGX01000001.1.cluster009",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":46.9,
                        "code":"PF00440",
                        "end":72,
                        "start":27
                    }
                ],
                "end":1364,
                "id":"KEF09332.1",
                "start":755,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":272.5,
                        "code":"PF00668",
                        "end":1324,
                        "start":873
                    },
                    {
                        "bitscore":51.5,
                        "code":"PF00550",
                        "end":851,
                        "start":786
                    },
                    {
                        "bitscore":109.3,
                        "code":"PF02801",
                        "end":382,
                        "start":255
                    },
                    {
                        "bitscore":196.8,
                        "code":"PF00109",
                        "end":247,
                        "start":8
                    }
                ],
                "end":24671,
                "id":"KEF09333.1",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":31.7,
                        "code":"PF00550",
                        "end":615,
                        "start":551
                    },
                    {
                        "bitscore":47.8,
                        "code":"PF13193",
                        "end":519,
                        "start":443
                    },
                    {
                        "bitscore":199.0,
                        "code":"PF00501",
                        "end":384,
                        "start":18
                    }
                ],
                "end":26689,
                "id":"KEF09334.1",
                "start":24784,
                "strand":-1
            },
            {
                "domains":[],
                "end":27669,
                "id":"KEF09335.1",
                "start":26685,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":639.0,
                        "code":"PF01474",
                        "end":442,
                        "start":15
                    }
                ],
                "end":29247,
                "id":"KEF09336.1",
                "start":27903,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":261.0,
                        "code":"PF00425",
                        "end":522,
                        "start":253
                    }
                ],
                "end":31067,
                "id":"KEF09337.1",
                "start":29456,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":173.4,
                        "code":"PF00117",
                        "end":188,
                        "start":4
                    }
                ],
                "end":31636,
                "id":"KEF09338.1",
                "start":31063,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":81.9,
                        "code":"PF00155",
                        "end":457,
                        "start":107
                    },
                    {
                        "bitscore":64.3,
                        "code":"PF00392",
                        "end":80,
                        "start":17
                    }
                ],
                "end":33072,
                "id":"KEF09339.1",
                "start":31644,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":70.0,
                        "code":"PF02885",
                        "end":73,
                        "start":11
                    },
                    {
                        "bitscore":267.8,
                        "code":"PF00591",
                        "end":335,
                        "start":79
                    }
                ],
                "end":34355,
                "id":"KEF09340.1",
                "start":33296,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":242.3,
                        "code":"PF00218",
                        "end":253,
                        "start":2
                    }
                ],
                "end":35136,
                "id":"KEF09341.1",
                "start":34326,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":219.9,
                        "code":"PF00682",
                        "end":307,
                        "start":27
                    }
                ],
                "end":36829,
                "id":"KEF09342.1",
                "start":35224,
                "strand":-1
            },
            {
                "domains":[],
                "end":37772,
                "id":"KEF09343.1",
                "start":36944,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":122.5,
                        "code":"PF01613",
                        "end":168,
                        "start":20
                    }
                ],
                "end":38337,
                "id":"KEF09344.1",
                "start":37824,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":100.4,
                        "code":"PF00999",
                        "end":399,
                        "start":7
                    }
                ],
                "end":39602,
                "id":"KEF09345.1",
                "start":38342,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":445.7,
                        "code":"PF04820",
                        "end":488,
                        "start":4
                    }
                ],
                "end":41202,
                "id":"KEF09346.1",
                "start":39639,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":164.0,
                        "code":"PF00975",
                        "end":246,
                        "start":19
                    }
                ],
                "end":42262,
                "id":"KEF09347.1",
                "start":41509,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":204.5,
                        "code":"PF00668",
                        "end":1532,
                        "start":1098
                    },
                    {
                        "bitscore":49.7,
                        "code":"PF00550",
                        "end":1082,
                        "start":1019
                    },
                    {
                        "bitscore":58.6,
                        "code":"PF13193",
                        "end":993,
                        "start":918
                    },
                    {
                        "bitscore":259.7,
                        "code":"PF00501",
                        "end":859,
                        "start":513
                    },
                    {
                        "bitscore":336.3,
                        "code":"PF00668",
                        "end":493,
                        "start":46
                    }
                ],
                "end":46916,
                "id":"KEF09348.1",
                "start":42317,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":48.2,
                        "code":"PF00550",
                        "end":4145,
                        "start":4081
                    },
                    {
                        "bitscore":31.2,
                        "code":"PF13193",
                        "end":4053,
                        "start":3977
                    },
                    {
                        "bitscore":267.1,
                        "code":"PF00501",
                        "end":3920,
                        "start":3566
                    },
                    {
                        "bitscore":293.1,
                        "code":"PF00668",
                        "end":3546,
                        "start":3103
                    },
                    {
                        "bitscore":221.5,
                        "code":"PF00668",
                        "end":3074,
                        "start":2633
                    },
                    {
                        "bitscore":53.3,
                        "code":"PF00550",
                        "end":2617,
                        "start":2554
                    },
                    {
                        "bitscore":33.2,
                        "code":"PF13193",
                        "end":2526,
                        "start":2452
                    },
                    {
                        "bitscore":288.6,
                        "code":"PF00501",
                        "end":2392,
                        "start":2037
                    },
                    {
                        "bitscore":286.5,
                        "code":"PF00668",
                        "end":2018,
                        "start":1570
                    },
                    {
                        "bitscore":248.3,
                        "code":"PF00668",
                        "end":1544,
                        "start":1098
                    },
                    {
                        "bitscore":47.1,
                        "code":"PF00550",
                        "end":1084,
                        "start":1021
                    },
                    {
                        "bitscore":45.6,
                        "code":"PF13193",
                        "end":993,
                        "start":919
                    },
                    {
                        "bitscore":305.8,
                        "code":"PF00501",
                        "end":860,
                        "start":513
                    },
                    {
                        "bitscore":290.2,
                        "code":"PF00668",
                        "end":493,
                        "start":42
                    }
                ],
                "end":59463,
                "id":"KEF09349.1",
                "start":46953,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":58.1,
                        "code":"PF00550",
                        "end":2116,
                        "start":2052
                    },
                    {
                        "bitscore":35.2,
                        "code":"PF13193",
                        "end":2024,
                        "start":1949
                    },
                    {
                        "bitscore":266.5,
                        "code":"PF00501",
                        "end":1890,
                        "start":1545
                    },
                    {
                        "bitscore":326.4,
                        "code":"PF00668",
                        "end":1524,
                        "start":1072
                    },
                    {
                        "bitscore":62.3,
                        "code":"PF00550",
                        "end":1057,
                        "start":993
                    },
                    {
                        "bitscore":46.1,
                        "code":"PF13193",
                        "end":967,
                        "start":895
                    },
                    {
                        "bitscore":327.3,
                        "code":"PF00501",
                        "end":829,
                        "start":479
                    },
                    {
                        "bitscore":178.3,
                        "code":"PF00668",
                        "end":460,
                        "start":4
                    }
                ],
                "end":65889,
                "id":"KEF09350.1",
                "start":59466,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":140.1,
                        "code":"PF00144",
                        "end":288,
                        "start":9
                    }
                ],
                "end":67204,
                "id":"KEF09351.1",
                "start":66010,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":40.7,
                        "code":"PF02687",
                        "end":848,
                        "start":733
                    },
                    {
                        "bitscore":37.8,
                        "code":"PF12704",
                        "end":703,
                        "start":504
                    },
                    {
                        "bitscore":71.3,
                        "code":"PF02687",
                        "end":397,
                        "start":275
                    },
                    {
                        "bitscore":43.9,
                        "code":"PF12704",
                        "end":241,
                        "start":22
                    }
                ],
                "end":70486,
                "id":"KEF09352.1",
                "start":67915,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":114.1,
                        "code":"PF00005",
                        "end":181,
                        "start":34
                    }
                ],
                "end":71249,
                "id":"KEF09353.1",
                "start":70490,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":86.7,
                        "code":"PF13796",
                        "end":195,
                        "start":20
                    },
                    {
                        "bitscore":53.6,
                        "code":"PF07730",
                        "end":291,
                        "start":224
                    },
                    {
                        "bitscore":31.5,
                        "code":"PF02518",
                        "end":418,
                        "start":328
                    }
                ],
                "end":72846,
                "id":"KEF09354.1",
                "start":71589,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":52.1,
                        "code":"PF00072",
                        "end":121,
                        "start":3
                    },
                    {
                        "bitscore":54.4,
                        "code":"PF00196",
                        "end":200,
                        "start":149
                    }
                ],
                "end":73478,
                "id":"KEF09355.1",
                "start":72833,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":108.3,
                        "code":"PF05977",
                        "end":441,
                        "start":37
                    }
                ],
                "end":74864,
                "id":"KEF09356.1",
                "start":73529,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":121.1,
                        "code":"PF02668",
                        "end":296,
                        "start":2
                    }
                ],
                "end":75766,
                "id":"KEF09357.1",
                "start":74794,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":185.0,
                        "code":"PF00155",
                        "end":385,
                        "start":35
                    }
                ],
                "end":77031,
                "id":"KEF09358.1",
                "start":75819,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":78.7,
                        "code":"PF00694",
                        "end":118,
                        "start":1
                    }
                ],
                "end":77657,
                "id":"KEF09359.1",
                "start":77030,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":565.0,
                        "code":"PF00330",
                        "end":457,
                        "start":9
                    }
                ],
                "end":79072,
                "id":"KEF09360.1",
                "start":77671,
                "strand":-1
            },
            {
                "domains":[],
                "end":79799,
                "id":"KEF09361.1",
                "start":79364,
                "strand":1
            },
            {
                "domains":[],
                "end":81040,
                "id":"KEF09362.1",
                "start":80389,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":59.1,
                        "code":"PF00005",
                        "end":132,
                        "start":1
                    }
                ],
                "end":81733,
                "id":"KEF09363.1",
                "start":81121,
                "strand":-1
            },
            {
                "domains":[],
                "end":82935,
                "id":"KEF09364.1",
                "start":82032,
                "strand":-1
            },
            {
                "domains":[],
                "end":84402,
                "id":"KEF09365.1",
                "start":84207,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":32.7,
                        "code":"PF10935",
                        "end":315,
                        "start":181
                    }
                ],
                "end":85449,
                "id":"KEF09366.1",
                "start":84489,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.2,
                        "code":"PF02518",
                        "end":377,
                        "start":263
                    }
                ],
                "end":87407,
                "id":"KEF09367.1",
                "start":85922,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":69.7,
                        "code":"PF03259",
                        "end":101,
                        "start":9
                    }
                ],
                "end":87848,
                "id":"KEF09368.1",
                "start":87437,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":104.4,
                        "code":"PF05331",
                        "end":123,
                        "start":12
                    }
                ],
                "end":88216,
                "id":"KEF09369.1",
                "start":87844,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":103.2,
                        "code":"PF03029",
                        "end":198,
                        "start":30
                    }
                ],
                "end":88820,
                "id":"KEF09370.1",
                "start":88196,
                "strand":1
            },
            {
                "domains":[],
                "end":90283,
                "id":"KEF09371.1",
                "start":88816,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":166.0,
                        "code":"PF00155",
                        "end":393,
                        "start":37
                    }
                ],
                "end":91562,
                "id":"KEF09372.1",
                "start":90308,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.2,
                        "code":"PF11991",
                        "end":273,
                        "start":2
                    }
                ],
                "end":92533,
                "id":"KEF09373.1",
                "start":91558,
                "strand":-1
            },
            {
                "domains":[],
                "end":93328,
                "id":"KEF09374.1",
                "start":93100,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":46.2,
                        "code":"PF00067",
                        "end":318,
                        "start":219
                    }
                ],
                "end":96569,
                "id":"KEF09375.1",
                "start":95513,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces rimosus subsp. rimosus strain NRRL WC-3560 contig81.1, whole genome shotgun sequence",
        "end":6714,
        "id":"JOBV01000001.1.cluster044",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":63.5,
                        "code":"PF03477",
                        "end":169,
                        "start":81
                    }
                ],
                "end":1694,
                "id":"JOBV01000001.1.cluster044_ORF1",
                "start":1058,
                "strand":-1
            },
            {
                "domains":[],
                "end":2017,
                "id":"JOBV01000001.1.cluster044_ORF2",
                "start":1894,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":101.7,
                        "code":"PF01726",
                        "end":140,
                        "start":76
                    },
                    {
                        "bitscore":119.7,
                        "code":"PF00717",
                        "end":278,
                        "start":166
                    }
                ],
                "end":2920,
                "id":"JOBV01000001.1.cluster044_ORF3",
                "start":2065,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":121.6,
                        "code":"PF13307",
                        "end":631,
                        "start":470
                    },
                    {
                        "bitscore":24.9,
                        "code":"PF00270",
                        "end":97,
                        "start":24
                    }
                ],
                "end":4959,
                "id":"JOBV01000001.1.cluster044_ORF4",
                "start":2985,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":135.1,
                        "code":"PF06276",
                        "end":551,
                        "start":387
                    },
                    {
                        "bitscore":247.1,
                        "code":"PF04183",
                        "end":366,
                        "start":115
                    }
                ],
                "end":6713,
                "id":"JOBV01000001.1.cluster044_ORF5",
                "start":5000,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces rimosus subsp. rimosus strain NRRL WC-3924 contig24.1, whole genome shotgun sequence",
        "end":108830,
        "id":"JOBW01000001.1.cluster027",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":242.4,
                        "code":"PF00501",
                        "end":885,
                        "start":518
                    },
                    {
                        "bitscore":183.6,
                        "code":"PF00668",
                        "end":501,
                        "start":30
                    }
                ],
                "end":3171,
                "id":"JOBW01000001.1.cluster027_ORF1",
                "start":1,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":46.9,
                        "code":"PF07687",
                        "end":278,
                        "start":176
                    }
                ],
                "end":4512,
                "id":"JOBW01000001.1.cluster027_ORF2",
                "start":3321,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":74.0,
                        "code":"PF01497",
                        "end":308,
                        "start":73
                    }
                ],
                "end":5575,
                "id":"JOBW01000001.1.cluster027_ORF3",
                "start":4576,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":108.1,
                        "code":"PF00005",
                        "end":167,
                        "start":18
                    }
                ],
                "end":6539,
                "id":"JOBW01000001.1.cluster027_ORF4",
                "start":5744,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":39.9,
                        "code":"PF06722",
                        "end":404,
                        "start":262
                    }
                ],
                "end":7836,
                "id":"JOBW01000001.1.cluster027_ORF5",
                "start":6615,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":194.2,
                        "code":"PF10014",
                        "end":251,
                        "start":58
                    }
                ],
                "end":8896,
                "id":"JOBW01000001.1.cluster027_ORF6",
                "start":8128,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":46.4,
                        "code":"PF06325",
                        "end":88,
                        "start":3
                    }
                ],
                "end":9613,
                "id":"JOBW01000001.1.cluster027_ORF7",
                "start":9001,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":60.8,
                        "code":"PF09360",
                        "end":65,
                        "start":20
                    }
                ],
                "end":9872,
                "id":"JOBW01000001.1.cluster027_ORF8",
                "start":9626,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":185.2,
                        "code":"PF14518",
                        "end":304,
                        "start":127
                    }
                ],
                "end":10867,
                "id":"JOBW01000001.1.cluster027_ORF9",
                "start":9889,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":23.1,
                        "code":"PF06081",
                        "end":177,
                        "start":37
                    }
                ],
                "end":12204,
                "id":"JOBW01000001.1.cluster027_ORF10",
                "start":11001,
                "strand":-1
            },
            {
                "domains":[],
                "end":12721,
                "id":"JOBW01000001.1.cluster027_ORF11",
                "start":12478,
                "strand":1
            },
            {
                "domains":[],
                "end":13515,
                "id":"JOBW01000001.1.cluster027_ORF12",
                "start":12858,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.8,
                        "code":"PF00067",
                        "end":318,
                        "start":219
                    }
                ],
                "end":14644,
                "id":"JOBW01000001.1.cluster027_ORF13",
                "start":13588,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":104.0,
                        "code":"PF07690",
                        "end":212,
                        "start":24
                    },
                    {
                        "bitscore":54.3,
                        "code":"PF07690",
                        "end":426,
                        "start":208
                    }
                ],
                "end":16611,
                "id":"JOBW01000001.1.cluster027_ORF14",
                "start":15168,
                "strand":1
            },
            {
                "domains":[],
                "end":17056,
                "id":"JOBW01000001.1.cluster027_ORF15",
                "start":16819,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":59.3,
                        "code":"PF11991",
                        "end":301,
                        "start":5
                    }
                ],
                "end":18598,
                "id":"JOBW01000001.1.cluster027_ORF16",
                "start":17539,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":161.6,
                        "code":"PF00155",
                        "end":390,
                        "start":34
                    }
                ],
                "end":19848,
                "id":"JOBW01000001.1.cluster027_ORF17",
                "start":18603,
                "strand":1
            },
            {
                "domains":[],
                "end":21340,
                "id":"JOBW01000001.1.cluster027_ORF18",
                "start":19873,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":103.2,
                        "code":"PF03029",
                        "end":198,
                        "start":30
                    }
                ],
                "end":21960,
                "id":"JOBW01000001.1.cluster027_ORF19",
                "start":21336,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":104.4,
                        "code":"PF05331",
                        "end":123,
                        "start":12
                    }
                ],
                "end":22312,
                "id":"JOBW01000001.1.cluster027_ORF20",
                "start":21940,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":69.5,
                        "code":"PF03259",
                        "end":105,
                        "start":13
                    }
                ],
                "end":22731,
                "id":"JOBW01000001.1.cluster027_ORF21",
                "start":22308,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.2,
                        "code":"PF02518",
                        "end":377,
                        "start":263
                    }
                ],
                "end":24234,
                "id":"JOBW01000001.1.cluster027_ORF22",
                "start":22749,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":32.7,
                        "code":"PF10935",
                        "end":315,
                        "start":181
                    }
                ],
                "end":25664,
                "id":"JOBW01000001.1.cluster027_ORF23",
                "start":24704,
                "strand":-1
            },
            {
                "domains":[],
                "end":25946,
                "id":"JOBW01000001.1.cluster027_ORF24",
                "start":25751,
                "strand":-1
            },
            {
                "domains":[],
                "end":28120,
                "id":"JOBW01000001.1.cluster027_ORF25",
                "start":27223,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":60.7,
                        "code":"PF00005",
                        "end":168,
                        "start":37
                    }
                ],
                "end":29031,
                "id":"JOBW01000001.1.cluster027_ORF26",
                "start":28311,
                "strand":1
            },
            {
                "domains":[],
                "end":29762,
                "id":"JOBW01000001.1.cluster027_ORF27",
                "start":29111,
                "strand":-1
            },
            {
                "domains":[],
                "end":30199,
                "id":"JOBW01000001.1.cluster027_ORF28",
                "start":30088,
                "strand":-1
            },
            {
                "domains":[],
                "end":30786,
                "id":"JOBW01000001.1.cluster027_ORF29",
                "start":30351,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":560.6,
                        "code":"PF00330",
                        "end":457,
                        "start":9
                    }
                ],
                "end":32479,
                "id":"JOBW01000001.1.cluster027_ORF30",
                "start":31078,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":77.5,
                        "code":"PF00694",
                        "end":118,
                        "start":1
                    }
                ],
                "end":33120,
                "id":"JOBW01000001.1.cluster027_ORF31",
                "start":32493,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":185.7,
                        "code":"PF00155",
                        "end":386,
                        "start":36
                    }
                ],
                "end":34331,
                "id":"JOBW01000001.1.cluster027_ORF32",
                "start":33116,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":122.8,
                        "code":"PF02668",
                        "end":315,
                        "start":11
                    }
                ],
                "end":35356,
                "id":"JOBW01000001.1.cluster027_ORF33",
                "start":34327,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":110.9,
                        "code":"PF05977",
                        "end":419,
                        "start":15
                    }
                ],
                "end":36621,
                "id":"JOBW01000001.1.cluster027_ORF34",
                "start":35352,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":54.4,
                        "code":"PF00196",
                        "end":200,
                        "start":149
                    },
                    {
                        "bitscore":50.3,
                        "code":"PF00072",
                        "end":121,
                        "start":3
                    }
                ],
                "end":37317,
                "id":"JOBW01000001.1.cluster027_ORF35",
                "start":36672,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":31.4,
                        "code":"PF02518",
                        "end":441,
                        "start":351
                    },
                    {
                        "bitscore":53.5,
                        "code":"PF07730",
                        "end":314,
                        "start":247
                    },
                    {
                        "bitscore":87.0,
                        "code":"PF13796",
                        "end":218,
                        "start":43
                    }
                ],
                "end":38630,
                "id":"JOBW01000001.1.cluster027_ORF36",
                "start":37304,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":113.5,
                        "code":"PF00005",
                        "end":228,
                        "start":81
                    }
                ],
                "end":39660,
                "id":"JOBW01000001.1.cluster027_ORF37",
                "start":38760,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.5,
                        "code":"PF12704",
                        "end":241,
                        "start":22
                    },
                    {
                        "bitscore":70.4,
                        "code":"PF02687",
                        "end":397,
                        "start":275
                    },
                    {
                        "bitscore":38.2,
                        "code":"PF12704",
                        "end":703,
                        "start":504
                    },
                    {
                        "bitscore":40.7,
                        "code":"PF02687",
                        "end":848,
                        "start":733
                    }
                ],
                "end":42235,
                "id":"JOBW01000001.1.cluster027_ORF38",
                "start":39664,
                "strand":1
            },
            {
                "domains":[],
                "end":42452,
                "id":"JOBW01000001.1.cluster027_ORF39",
                "start":42335,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":143.4,
                        "code":"PF00144",
                        "end":288,
                        "start":9
                    }
                ],
                "end":44018,
                "id":"JOBW01000001.1.cluster027_ORF40",
                "start":42824,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":174.4,
                        "code":"PF00668",
                        "end":460,
                        "start":4
                    },
                    {
                        "bitscore":319.5,
                        "code":"PF00501",
                        "end":829,
                        "start":479
                    },
                    {
                        "bitscore":46.2,
                        "code":"PF13193",
                        "end":967,
                        "start":895
                    },
                    {
                        "bitscore":63.3,
                        "code":"PF00550",
                        "end":1057,
                        "start":993
                    },
                    {
                        "bitscore":327.5,
                        "code":"PF00668",
                        "end":1524,
                        "start":1072
                    },
                    {
                        "bitscore":262.8,
                        "code":"PF00501",
                        "end":1890,
                        "start":1545
                    },
                    {
                        "bitscore":37.5,
                        "code":"PF13193",
                        "end":2024,
                        "start":1949
                    },
                    {
                        "bitscore":58.1,
                        "code":"PF00550",
                        "end":2116,
                        "start":2052
                    }
                ],
                "end":50562,
                "id":"JOBW01000001.1.cluster027_ORF41",
                "start":44139,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":290.0,
                        "code":"PF00668",
                        "end":493,
                        "start":42
                    },
                    {
                        "bitscore":306.3,
                        "code":"PF00501",
                        "end":860,
                        "start":513
                    },
                    {
                        "bitscore":47.7,
                        "code":"PF13193",
                        "end":993,
                        "start":919
                    },
                    {
                        "bitscore":47.8,
                        "code":"PF00550",
                        "end":1084,
                        "start":1021
                    },
                    {
                        "bitscore":241.1,
                        "code":"PF00668",
                        "end":1542,
                        "start":1098
                    },
                    {
                        "bitscore":285.7,
                        "code":"PF00668",
                        "end":2018,
                        "start":1570
                    },
                    {
                        "bitscore":291.4,
                        "code":"PF00501",
                        "end":2392,
                        "start":2037
                    },
                    {
                        "bitscore":33.0,
                        "code":"PF13193",
                        "end":2526,
                        "start":2452
                    },
                    {
                        "bitscore":53.3,
                        "code":"PF00550",
                        "end":2617,
                        "start":2554
                    },
                    {
                        "bitscore":219.9,
                        "code":"PF00668",
                        "end":3074,
                        "start":2633
                    },
                    {
                        "bitscore":292.5,
                        "code":"PF00668",
                        "end":3546,
                        "start":3102
                    },
                    {
                        "bitscore":269.1,
                        "code":"PF00501",
                        "end":3920,
                        "start":3566
                    },
                    {
                        "bitscore":29.6,
                        "code":"PF13193",
                        "end":4053,
                        "start":3977
                    },
                    {
                        "bitscore":48.2,
                        "code":"PF00550",
                        "end":4145,
                        "start":4081
                    }
                ],
                "end":63075,
                "id":"JOBW01000001.1.cluster027_ORF42",
                "start":50565,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":337.9,
                        "code":"PF00668",
                        "end":493,
                        "start":46
                    },
                    {
                        "bitscore":260.1,
                        "code":"PF00501",
                        "end":859,
                        "start":513
                    },
                    {
                        "bitscore":58.6,
                        "code":"PF13193",
                        "end":993,
                        "start":918
                    },
                    {
                        "bitscore":49.7,
                        "code":"PF00550",
                        "end":1082,
                        "start":1019
                    },
                    {
                        "bitscore":210.0,
                        "code":"PF00668",
                        "end":1532,
                        "start":1098
                    }
                ],
                "end":67711,
                "id":"JOBW01000001.1.cluster027_ORF43",
                "start":63112,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":164.0,
                        "code":"PF00975",
                        "end":246,
                        "start":19
                    }
                ],
                "end":68519,
                "id":"JOBW01000001.1.cluster027_ORF44",
                "start":67766,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":445.9,
                        "code":"PF04820",
                        "end":488,
                        "start":4
                    }
                ],
                "end":70389,
                "id":"JOBW01000001.1.cluster027_ORF45",
                "start":68826,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":104.7,
                        "code":"PF00999",
                        "end":399,
                        "start":7
                    }
                ],
                "end":71686,
                "id":"JOBW01000001.1.cluster027_ORF46",
                "start":70426,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":122.4,
                        "code":"PF01613",
                        "end":171,
                        "start":23
                    }
                ],
                "end":72204,
                "id":"JOBW01000001.1.cluster027_ORF47",
                "start":71682,
                "strand":1
            },
            {
                "domains":[],
                "end":73086,
                "id":"JOBW01000001.1.cluster027_ORF48",
                "start":72258,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":221.7,
                        "code":"PF00682",
                        "end":331,
                        "start":51
                    }
                ],
                "end":74800,
                "id":"JOBW01000001.1.cluster027_ORF49",
                "start":73132,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":97.6,
                        "code":"PF00218",
                        "end":102,
                        "start":1
                    }
                ],
                "end":75699,
                "id":"JOBW01000001.1.cluster027_ORF50",
                "start":75342,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":267.5,
                        "code":"PF00591",
                        "end":335,
                        "start":79
                    },
                    {
                        "bitscore":70.6,
                        "code":"PF02885",
                        "end":73,
                        "start":11
                    }
                ],
                "end":76729,
                "id":"JOBW01000001.1.cluster027_ORF51",
                "start":75670,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":64.3,
                        "code":"PF00392",
                        "end":80,
                        "start":17
                    },
                    {
                        "bitscore":86.7,
                        "code":"PF00155",
                        "end":457,
                        "start":107
                    }
                ],
                "end":78381,
                "id":"JOBW01000001.1.cluster027_ORF52",
                "start":76953,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":173.4,
                        "code":"PF00117",
                        "end":188,
                        "start":4
                    }
                ],
                "end":78962,
                "id":"JOBW01000001.1.cluster027_ORF53",
                "start":78389,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":258.1,
                        "code":"PF00425",
                        "end":522,
                        "start":253
                    }
                ],
                "end":80569,
                "id":"JOBW01000001.1.cluster027_ORF54",
                "start":78958,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":639.7,
                        "code":"PF01474",
                        "end":442,
                        "start":14
                    }
                ],
                "end":82122,
                "id":"JOBW01000001.1.cluster027_ORF55",
                "start":80778,
                "strand":1
            },
            {
                "domains":[],
                "end":83340,
                "id":"JOBW01000001.1.cluster027_ORF56",
                "start":82326,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":195.8,
                        "code":"PF00501",
                        "end":384,
                        "start":18
                    },
                    {
                        "bitscore":47.2,
                        "code":"PF13193",
                        "end":519,
                        "start":443
                    },
                    {
                        "bitscore":31.7,
                        "code":"PF00550",
                        "end":615,
                        "start":551
                    }
                ],
                "end":85241,
                "id":"JOBW01000001.1.cluster027_ORF57",
                "start":83336,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":194.2,
                        "code":"PF00109",
                        "end":247,
                        "start":8
                    },
                    {
                        "bitscore":109.1,
                        "code":"PF02801",
                        "end":382,
                        "start":255
                    },
                    {
                        "bitscore":33.3,
                        "code":"PF16197",
                        "end":518,
                        "start":387
                    },
                    {
                        "bitscore":51.5,
                        "code":"PF00550",
                        "end":846,
                        "start":781
                    },
                    {
                        "bitscore":272.5,
                        "code":"PF00668",
                        "end":1320,
                        "start":867
                    }
                ],
                "end":90010,
                "id":"JOBW01000001.1.cluster027_ORF58",
                "start":85354,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.1,
                        "code":"PF00668",
                        "end":320,
                        "start":7
                    },
                    {
                        "bitscore":278.4,
                        "code":"PF00501",
                        "end":778,
                        "start":440
                    },
                    {
                        "bitscore":41.6,
                        "code":"PF13193",
                        "end":911,
                        "start":836
                    },
                    {
                        "bitscore":48.6,
                        "code":"PF00550",
                        "end":1004,
                        "start":941
                    },
                    {
                        "bitscore":256.9,
                        "code":"PF00668",
                        "end":1489,
                        "start":1051
                    },
                    {
                        "bitscore":256.6,
                        "code":"PF00501",
                        "end":1864,
                        "start":1508
                    },
                    {
                        "bitscore":48.4,
                        "code":"PF08242",
                        "end":2139,
                        "start":2039
                    },
                    {
                        "bitscore":52.1,
                        "code":"PF00550",
                        "end":2501,
                        "start":2437
                    },
                    {
                        "bitscore":89.8,
                        "code":"PF00975",
                        "end":2635,
                        "start":2527
                    }
                ],
                "end":98403,
                "id":"JOBW01000001.1.cluster027_ORF59",
                "start":90006,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":190.4,
                        "code":"PF00668",
                        "end":413,
                        "start":16
                    },
                    {
                        "bitscore":295.2,
                        "code":"PF00501",
                        "end":842,
                        "start":475
                    },
                    {
                        "bitscore":37.1,
                        "code":"PF13193",
                        "end":974,
                        "start":900
                    },
                    {
                        "bitscore":44.8,
                        "code":"PF00550",
                        "end":1083,
                        "start":1005
                    },
                    {
                        "bitscore":247.0,
                        "code":"PF00668",
                        "end":1551,
                        "start":1108
                    },
                    {
                        "bitscore":46.4,
                        "code":"PF00550",
                        "end":1671,
                        "start":1608
                    },
                    {
                        "bitscore":96.2,
                        "code":"PF00668",
                        "end":2160,
                        "start":1700
                    },
                    {
                        "bitscore":167.0,
                        "code":"PF00668",
                        "end":2624,
                        "start":2232
                    },
                    {
                        "bitscore":203.4,
                        "code":"PF00501",
                        "end":3148,
                        "start":2848
                    },
                    {
                        "bitscore":45.1,
                        "code":"PF00550",
                        "end":3452,
                        "start":3387
                    }
                ],
                "end":108830,
                "id":"JOBW01000001.1.cluster027_ORF60",
                "start":98399,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces rimosus subsp. rimosus strain NRRL B-2660 contig92.1, whole genome shotgun sequence",
        "end":8973,
        "id":"JOES01000001.1.cluster049",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2407,
                "id":"JOES01000001.1.cluster049_ORF1",
                "start":1270,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":292.3,
                        "code":"PF00202",
                        "end":469,
                        "start":56
                    }
                ],
                "end":4534,
                "id":"JOES01000001.1.cluster049_ORF2",
                "start":2980,
                "strand":1
            },
            {
                "domains":[],
                "end":5004,
                "id":"JOES01000001.1.cluster049_ORF3",
                "start":4533,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":231.0,
                        "code":"PF04183",
                        "end":491,
                        "start":257
                    },
                    {
                        "bitscore":114.3,
                        "code":"PF06276",
                        "end":689,
                        "start":525
                    }
                ],
                "end":7121,
                "id":"JOES01000001.1.cluster049_ORF4",
                "start":5000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":157.2,
                        "code":"PF13523",
                        "end":231,
                        "start":85
                    }
                ],
                "end":7959,
                "id":"JOES01000001.1.cluster049_ORF5",
                "start":7209,
                "strand":1
            },
            {
                "domains":[],
                "end":8866,
                "id":"JOES01000001.1.cluster049_ORF6",
                "start":8305,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces sp. NRRL F-5555 contig17.1, whole genome shotgun sequence",
        "end":11953,
        "id":"JOHJ01000001.1.cluster020",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":63.4,
                        "code":"PF03477",
                        "end":134,
                        "start":46
                    }
                ],
                "end":589,
                "id":"JOHJ01000001.1.cluster020_ORF1",
                "start":40,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":101.9,
                        "code":"PF01726",
                        "end":114,
                        "start":50
                    },
                    {
                        "bitscore":120.8,
                        "code":"PF00717",
                        "end":253,
                        "start":141
                    }
                ],
                "end":1898,
                "id":"JOHJ01000001.1.cluster020_ORF2",
                "start":1118,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":125.2,
                        "code":"PF13307",
                        "end":632,
                        "start":470
                    },
                    {
                        "bitscore":26.9,
                        "code":"PF00270",
                        "end":94,
                        "start":25
                    }
                ],
                "end":4094,
                "id":"JOHJ01000001.1.cluster020_ORF3",
                "start":2063,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":162.4,
                        "code":"PF13523",
                        "end":212,
                        "start":66
                    }
                ],
                "end":5004,
                "id":"JOHJ01000001.1.cluster020_ORF4",
                "start":4311,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":126.0,
                        "code":"PF06276",
                        "end":625,
                        "start":461
                    },
                    {
                        "bitscore":232.7,
                        "code":"PF04183",
                        "end":424,
                        "start":193
                    }
                ],
                "end":6953,
                "id":"JOHJ01000001.1.cluster020_ORF5",
                "start":5000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":161.2,
                        "code":"PF00202",
                        "end":461,
                        "start":207
                    },
                    {
                        "bitscore":53.2,
                        "code":"PF00202",
                        "end":198,
                        "start":74
                    }
                ],
                "end":8457,
                "id":"JOHJ01000001.1.cluster020_ORF6",
                "start":7008,
                "strand":-1
            },
            {
                "domains":[],
                "end":10046,
                "id":"JOHJ01000001.1.cluster020_ORF7",
                "start":8813,
                "strand":1
            },
            {
                "domains":[],
                "end":11383,
                "id":"JOHJ01000001.1.cluster020_ORF8",
                "start":10168,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces sp. NRRL S-325 contig12.1, whole genome shotgun sequence",
        "end":13073,
        "id":"JOIW01000001.1.cluster027",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":31.5,
                        "code":"PF01590",
                        "end":143,
                        "start":6
                    },
                    {
                        "bitscore":46.5,
                        "code":"PF00196",
                        "end":274,
                        "start":218
                    }
                ],
                "end":858,
                "id":"JOIW01000001.1.cluster027_ORF1",
                "start":12,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":258.3,
                        "code":"PF06224",
                        "end":353,
                        "start":36
                    }
                ],
                "end":2022,
                "id":"JOIW01000001.1.cluster027_ORF2",
                "start":903,
                "strand":-1
            },
            {
                "domains":[],
                "end":2994,
                "id":"JOIW01000001.1.cluster027_ORF3",
                "start":2127,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.9,
                        "code":"PF13410",
                        "end":267,
                        "start":191
                    }
                ],
                "end":4024,
                "id":"JOIW01000001.1.cluster027_ORF4",
                "start":2998,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":198.5,
                        "code":"PF07690",
                        "end":433,
                        "start":29
                    }
                ],
                "end":5517,
                "id":"JOIW01000001.1.cluster027_ORF5",
                "start":4020,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":59.8,
                        "code":"PF18029",
                        "end":124,
                        "start":8
                    }
                ],
                "end":6051,
                "id":"JOIW01000001.1.cluster027_ORF6",
                "start":5646,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.0,
                        "code":"PF03372",
                        "end":788,
                        "start":497
                    }
                ],
                "end":8786,
                "id":"JOIW01000001.1.cluster027_ORF7",
                "start":6371,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":75.7,
                        "code":"PF00561",
                        "end":266,
                        "start":34
                    }
                ],
                "end":9982,
                "id":"JOIW01000001.1.cluster027_ORF8",
                "start":8926,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":118.3,
                        "code":"PF02801",
                        "end":382,
                        "start":270
                    },
                    {
                        "bitscore":152.0,
                        "code":"PF00109",
                        "end":262,
                        "start":20
                    }
                ],
                "end":11275,
                "id":"JOIW01000001.1.cluster027_ORF9",
                "start":10000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.6,
                        "code":"PF00550",
                        "end":71,
                        "start":5
                    }
                ],
                "end":11505,
                "id":"JOIW01000001.1.cluster027_ORF10",
                "start":11271,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":129.2,
                        "code":"PF04075",
                        "end":210,
                        "start":82
                    }
                ],
                "end":12198,
                "id":"JOIW01000001.1.cluster027_ORF11",
                "start":11559,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":67.7,
                        "code":"PF00881",
                        "end":221,
                        "start":22
                    }
                ],
                "end":13073,
                "id":"JOIW01000001.1.cluster027_ORF12",
                "start":12341,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Streptomyces sp. Root55 contig_18, whole genome shotgun sequence",
        "end":7214,
        "id":"LMFT01000001.1.cluster017",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":59.3,
                        "code":"PF14765",
                        "end":221,
                        "start":75
                    },
                    {
                        "bitscore":210.6,
                        "code":"PF08659",
                        "end":626,
                        "start":447
                    },
                    {
                        "bitscore":37.2,
                        "code":"PF00550",
                        "end":799,
                        "start":732
                    },
                    {
                        "bitscore":235.5,
                        "code":"PF07993",
                        "end":1085,
                        "start":848
                    }
                ],
                "end":3639,
                "id":"KQZ17929.1",
                "start":1,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":216.4,
                        "code":"PF13561",
                        "end":254,
                        "start":17
                    }
                ],
                "end":4580,
                "id":"KQZ17930.1",
                "start":3809,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.1,
                        "code":"PF03756",
                        "end":301,
                        "start":186
                    },
                    {
                        "bitscore":33.4,
                        "code":"PF03756",
                        "end":154,
                        "start":30
                    }
                ],
                "end":5580,
                "id":"KQZ17866.1",
                "start":4671,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":62.3,
                        "code":"PF00440",
                        "end":60,
                        "start":14
                    }
                ],
                "end":6369,
                "id":"KQZ17867.1",
                "start":5691,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":161.1,
                        "code":"PF03704",
                        "end":248,
                        "start":103
                    },
                    {
                        "bitscore":37.5,
                        "code":"PF00486",
                        "end":96,
                        "start":21
                    }
                ],
                "end":7214,
                "id":"KQZ17868.1",
                "start":6383,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
