var bs_data=[
    {
        "desc":"contig_6945, whole genome shotgun sequence",
        "end":20525,
        "id":"151_sub.region001.contig_6945",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":55.5,
                        "code":"PF17765",
                        "end":235,
                        "start":93
                    },
                    {
                        "bitscore":30.4,
                        "code":"PF13560",
                        "end":68,
                        "start":8
                    }
                ],
                "end":1017,
                "id":"gnl_Bakta_AMIGOI_29010",
                "start":132,
                "strand":-1
            },
            {
                "domains":[],
                "end":1553,
                "id":"gnl_Bakta_AMIGOI_29015",
                "start":1052,
                "strand":1
            },
            {
                "domains":[],
                "end":1888,
                "id":"gnl_Bakta_AMIGOI_29020",
                "start":1654,
                "strand":-1
            },
            {
                "domains":[],
                "end":2196,
                "id":"asnC",
                "start":1932,
                "strand":1
            },
            {
                "domains":[],
                "end":3017,
                "id":"gnl_Bakta_AMIGOI_29030",
                "start":2366,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.8,
                        "code":"PF02371",
                        "end":105,
                        "start":19
                    }
                ],
                "end":3621,
                "id":"gnl_Bakta_AMIGOI_29035",
                "start":3183,
                "strand":1
            },
            {
                "domains":[],
                "end":4376,
                "id":"gnl_Bakta_AMIGOI_29040",
                "start":3893,
                "strand":-1
            },
            {
                "domains":[],
                "end":5974,
                "id":"gnl_Bakta_AMIGOI_29050",
                "start":5260,
                "strand":-1
            },
            {
                "domains":[],
                "end":6680,
                "id":"gnl_Bakta_AMIGOI_29055",
                "start":6077,
                "strand":1
            },
            {
                "domains":[],
                "end":7010,
                "id":"gnl_Bakta_AMIGOI_29060",
                "start":6761,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.7,
                        "code":"PF00535",
                        "end":140,
                        "start":5
                    }
                ],
                "end":7546,
                "id":"gnl_Bakta_AMIGOI_29065",
                "start":7006,
                "strand":-1
            },
            {
                "domains":[],
                "end":8237,
                "id":"gnl_Bakta_AMIGOI_29070",
                "start":7673,
                "strand":-1
            },
            {
                "domains":[],
                "end":8567,
                "id":"gnl_Bakta_AMIGOI_29075",
                "start":8417,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":61.8,
                        "code":"PF13450",
                        "end":68,
                        "start":2
                    }
                ],
                "end":9120,
                "id":"gnl_Bakta_AMIGOI_29080",
                "start":8838,
                "strand":-1
            },
            {
                "domains":[],
                "end":9287,
                "id":"gnl_Bakta_AMIGOI_29085",
                "start":9164,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":93.9,
                        "code":"PF00494",
                        "end":161,
                        "start":21
                    }
                ],
                "end":10525,
                "id":"gnl_Bakta_AMIGOI_29090",
                "start":10000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":135.7,
                        "code":"PF01593",
                        "end":492,
                        "start":21
                    }
                ],
                "end":12450,
                "id":"gnl_Bakta_AMIGOI_29095",
                "start":10521,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":28.0,
                        "code":"PF00348",
                        "end":304,
                        "start":238
                    },
                    {
                        "bitscore":64.4,
                        "code":"PF00348",
                        "end":167,
                        "start":39
                    }
                ],
                "end":13515,
                "id":"gnl_Bakta_AMIGOI_29100",
                "start":12492,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":167.9,
                        "code":"PF02601",
                        "end":494,
                        "start":148
                    },
                    {
                        "bitscore":65.4,
                        "code":"PF13742",
                        "end":124,
                        "start":21
                    }
                ],
                "end":15153,
                "id":"gnl_Bakta_AMIGOI_29105",
                "start":13527,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":192.6,
                        "code":"PF02646",
                        "end":363,
                        "start":112
                    }
                ],
                "end":16498,
                "id":"gnl_Bakta_AMIGOI_29110",
                "start":15166,
                "strand":-1
            },
            {
                "domains":[],
                "end":17296,
                "id":"gnl_Bakta_AMIGOI_29115",
                "start":16744,
                "strand":-1
            },
            {
                "domains":[],
                "end":18632,
                "id":"gnl_Bakta_AMIGOI_29125",
                "start":17609,
                "strand":-1
            },
            {
                "domains":[],
                "end":18831,
                "id":"gnl_Bakta_AMIGOI_29130",
                "start":18672,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.7,
                        "code":"PF06271",
                        "end":164,
                        "start":57
                    }
                ],
                "end":19322,
                "id":"gnl_Bakta_AMIGOI_29135",
                "start":18827,
                "strand":-1
            },
            {
                "domains":[],
                "end":19653,
                "id":"gnl_Bakta_AMIGOI_29140",
                "start":19374,
                "strand":-1
            },
            {
                "domains":[],
                "end":19883,
                "id":"gnl_Bakta_AMIGOI_29145",
                "start":19649,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":207.6,
                        "code":"PF01039",
                        "end":158,
                        "start":1
                    }
                ],
                "end":20494,
                "id":"gnl_Bakta_AMIGOI_29150",
                "start":20011,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_594, whole genome shotgun sequence",
        "end":20915,
        "id":"2078.region001.contig_594",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":1424,
                "id":"gnl_Bakta_CCBMAC_07745",
                "start":818,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.8,
                        "code":"PF12833",
                        "end":111,
                        "start":32
                    },
                    {
                        "bitscore":94.4,
                        "code":"PF06029",
                        "end":240,
                        "start":125
                    }
                ],
                "end":2954,
                "id":"gnl_Bakta_CCBMAC_07750",
                "start":1745,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.2,
                        "code":"PF01035",
                        "end":160,
                        "start":81
                    }
                ],
                "end":3445,
                "id":"gnl_Bakta_CCBMAC_07755",
                "start":2950,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":262.2,
                        "code":"PF00793",
                        "end":335,
                        "start":73
                    },
                    {
                        "bitscore":67.3,
                        "code":"PF18152",
                        "end":67,
                        "start":1
                    }
                ],
                "end":4489,
                "id":"gnl_Bakta_CCBMAC_07760",
                "start":3457,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":149.5,
                        "code":"PF01261",
                        "end":292,
                        "start":33
                    }
                ],
                "end":5632,
                "id":"gnl_Bakta_CCBMAC_07765",
                "start":4750,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":40.9,
                        "code":"PF03793",
                        "end":412,
                        "start":352
                    },
                    {
                        "bitscore":55.8,
                        "code":"PF03793",
                        "end":347,
                        "start":284
                    },
                    {
                        "bitscore":53.1,
                        "code":"PF03793",
                        "end":279,
                        "start":216
                    },
                    {
                        "bitscore":51.7,
                        "code":"PF03793",
                        "end":211,
                        "start":148
                    }
                ],
                "end":6870,
                "id":"gnl_Bakta_CCBMAC_07770",
                "start":5631,
                "strand":-1
            },
            {
                "domains":[],
                "end":7648,
                "id":"gnl_Bakta_CCBMAC_07775",
                "start":7174,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":148.2,
                        "code":"PF07992",
                        "end":273,
                        "start":2
                    },
                    {
                        "bitscore":59.3,
                        "code":"PF14759",
                        "end":385,
                        "start":299
                    }
                ],
                "end":8875,
                "id":"gnl_Bakta_CCBMAC_07780",
                "start":7711,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.9,
                        "code":"PF21531",
                        "end":66,
                        "start":8
                    },
                    {
                        "bitscore":92.9,
                        "code":"PF18367",
                        "end":127,
                        "start":72
                    }
                ],
                "end":9293,
                "id":"gnl_Bakta_CCBMAC_07785",
                "start":8906,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":39.4,
                        "code":"PF18916",
                        "end":97,
                        "start":3
                    }
                ],
                "end":9640,
                "id":"gnl_Bakta_CCBMAC_07790",
                "start":9295,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":230.3,
                        "code":"PF00494",
                        "end":286,
                        "start":27
                    }
                ],
                "end":10915,
                "id":"gnl_Bakta_CCBMAC_07800",
                "start":10000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":42.2,
                        "code":"PF01337",
                        "end":146,
                        "start":63
                    }
                ],
                "end":11543,
                "id":"gnl_Bakta_CCBMAC_07805",
                "start":11042,
                "strand":1
            },
            {
                "domains":[],
                "end":12180,
                "id":"gnl_Bakta_CCBMAC_07810",
                "start":11556,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":116.8,
                        "code":"PF01593",
                        "end":287,
                        "start":18
                    }
                ],
                "end":13058,
                "id":"gnl_Bakta_CCBMAC_07815",
                "start":12179,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":175.0,
                        "code":"PF00348",
                        "end":310,
                        "start":41
                    }
                ],
                "end":14131,
                "id":"gnl_Bakta_CCBMAC_07820",
                "start":13063,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":74.5,
                        "code":"PF01593",
                        "end":496,
                        "start":11
                    }
                ],
                "end":15714,
                "id":"crtI",
                "start":14214,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":168.0,
                        "code":"PF01276",
                        "end":325,
                        "start":20
                    },
                    {
                        "bitscore":36.2,
                        "code":"PF03711",
                        "end":463,
                        "start":386
                    }
                ],
                "end":17193,
                "id":"gnl_Bakta_CCBMAC_07830",
                "start":15729,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":75.5,
                        "code":"PF00535",
                        "end":220,
                        "start":48
                    }
                ],
                "end":18377,
                "id":"gnl_Bakta_CCBMAC_07835",
                "start":17258,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":124.9,
                        "code":"PF04240",
                        "end":258,
                        "start":43
                    }
                ],
                "end":19168,
                "id":"gnl_Bakta_CCBMAC_07840",
                "start":18373,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":142.3,
                        "code":"PF13548",
                        "end":174,
                        "start":5
                    }
                ],
                "end":19752,
                "id":"gnl_Bakta_CCBMAC_07845",
                "start":19164,
                "strand":-1
            },
            {
                "domains":[],
                "end":20507,
                "id":"gnl_Bakta_CCBMAC_07850",
                "start":19739,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_1861, whole genome shotgun sequence",
        "end":10743,
        "id":"267.region001.contig_1861",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":62.9,
                        "code":"PF00494",
                        "end":199,
                        "start":84
                    }
                ],
                "end":743,
                "id":"gnl_Bakta_DBMEPI_12375",
                "start":11,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":24.1,
                        "code":"PF13428",
                        "end":73,
                        "start":35
                    }
                ],
                "end":1403,
                "id":"gnl_Bakta_DBMEPI_12380",
                "start":1088,
                "strand":1
            },
            {
                "domains":[],
                "end":2359,
                "id":"gnl_Bakta_DBMEPI_12385",
                "start":1516,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.1,
                        "code":"PF00454",
                        "end":205,
                        "start":58
                    }
                ],
                "end":3384,
                "id":"gnl_Bakta_DBMEPI_12390",
                "start":2577,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":63.8,
                        "code":"PF08241",
                        "end":135,
                        "start":44
                    }
                ],
                "end":4104,
                "id":"gnl_Bakta_DBMEPI_12395",
                "start":3432,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":35.4,
                        "code":"PF00069",
                        "end":113,
                        "start":1
                    }
                ],
                "end":4711,
                "id":"gnl_Bakta_DBMEPI_12400",
                "start":4366,
                "strand":1
            },
            {
                "domains":[],
                "end":5014,
                "id":"gnl_Bakta_DBMEPI_12405",
                "start":4744,
                "strand":1
            },
            {
                "domains":[],
                "end":6996,
                "id":"gnl_Bakta_DBMEPI_12410",
                "start":5220,
                "strand":1
            },
            {
                "domains":[],
                "end":7248,
                "id":"gnl_Bakta_DBMEPI_12415",
                "start":7026,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.2,
                        "code":"PF00535",
                        "end":172,
                        "start":11
                    }
                ],
                "end":8032,
                "id":"gnl_Bakta_DBMEPI_12420",
                "start":7318,
                "strand":-1
            },
            {
                "domains":[],
                "end":8342,
                "id":"gnl_Bakta_DBMEPI_12425",
                "start":8153,
                "strand":-1
            },
            {
                "domains":[],
                "end":9463,
                "id":"267.region001.contig_1861_ORF12",
                "start":8758,
                "strand":1
            },
            {
                "domains":[],
                "end":9907,
                "id":"gnl_Bakta_DBMEPI_12435",
                "start":9472,
                "strand":-1
            },
            {
                "domains":[],
                "end":10702,
                "id":"gnl_Bakta_DBMEPI_12445",
                "start":10060,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_1868, whole genome shotgun sequence",
        "end":9036,
        "id":"267.region001.contig_1868",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":41.9,
                        "code":"PF13432",
                        "end":53,
                        "start":1
                    }
                ],
                "end":407,
                "id":"gnl_Bakta_DBMEPI_12485",
                "start":116,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":56.8,
                        "code":"PF00593",
                        "end":142,
                        "start":1
                    }
                ],
                "end":1116,
                "id":"gnl_Bakta_DBMEPI_12490",
                "start":594,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":52.0,
                        "code":"PF00593",
                        "end":602,
                        "start":393
                    },
                    {
                        "bitscore":64.8,
                        "code":"PF07715",
                        "end":234,
                        "start":128
                    },
                    {
                        "bitscore":46.0,
                        "code":"PF13620",
                        "end":109,
                        "start":34
                    }
                ],
                "end":2948,
                "id":"gnl_Bakta_DBMEPI_12495",
                "start":1124,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":77.7,
                        "code":"PF01926",
                        "end":140,
                        "start":6
                    },
                    {
                        "bitscore":91.9,
                        "code":"PF06071",
                        "end":358,
                        "start":275
                    }
                ],
                "end":4589,
                "id":"ychF",
                "start":3512,
                "strand":1
            },
            {
                "domains":[],
                "end":5514,
                "id":"gnl_Bakta_DBMEPI_12510",
                "start":4953,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":333.3,
                        "code":"PF13249",
                        "end":319,
                        "start":28
                    }
                ],
                "end":6959,
                "id":"gnl_Bakta_DBMEPI_12515",
                "start":5756,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":84.3,
                        "code":"PF13243",
                        "end":100,
                        "start":1
                    }
                ],
                "end":7780,
                "id":"gnl_Bakta_DBMEPI_12520",
                "start":6955,
                "strand":1
            },
            {
                "domains":[],
                "end":8030,
                "id":"gnl_Bakta_DBMEPI_12525",
                "start":7823,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":54.7,
                        "code":"PF11946",
                        "end":69,
                        "start":1
                    }
                ],
                "end":8691,
                "id":"gnl_Bakta_DBMEPI_12530",
                "start":8478,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_7044, whole genome shotgun sequence",
        "end":17726,
        "id":"267.region001.contig_7044",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":666,
                "id":"gnl_Bakta_DBMEPI_21975",
                "start":456,
                "strand":-1
            },
            {
                "domains":[],
                "end":1214,
                "id":"gnl_Bakta_DBMEPI_21980",
                "start":662,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":25.9,
                        "code":"PF14559",
                        "end":91,
                        "start":25
                    }
                ],
                "end":1799,
                "id":"gnl_Bakta_DBMEPI_21985",
                "start":1259,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":167.2,
                        "code":"PF00069",
                        "end":277,
                        "start":12
                    }
                ],
                "end":3555,
                "id":"gnl_Bakta_DBMEPI_21990",
                "start":1899,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":32.0,
                        "code":"PF02771",
                        "end":97,
                        "start":8
                    },
                    {
                        "bitscore":38.4,
                        "code":"PF00441",
                        "end":377,
                        "start":231
                    }
                ],
                "end":4904,
                "id":"gnl_Bakta_DBMEPI_21995",
                "start":3731,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":16.1,
                        "code":"PF13432",
                        "end":583,
                        "start":541
                    },
                    {
                        "bitscore":163.6,
                        "code":"PF00069",
                        "end":262,
                        "start":9
                    }
                ],
                "end":7463,
                "id":"gnl_Bakta_DBMEPI_22000",
                "start":4907,
                "strand":-1
            },
            {
                "domains":[],
                "end":8346,
                "id":"gnl_Bakta_DBMEPI_22005",
                "start":7500,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":25.5,
                        "code":"PF00326",
                        "end":438,
                        "start":286
                    }
                ],
                "end":9728,
                "id":"gnl_Bakta_DBMEPI_22010",
                "start":8342,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":62.8,
                        "code":"PF00494",
                        "end":118,
                        "start":7
                    }
                ],
                "end":10534,
                "id":"gnl_Bakta_DBMEPI_22015",
                "start":10000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":28.9,
                        "code":"PF00494",
                        "end":70,
                        "start":16
                    }
                ],
                "end":10943,
                "id":"gnl_Bakta_DBMEPI_22020",
                "start":10721,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.6,
                        "code":"PF00696",
                        "end":216,
                        "start":2
                    }
                ],
                "end":11730,
                "id":"gnl_Bakta_DBMEPI_22025",
                "start":11004,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":27.1,
                        "code":"PF00288",
                        "end":154,
                        "start":95
                    }
                ],
                "end":12821,
                "id":"gnl_Bakta_DBMEPI_22030",
                "start":11858,
                "strand":-1
            },
            {
                "domains":[],
                "end":13471,
                "id":"gnl_Bakta_DBMEPI_22035",
                "start":12817,
                "strand":-1
            },
            {
                "domains":[],
                "end":13902,
                "id":"gnl_Bakta_DBMEPI_22040",
                "start":13542,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":126.8,
                        "code":"PF00368",
                        "end":122,
                        "start":1
                    }
                ],
                "end":14295,
                "id":"gnl_Bakta_DBMEPI_22045",
                "start":13911,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":114.8,
                        "code":"PF00368",
                        "end":150,
                        "start":29
                    }
                ],
                "end":15150,
                "id":"gnl_Bakta_DBMEPI_22050",
                "start":14697,
                "strand":-1
            },
            {
                "domains":[],
                "end":16173,
                "id":"gnl_Bakta_DBMEPI_22055",
                "start":15456,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":85.5,
                        "code":"PF00348",
                        "end":109,
                        "start":1
                    }
                ],
                "end":16646,
                "id":"gnl_Bakta_DBMEPI_22060",
                "start":16169,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":75.0,
                        "code":"PF00348",
                        "end":128,
                        "start":49
                    }
                ],
                "end":17276,
                "id":"gnl_Bakta_DBMEPI_22065",
                "start":16739,
                "strand":-1
            },
            {
                "domains":[],
                "end":17677,
                "id":"gnl_Bakta_DBMEPI_22070",
                "start":17470,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_10501, whole genome shotgun sequence",
        "end":8041,
        "id":"377.region001.contig_10501",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":74.5,
                        "code":"PF00892",
                        "end":214,
                        "start":78
                    }
                ],
                "end":882,
                "id":"gnl_Bakta_JPINFP_00265",
                "start":186,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":52.0,
                        "code":"PF00892",
                        "end":284,
                        "start":150
                    },
                    {
                        "bitscore":56.4,
                        "code":"PF00892",
                        "end":144,
                        "start":13
                    }
                ],
                "end":1769,
                "id":"eamA",
                "start":863,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":45.5,
                        "code":"PF03793",
                        "end":464,
                        "start":405
                    },
                    {
                        "bitscore":43.3,
                        "code":"PF03793",
                        "end":400,
                        "start":339
                    },
                    {
                        "bitscore":56.6,
                        "code":"PF03793",
                        "end":334,
                        "start":271
                    },
                    {
                        "bitscore":48.3,
                        "code":"PF03793",
                        "end":266,
                        "start":203
                    }
                ],
                "end":3171,
                "id":"gnl_Bakta_JPINFP_00275",
                "start":1776,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.0,
                        "code":"PF18916",
                        "end":175,
                        "start":81
                    }
                ],
                "end":4169,
                "id":"gnl_Bakta_JPINFP_00280",
                "start":3602,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":182.0,
                        "code":"PF00494",
                        "end":200,
                        "start":3
                    }
                ],
                "end":5239,
                "id":"gnl_Bakta_JPINFP_00290",
                "start":4576,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":100.4,
                        "code":"PF00545",
                        "end":141,
                        "start":62
                    }
                ],
                "end":5991,
                "id":"gnl_Bakta_JPINFP_00295",
                "start":5556,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":55.5,
                        "code":"PF01337",
                        "end":122,
                        "start":42
                    }
                ],
                "end":6374,
                "id":"gnl_Bakta_JPINFP_00300",
                "start":5990,
                "strand":1
            },
            {
                "domains":[],
                "end":7295,
                "id":"gnl_Bakta_JPINFP_00305",
                "start":6980,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":23.0,
                        "code":"PF01593",
                        "end":85,
                        "start":6
                    }
                ],
                "end":7691,
                "id":"gnl_Bakta_JPINFP_00310",
                "start":7397,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_4038, whole genome shotgun sequence",
        "end":21239,
        "id":"377.region001.contig_4038",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":39.6,
                        "code":"PF06305",
                        "end":96,
                        "start":31
                    }
                ],
                "end":672,
                "id":"gnl_Bakta_JPINFP_19190",
                "start":276,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":152.5,
                        "code":"PF00106",
                        "end":200,
                        "start":7
                    }
                ],
                "end":1545,
                "id":"gnl_Bakta_JPINFP_19195",
                "start":708,
                "strand":-1
            },
            {
                "domains":[],
                "end":3231,
                "id":"gnl_Bakta_JPINFP_19200",
                "start":2187,
                "strand":1
            },
            {
                "domains":[],
                "end":3533,
                "id":"gnl_Bakta_JPINFP_19205",
                "start":3227,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":275.0,
                        "code":"PF00202",
                        "end":294,
                        "start":14
                    }
                ],
                "end":4662,
                "id":"gnl_Bakta_JPINFP_19210",
                "start":3591,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.0,
                        "code":"PF11746",
                        "end":83,
                        "start":1
                    }
                ],
                "end":5139,
                "id":"gnl_Bakta_JPINFP_19215",
                "start":4887,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.0,
                        "code":"PF07883",
                        "end":107,
                        "start":36
                    }
                ],
                "end":5522,
                "id":"gnl_Bakta_JPINFP_19220",
                "start":5135,
                "strand":-1
            },
            {
                "domains":[],
                "end":6000,
                "id":"gnl_Bakta_JPINFP_19225",
                "start":5532,
                "strand":-1
            },
            {
                "domains":[],
                "end":7153,
                "id":"gnl_Bakta_JPINFP_19230",
                "start":6541,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":57.5,
                        "code":"PF04075",
                        "end":129,
                        "start":16
                    }
                ],
                "end":8051,
                "id":"gnl_Bakta_JPINFP_19235",
                "start":7487,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":72.3,
                        "code":"PF13380",
                        "end":126,
                        "start":14
                    }
                ],
                "end":9130,
                "id":"gnl_Bakta_JPINFP_19240",
                "start":8719,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":135.8,
                        "code":"PF01738",
                        "end":240,
                        "start":17
                    }
                ],
                "end":9996,
                "id":"gnl_Bakta_JPINFP_19245",
                "start":9264,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":105.5,
                        "code":"PF05834",
                        "end":394,
                        "start":13
                    }
                ],
                "end":11239,
                "id":"gnl_Bakta_JPINFP_19250",
                "start":10000,
                "strand":1
            },
            {
                "domains":[],
                "end":11783,
                "id":"gnl_Bakta_JPINFP_19255",
                "start":11498,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":25.3,
                        "code":"PF01402",
                        "end":40,
                        "start":3
                    }
                ],
                "end":12060,
                "id":"copG",
                "start":11856,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.9,
                        "code":"PF02661",
                        "end":81,
                        "start":3
                    }
                ],
                "end":12434,
                "id":"gnl_Bakta_JPINFP_19265",
                "start":12056,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.4,
                        "code":"PF03553",
                        "end":174,
                        "start":1
                    }
                ],
                "end":13213,
                "id":"gnl_Bakta_JPINFP_19270",
                "start":12583,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":38.0,
                        "code":"PF03553",
                        "end":220,
                        "start":171
                    }
                ],
                "end":14127,
                "id":"nhaC",
                "start":13443,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":155.1,
                        "code":"PF07993",
                        "end":242,
                        "start":6
                    }
                ],
                "end":15507,
                "id":"gnl_Bakta_JPINFP_19280",
                "start":14415,
                "strand":1
            },
            {
                "domains":[],
                "end":16568,
                "id":"gnl_Bakta_JPINFP_19285",
                "start":15539,
                "strand":1
            },
            {
                "domains":[],
                "end":17605,
                "id":"gnl_Bakta_JPINFP_19290",
                "start":16567,
                "strand":1
            },
            {
                "domains":[],
                "end":17989,
                "id":"gnl_Bakta_JPINFP_19295",
                "start":17731,
                "strand":1
            },
            {
                "domains":[],
                "end":18890,
                "id":"gnl_Bakta_JPINFP_19300",
                "start":18062,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":148.5,
                        "code":"PF00999",
                        "end":375,
                        "start":9
                    }
                ],
                "end":20040,
                "id":"yhaU",
                "start":18852,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.9,
                        "code":"PF02080",
                        "end":158,
                        "start":87
                    }
                ],
                "end":20529,
                "id":"gnl_Bakta_JPINFP_19310",
                "start":20049,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_5298, whole genome shotgun sequence",
        "end":21737,
        "id":"bins.10.region001.contig_5298",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":58.2,
                        "code":"PF01699",
                        "end":192,
                        "start":38
                    },
                    {
                        "bitscore":61.1,
                        "code":"PF01699",
                        "end":382,
                        "start":236
                    }
                ],
                "end":1612,
                "id":"gnl_Bakta_CBDGDI_11120",
                "start":460,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":75.5,
                        "code":"PF07510",
                        "end":215,
                        "start":75
                    }
                ],
                "end":2319,
                "id":"gnl_Bakta_CBDGDI_11125",
                "start":1656,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":184.4,
                        "code":"PF13449",
                        "end":299,
                        "start":24
                    }
                ],
                "end":3281,
                "id":"gnl_Bakta_CBDGDI_11130",
                "start":2315,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":275.6,
                        "code":"PF13810",
                        "end":652,
                        "start":290
                    }
                ],
                "end":5681,
                "id":"gnl_Bakta_CBDGDI_11135",
                "start":3689,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":45.5,
                        "code":"PF12680",
                        "end":100,
                        "start":2
                    }
                ],
                "end":6305,
                "id":"gnl_Bakta_CBDGDI_11140",
                "start":5930,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":194.8,
                        "code":"PF16877",
                        "end":152,
                        "start":34
                    }
                ],
                "end":6775,
                "id":"gnl_Bakta_CBDGDI_11145",
                "start":6316,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":49.0,
                        "code":"PF05305",
                        "end":101,
                        "start":24
                    }
                ],
                "end":7160,
                "id":"gnl_Bakta_CBDGDI_11150",
                "start":6824,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":116.7,
                        "code":"PF13561",
                        "end":177,
                        "start":27
                    }
                ],
                "end":7715,
                "id":"bins.10.region001.contig_5298_ORF8",
                "start":7172,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":144.7,
                        "code":"PF00348",
                        "end":330,
                        "start":60
                    }
                ],
                "end":9186,
                "id":"gnl_Bakta_CBDGDI_11160",
                "start":8046,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":99.6,
                        "code":"PF01593",
                        "end":269,
                        "start":18
                    }
                ],
                "end":10029,
                "id":"gnl_Bakta_CBDGDI_11165",
                "start":9213,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.1,
                        "code":"PF01593",
                        "end":227,
                        "start":1
                    },
                    {
                        "bitscore":229.8,
                        "code":"PF00494",
                        "end":535,
                        "start":274
                    }
                ],
                "end":11737,
                "id":"gnl_Bakta_CBDGDI_11170",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":61.7,
                        "code":"PF01209",
                        "end":235,
                        "start":7
                    }
                ],
                "end":12477,
                "id":"gnl_Bakta_CBDGDI_11175",
                "start":11733,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":97.2,
                        "code":"PF01593",
                        "end":301,
                        "start":6
                    }
                ],
                "end":13506,
                "id":"bins.10.region001.contig_5298_ORF13",
                "start":12558,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":299.2,
                        "code":"PF19299",
                        "end":192,
                        "start":6
                    }
                ],
                "end":15034,
                "id":"bins.10.region001.contig_5298_ORF15",
                "start":14446,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":60.4,
                        "code":"PF19328",
                        "end":349,
                        "start":139
                    }
                ],
                "end":16122,
                "id":"gnl_Bakta_CBDGDI_11195",
                "start":15045,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":52.3,
                        "code":"PF03492",
                        "end":191,
                        "start":5
                    }
                ],
                "end":16741,
                "id":"gnl_Bakta_CBDGDI_11200",
                "start":16054,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.7,
                        "code":"PF03492",
                        "end":121,
                        "start":26
                    }
                ],
                "end":17163,
                "id":"gnl_Bakta_CBDGDI_11205",
                "start":16746,
                "strand":-1
            },
            {
                "domains":[],
                "end":18107,
                "id":"gnl_Bakta_CBDGDI_11210",
                "start":17918,
                "strand":1
            },
            {
                "domains":[],
                "end":19069,
                "id":"gnl_Bakta_CBDGDI_11215",
                "start":18724,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":86.5,
                        "code":"PF00753",
                        "end":187,
                        "start":21
                    }
                ],
                "end":19706,
                "id":"gnl_Bakta_CBDGDI_11220",
                "start":19079,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":108.9,
                        "code":"PF00107",
                        "end":324,
                        "start":190
                    },
                    {
                        "bitscore":87.7,
                        "code":"PF08240",
                        "end":148,
                        "start":29
                    }
                ],
                "end":20788,
                "id":"gnl_Bakta_CBDGDI_11225",
                "start":19702,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":76.6,
                        "code":"PF00753",
                        "end":273,
                        "start":57
                    }
                ],
                "end":21678,
                "id":"gnl_Bakta_CBDGDI_11230",
                "start":20799,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_4187, whole genome shotgun sequence",
        "end":20642,
        "id":"bins.25_sub.region001.contig_4187",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":103.0,
                        "code":"PF01145",
                        "end":233,
                        "start":28
                    }
                ],
                "end":1218,
                "id":"gnl_Bakta_GAHAIK_09185",
                "start":183,
                "strand":1
            },
            {
                "domains":[],
                "end":1468,
                "id":"gnl_Bakta_GAHAIK_09190",
                "start":1270,
                "strand":-1
            },
            {
                "domains":[],
                "end":2630,
                "id":"gnl_Bakta_GAHAIK_09195",
                "start":1967,
                "strand":-1
            },
            {
                "domains":[],
                "end":3578,
                "id":"gnl_Bakta_GAHAIK_09200",
                "start":3239,
                "strand":-1
            },
            {
                "domains":[],
                "end":4310,
                "id":"gnl_Bakta_GAHAIK_09205",
                "start":3935,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":29.0,
                        "code":"PF18927",
                        "end":83,
                        "start":38
                    }
                ],
                "end":5193,
                "id":"gnl_Bakta_GAHAIK_09215",
                "start":4935,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.9,
                        "code":"PF00535",
                        "end":188,
                        "start":48
                    }
                ],
                "end":6565,
                "id":"gnl_Bakta_GAHAIK_09220",
                "start":5320,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.8,
                        "code":"PF04116",
                        "end":146,
                        "start":11
                    }
                ],
                "end":7050,
                "id":"gnl_Bakta_GAHAIK_09225",
                "start":6570,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":30.8,
                        "code":"PF18916",
                        "end":60,
                        "start":1
                    }
                ],
                "end":7271,
                "id":"gnl_Bakta_GAHAIK_09230",
                "start":7046,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.0,
                        "code":"PF18916",
                        "end":97,
                        "start":5
                    }
                ],
                "end":7748,
                "id":"gnl_Bakta_GAHAIK_09235",
                "start":7376,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":130.1,
                        "code":"PF01593",
                        "end":486,
                        "start":10
                    }
                ],
                "end":9364,
                "id":"gnl_Bakta_GAHAIK_09240",
                "start":7894,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":32.4,
                        "code":"PF00494",
                        "end":62,
                        "start":1
                    }
                ],
                "end":10642,
                "id":"gnl_Bakta_GAHAIK_09245",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.1,
                        "code":"PF01987",
                        "end":135,
                        "start":18
                    }
                ],
                "end":11327,
                "id":"gnl_Bakta_GAHAIK_09255",
                "start":10880,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":146.4,
                        "code":"PF01566",
                        "end":187,
                        "start":1
                    }
                ],
                "end":12240,
                "id":"gnl_Bakta_GAHAIK_09260",
                "start":11403,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":32.7,
                        "code":"PF00571",
                        "end":70,
                        "start":4
                    }
                ],
                "end":12941,
                "id":"gnl_Bakta_GAHAIK_09265",
                "start":12695,
                "strand":-1
            },
            {
                "domains":[],
                "end":13832,
                "id":"gnl_Bakta_GAHAIK_09270",
                "start":13241,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.8,
                        "code":"PF03883",
                        "end":120,
                        "start":1
                    }
                ],
                "end":15147,
                "id":"gnl_Bakta_GAHAIK_09280",
                "start":14733,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":107.1,
                        "code":"PF02583",
                        "end":91,
                        "start":9
                    }
                ],
                "end":15441,
                "id":"copY",
                "start":15153,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":55.1,
                        "code":"PF00403",
                        "end":63,
                        "start":5
                    }
                ],
                "end":15709,
                "id":"gnl_Bakta_GAHAIK_09290",
                "start":15502,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":99.9,
                        "code":"PF04116",
                        "end":321,
                        "start":188
                    }
                ],
                "end":16895,
                "id":"gnl_Bakta_GAHAIK_09295",
                "start":15710,
                "strand":-1
            },
            {
                "domains":[],
                "end":17628,
                "id":"gnl_Bakta_GAHAIK_09300",
                "start":17046,
                "strand":-1
            },
            {
                "domains":[],
                "end":18718,
                "id":"gnl_Bakta_GAHAIK_09305",
                "start":17761,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":25.0,
                        "code":"PF00440",
                        "end":77,
                        "start":32
                    }
                ],
                "end":20220,
                "id":"gnl_Bakta_GAHAIK_09315",
                "start":19584,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_14714, whole genome shotgun sequence",
        "end":20873,
        "id":"bins.36.region001.contig_14714",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":62.8,
                        "code":"PF13393",
                        "end":71,
                        "start":11
                    }
                ],
                "end":836,
                "id":"gnl_Bakta_NBAJGP_04300",
                "start":617,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.4,
                        "code":"PF09838",
                        "end":48,
                        "start":1
                    }
                ],
                "end":1010,
                "id":"gnl_Bakta_NBAJGP_04305",
                "start":860,
                "strand":-1
            },
            {
                "domains":[],
                "end":1594,
                "id":"gnl_Bakta_NBAJGP_04310",
                "start":1273,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":47.0,
                        "code":"PF01145",
                        "end":95,
                        "start":1
                    }
                ],
                "end":1990,
                "id":"hflC",
                "start":1702,
                "strand":-1
            },
            {
                "domains":[],
                "end":2462,
                "id":"gnl_Bakta_NBAJGP_04320",
                "start":2165,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":54.2,
                        "code":"PF01145",
                        "end":129,
                        "start":42
                    }
                ],
                "end":3188,
                "id":"gnl_Bakta_NBAJGP_04330",
                "start":2735,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":33.1,
                        "code":"PF19275",
                        "end":419,
                        "start":328
                    },
                    {
                        "bitscore":69.3,
                        "code":"PF01926",
                        "end":318,
                        "start":199
                    },
                    {
                        "bitscore":96.5,
                        "code":"PF16360",
                        "end":192,
                        "start":114
                    },
                    {
                        "bitscore":104.9,
                        "code":"PF13167",
                        "end":112,
                        "start":25
                    }
                ],
                "end":4860,
                "id":"hflX",
                "start":3585,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":105.3,
                        "code":"PF17209",
                        "end":69,
                        "start":7
                    }
                ],
                "end":5174,
                "id":"hfq",
                "start":4922,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":89.9,
                        "code":"PF00677",
                        "end":184,
                        "start":100
                    },
                    {
                        "bitscore":76.0,
                        "code":"PF00677",
                        "end":87,
                        "start":3
                    }
                ],
                "end":6062,
                "id":"gnl_Bakta_NBAJGP_04345",
                "start":5324,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":157.2,
                        "code":"PF01872",
                        "end":367,
                        "start":149
                    },
                    {
                        "bitscore":68.0,
                        "code":"PF00383",
                        "end":102,
                        "start":3
                    }
                ],
                "end":7244,
                "id":"ribD",
                "start":6119,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":78.1,
                        "code":"PF03477",
                        "end":137,
                        "start":49
                    }
                ],
                "end":7756,
                "id":"nrdR",
                "start":7240,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":570.7,
                        "code":"PF00464",
                        "end":378,
                        "start":8
                    }
                ],
                "end":9039,
                "id":"gnl_Bakta_NBAJGP_04360",
                "start":7896,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":80.1,
                        "code":"PF13489",
                        "end":213,
                        "start":33
                    }
                ],
                "end":9955,
                "id":"gnl_Bakta_NBAJGP_04365",
                "start":9211,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":105.3,
                        "code":"PF00494",
                        "end":264,
                        "start":11
                    }
                ],
                "end":10873,
                "id":"gnl_Bakta_NBAJGP_04370",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":131.6,
                        "code":"PF00106",
                        "end":212,
                        "start":13
                    }
                ],
                "end":11571,
                "id":"gnl_Bakta_NBAJGP_04375",
                "start":10869,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":64.8,
                        "code":"PF09360",
                        "end":209,
                        "start":165
                    },
                    {
                        "bitscore":53.5,
                        "code":"PF09360",
                        "end":134,
                        "start":90
                    },
                    {
                        "bitscore":68.1,
                        "code":"PF06902",
                        "end":72,
                        "start":9
                    }
                ],
                "end":12291,
                "id":"gnl_Bakta_NBAJGP_04380",
                "start":11640,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":200.0,
                        "code":"PF13561",
                        "end":246,
                        "start":13
                    }
                ],
                "end":13223,
                "id":"gnl_Bakta_NBAJGP_04385",
                "start":12476,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":95.1,
                        "code":"PF17954",
                        "end":231,
                        "start":146
                    },
                    {
                        "bitscore":127.6,
                        "code":"PF02678",
                        "end":119,
                        "start":4
                    }
                ],
                "end":14058,
                "id":"gnl_Bakta_NBAJGP_04390",
                "start":13356,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":128.3,
                        "code":"PF06897",
                        "end":161,
                        "start":60
                    }
                ],
                "end":14878,
                "id":"gnl_Bakta_NBAJGP_04395",
                "start":14365,
                "strand":-1
            },
            {
                "domains":[],
                "end":15495,
                "id":"gnl_Bakta_NBAJGP_04400",
                "start":15207,
                "strand":-1
            },
            {
                "domains":[],
                "end":15717,
                "id":"gnl_Bakta_NBAJGP_04405",
                "start":15531,
                "strand":-1
            },
            {
                "domains":[],
                "end":16358,
                "id":"gnl_Bakta_NBAJGP_04410",
                "start":15785,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":125.5,
                        "code":"PF13365",
                        "end":257,
                        "start":123
                    },
                    {
                        "bitscore":52.6,
                        "code":"PF13180",
                        "end":387,
                        "start":296
                    },
                    {
                        "bitscore":40.6,
                        "code":"PF17820",
                        "end":490,
                        "start":436
                    }
                ],
                "end":18116,
                "id":"gnl_Bakta_NBAJGP_04415",
                "start":16598,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":84.5,
                        "code":"PF00072",
                        "end":113,
                        "start":3
                    },
                    {
                        "bitscore":99.8,
                        "code":"PF00486",
                        "end":221,
                        "start":146
                    }
                ],
                "end":19148,
                "id":"phoB",
                "start":18473,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":39.3,
                        "code":"PF00672",
                        "end":270,
                        "start":217
                    },
                    {
                        "bitscore":37.9,
                        "code":"PF00512",
                        "end":344,
                        "start":275
                    },
                    {
                        "bitscore":92.6,
                        "code":"PF02518",
                        "end":498,
                        "start":389
                    }
                ],
                "end":20707,
                "id":"gnl_Bakta_NBAJGP_04425",
                "start":19144,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_956, whole genome shotgun sequence",
        "end":20615,
        "id":"bins.36.region001.contig_956",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":97.3,
                        "code":"PF04432",
                        "end":313,
                        "start":162
                    },
                    {
                        "bitscore":67.1,
                        "code":"PF04422",
                        "end":155,
                        "start":79
                    }
                ],
                "end":2741,
                "id":"gnl_Bakta_NBAJGP_26905",
                "start":1475,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":60.5,
                        "code":"PF00561",
                        "end":163,
                        "start":13
                    }
                ],
                "end":3950,
                "id":"gnl_Bakta_NBAJGP_26910",
                "start":2987,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.7,
                        "code":"PF01078",
                        "end":196,
                        "start":114
                    },
                    {
                        "bitscore":58.6,
                        "code":"PF17863",
                        "end":337,
                        "start":264
                    }
                ],
                "end":5032,
                "id":"gnl_Bakta_NBAJGP_26915",
                "start":4006,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.0,
                        "code":"PF13519",
                        "end":541,
                        "start":437
                    }
                ],
                "end":6888,
                "id":"gnl_Bakta_NBAJGP_26920",
                "start":5031,
                "strand":1
            },
            {
                "domains":[],
                "end":6987,
                "id":"gnl_Bakta_NBAJGP_26925",
                "start":6894,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":84.3,
                        "code":"PF12697",
                        "end":280,
                        "start":42
                    }
                ],
                "end":7865,
                "id":"bchO",
                "start":6983,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":98.6,
                        "code":"PF01593",
                        "end":453,
                        "start":1
                    }
                ],
                "end":9500,
                "id":"gnl_Bakta_NBAJGP_26935",
                "start":8102,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":72.2,
                        "code":"PF00494",
                        "end":103,
                        "start":2
                    }
                ],
                "end":10615,
                "id":"gnl_Bakta_NBAJGP_26940",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":218.4,
                        "code":"PF00425",
                        "end":452,
                        "start":198
                    }
                ],
                "end":12204,
                "id":"gnl_Bakta_NBAJGP_26945",
                "start":10812,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.2,
                        "code":"PF00581",
                        "end":320,
                        "start":198
                    },
                    {
                        "bitscore":39.4,
                        "code":"PF00581",
                        "end":170,
                        "start":37
                    }
                ],
                "end":13790,
                "id":"gnl_Bakta_NBAJGP_26950",
                "start":12413,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":74.2,
                        "code":"PF01794",
                        "end":165,
                        "start":51
                    }
                ],
                "end":14900,
                "id":"msrQ",
                "start":14252,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":118.9,
                        "code":"PF00174",
                        "end":261,
                        "start":99
                    }
                ],
                "end":15891,
                "id":"msrP",
                "start":14910,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":351.9,
                        "code":"PF01053",
                        "end":331,
                        "start":4
                    }
                ],
                "end":17792,
                "id":"gnl_Bakta_NBAJGP_26970",
                "start":16391,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":43.7,
                        "code":"PF00805",
                        "end":57,
                        "start":19
                    },
                    {
                        "bitscore":26.8,
                        "code":"PF00805",
                        "end":87,
                        "start":54
                    },
                    {
                        "bitscore":47.7,
                        "code":"PF00805",
                        "end":134,
                        "start":95
                    },
                    {
                        "bitscore":35.3,
                        "code":"PF00805",
                        "end":190,
                        "start":155
                    },
                    {
                        "bitscore":36.4,
                        "code":"PF00805",
                        "end":235,
                        "start":196
                    }
                ],
                "end":18833,
                "id":"gnl_Bakta_NBAJGP_26975",
                "start":17978,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.9,
                        "code":"PF00293",
                        "end":105,
                        "start":49
                    }
                ],
                "end":19545,
                "id":"gnl_Bakta_NBAJGP_26980",
                "start":19206,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_4812, whole genome shotgun sequence",
        "end":7144,
        "id":"bins.63.region001.contig_4812",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":679,
                "id":"gnl_Bakta_AKODEI_19155",
                "start":496,
                "strand":-1
            },
            {
                "domains":[],
                "end":1115,
                "id":"gnl_Bakta_AKODEI_19160",
                "start":974,
                "strand":-1
            },
            {
                "domains":[],
                "end":1978,
                "id":"gnl_Bakta_AKODEI_19165",
                "start":1795,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":188.3,
                        "code":"PF00348",
                        "end":304,
                        "start":53
                    }
                ],
                "end":3624,
                "id":"gnl_Bakta_AKODEI_19170",
                "start":2550,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":132.3,
                        "code":"PF01036",
                        "end":257,
                        "start":14
                    }
                ],
                "end":4512,
                "id":"gnl_Bakta_AKODEI_19175",
                "start":3711,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.5,
                        "code":"PF01593",
                        "end":232,
                        "start":4
                    }
                ],
                "end":5620,
                "id":"gnl_Bakta_AKODEI_19180",
                "start":4885,
                "strand":1
            },
            {
                "domains":[],
                "end":6173,
                "id":"gnl_Bakta_AKODEI_19185",
                "start":5561,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":148.4,
                        "code":"PF00494",
                        "end":238,
                        "start":23
                    }
                ],
                "end":6967,
                "id":"gnl_Bakta_AKODEI_19190",
                "start":6169,
                "strand":1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
