var bs_data=[
    {
        "desc":"contig_5039, whole genome shotgun sequence",
        "end":35277,
        "id":"CONCOCT_CONCOCT.52.region001.contig_5039",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":75.8,
                        "code":"PF01370",
                        "end":299,
                        "start":4
                    }
                ],
                "end":1056,
                "id":"gnl_Bakta_KFGDHC_16845",
                "start":66,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":92.7,
                        "code":"PF00534",
                        "end":337,
                        "start":176
                    }
                ],
                "end":2333,
                "id":"gnl_Bakta_KFGDHC_16850",
                "start":1235,
                "strand":-1
            },
            {
                "domains":[],
                "end":3355,
                "id":"gnl_Bakta_KFGDHC_16855",
                "start":2878,
                "strand":-1
            },
            {
                "domains":[],
                "end":4744,
                "id":"gnl_Bakta_KFGDHC_16860",
                "start":4198,
                "strand":-1
            },
            {
                "domains":[],
                "end":5586,
                "id":"gnl_Bakta_KFGDHC_16865",
                "start":4953,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":45.9,
                        "code":"PF01943",
                        "end":326,
                        "start":46
                    }
                ],
                "end":7343,
                "id":"gnl_Bakta_KFGDHC_16870",
                "start":6350,
                "strand":-1
            },
            {
                "domains":[],
                "end":7663,
                "id":"gnl_Bakta_KFGDHC_16875",
                "start":7471,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":58.7,
                        "code":"PF13807",
                        "end":472,
                        "start":390
                    },
                    {
                        "bitscore":35.6,
                        "code":"PF02706",
                        "end":131,
                        "start":37
                    }
                ],
                "end":9782,
                "id":"gnl_Bakta_KFGDHC_16880",
                "start":7745,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.4,
                        "code":"PF10531",
                        "end":252,
                        "start":198
                    },
                    {
                        "bitscore":24.2,
                        "code":"PF10531",
                        "end":140,
                        "start":92
                    },
                    {
                        "bitscore":76.5,
                        "code":"PF02563",
                        "end":86,
                        "start":9
                    }
                ],
                "end":10750,
                "id":"gnl_Bakta_KFGDHC_16885",
                "start":9832,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":59.5,
                        "code":"PF13727",
                        "end":445,
                        "start":262
                    },
                    {
                        "bitscore":178.3,
                        "code":"PF02397",
                        "end":196,
                        "start":3
                    }
                ],
                "end":12584,
                "id":"gnl_Bakta_KFGDHC_16890",
                "start":11171,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":134.1,
                        "code":"PF04463",
                        "end":148,
                        "start":7
                    },
                    {
                        "bitscore":144.1,
                        "code":"PF08349",
                        "end":307,
                        "start":191
                    }
                ],
                "end":14152,
                "id":"gnl_Bakta_KFGDHC_16895",
                "start":13201,
                "strand":1
            },
            {
                "domains":[],
                "end":16243,
                "id":"gnl_Bakta_KFGDHC_16900",
                "start":15535,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":165.5,
                        "code":"PF03321",
                        "end":529,
                        "start":36
                    }
                ],
                "end":18023,
                "id":"gnl_Bakta_KFGDHC_16905",
                "start":16352,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":90.9,
                        "code":"PF00441",
                        "end":328,
                        "start":178
                    },
                    {
                        "bitscore":63.8,
                        "code":"PF02770",
                        "end":166,
                        "start":71
                    },
                    {
                        "bitscore":25.5,
                        "code":"PF02771",
                        "end":67,
                        "start":1
                    }
                ],
                "end":19597,
                "id":"gnl_Bakta_KFGDHC_16910",
                "start":18556,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":67.9,
                        "code":"PF14765",
                        "end":1744,
                        "start":1589
                    },
                    {
                        "bitscore":41.0,
                        "code":"PF00698",
                        "end":1345,
                        "start":1191
                    },
                    {
                        "bitscore":37.4,
                        "code":"PF16197",
                        "end":1147,
                        "start":1050
                    },
                    {
                        "bitscore":127.6,
                        "code":"PF02801",
                        "end":1048,
                        "start":933
                    },
                    {
                        "bitscore":238.3,
                        "code":"PF00109",
                        "end":925,
                        "start":683
                    },
                    {
                        "bitscore":41.4,
                        "code":"PF00550",
                        "end":593,
                        "start":528
                    },
                    {
                        "bitscore":149.8,
                        "code":"PF00501",
                        "end":339,
                        "start":1
                    }
                ],
                "end":25376,
                "id":"gnl_Bakta_KFGDHC_16915",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.0,
                        "code":"PF11583",
                        "end":259,
                        "start":4
                    }
                ],
                "end":26529,
                "id":"gnl_Bakta_KFGDHC_16920",
                "start":25524,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.7,
                        "code":"PF00198",
                        "end":266,
                        "start":201
                    },
                    {
                        "bitscore":25.8,
                        "code":"PF00198",
                        "end":134,
                        "start":1
                    }
                ],
                "end":27420,
                "id":"gnl_Bakta_KFGDHC_16925",
                "start":26586,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":45.8,
                        "code":"PF03364",
                        "end":196,
                        "start":69
                    }
                ],
                "end":28647,
                "id":"gnl_Bakta_KFGDHC_16930",
                "start":28032,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":89.0,
                        "code":"PF13282",
                        "end":511,
                        "start":362
                    },
                    {
                        "bitscore":61.9,
                        "code":"PF04055",
                        "end":343,
                        "start":174
                    },
                    {
                        "bitscore":37.6,
                        "code":"PF02310",
                        "end":133,
                        "start":27
                    }
                ],
                "end":30357,
                "id":"gnl_Bakta_KFGDHC_16935",
                "start":28764,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.0,
                        "code":"PF13683",
                        "end":271,
                        "start":206
                    }
                ],
                "end":32347,
                "id":"gnl_Bakta_KFGDHC_16940",
                "start":31435,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":79.9,
                        "code":"PF00575",
                        "end":451,
                        "start":378
                    },
                    {
                        "bitscore":83.6,
                        "code":"PF17674",
                        "end":361,
                        "start":292
                    },
                    {
                        "bitscore":94.3,
                        "code":"PF12836",
                        "end":286,
                        "start":222
                    },
                    {
                        "bitscore":178.5,
                        "code":"PF16921",
                        "end":182,
                        "start":56
                    }
                ],
                "end":34417,
                "id":"gnl_Bakta_KFGDHC_16950",
                "start":32899,
                "strand":-1
            },
            {
                "domains":[],
                "end":34896,
                "id":"gnl_Bakta_KFGDHC_16955",
                "start":34695,
                "strand":-1
            },
            {
                "domains":[],
                "end":35035,
                "id":"gnl_Bakta_KFGDHC_16960",
                "start":34888,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_19910, whole genome shotgun sequence",
        "end":34834,
        "id":"GraphMB_1677.region001.contig_19910",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2333,
                "id":"gnl_Bakta_MICCNF_06335",
                "start":1610,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":69.9,
                        "code":"PF16576",
                        "end":81,
                        "start":14
                    }
                ],
                "end":2797,
                "id":"gnl_Bakta_MICCNF_06340",
                "start":2521,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":40.5,
                        "code":"PF00550",
                        "end":102,
                        "start":36
                    },
                    {
                        "bitscore":288.4,
                        "code":"PF00109",
                        "end":374,
                        "start":124
                    },
                    {
                        "bitscore":143.4,
                        "code":"PF02801",
                        "end":500,
                        "start":382
                    },
                    {
                        "bitscore":42.7,
                        "code":"PF16197",
                        "end":583,
                        "start":502
                    },
                    {
                        "bitscore":179.6,
                        "code":"PF00698",
                        "end":1067,
                        "start":735
                    },
                    {
                        "bitscore":29.3,
                        "code":"PF00550",
                        "end":1340,
                        "start":1282
                    },
                    {
                        "bitscore":64.6,
                        "code":"PF00975",
                        "end":1731,
                        "start":1574
                    }
                ],
                "end":8356,
                "id":"gnl_Bakta_MICCNF_06345",
                "start":2815,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":487.0,
                        "code":"PF01039",
                        "end":514,
                        "start":31
                    }
                ],
                "end":9903,
                "id":"gnl_Bakta_MICCNF_06350",
                "start":8352,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":165.7,
                        "code":"PF00975",
                        "end":236,
                        "start":11
                    }
                ],
                "end":10622,
                "id":"tesA",
                "start":9902,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":106.1,
                        "code":"PF00501",
                        "end":209,
                        "start":12
                    }
                ],
                "end":11769,
                "id":"gnl_Bakta_MICCNF_06360",
                "start":11133,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":51.5,
                        "code":"PF00501",
                        "end":160,
                        "start":2
                    },
                    {
                        "bitscore":32.6,
                        "code":"PF00550",
                        "end":400,
                        "start":334
                    },
                    {
                        "bitscore":308.0,
                        "code":"PF00109",
                        "end":669,
                        "start":419
                    },
                    {
                        "bitscore":149.7,
                        "code":"PF02801",
                        "end":795,
                        "start":677
                    },
                    {
                        "bitscore":55.6,
                        "code":"PF16197",
                        "end":859,
                        "start":797
                    }
                ],
                "end":14834,
                "id":"gnl_Bakta_MICCNF_06365",
                "start":11912,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":288.7,
                        "code":"PF00698",
                        "end":304,
                        "start":1
                    },
                    {
                        "bitscore":158.6,
                        "code":"PF08659",
                        "end":715,
                        "start":538
                    },
                    {
                        "bitscore":50.0,
                        "code":"PF00550",
                        "end":883,
                        "start":816
                    }
                ],
                "end":17592,
                "id":"ppsB",
                "start":14811,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":239.6,
                        "code":"PF00109",
                        "end":273,
                        "start":16
                    },
                    {
                        "bitscore":139.6,
                        "code":"PF02801",
                        "end":401,
                        "start":281
                    },
                    {
                        "bitscore":65.2,
                        "code":"PF16197",
                        "end":514,
                        "start":403
                    }
                ],
                "end":19181,
                "id":"gnl_Bakta_MICCNF_06375",
                "start":17588,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":179.3,
                        "code":"PF00698",
                        "end":352,
                        "start":33
                    },
                    {
                        "bitscore":46.0,
                        "code":"PF00550",
                        "end":485,
                        "start":422
                    },
                    {
                        "bitscore":100.5,
                        "code":"PF00668",
                        "end":953,
                        "start":513
                    }
                ],
                "end":22047,
                "id":"gnl_Bakta_MICCNF_06380",
                "start":19140,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":113.7,
                        "code":"PF00005",
                        "end":171,
                        "start":27
                    }
                ],
                "end":23066,
                "id":"drrA",
                "start":22058,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.3,
                        "code":"PF12698",
                        "end":263,
                        "start":33
                    }
                ],
                "end":23872,
                "id":"gnl_Bakta_MICCNF_06390",
                "start":23062,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":63.4,
                        "code":"PF01061",
                        "end":232,
                        "start":21
                    }
                ],
                "end":24684,
                "id":"gnl_Bakta_MICCNF_06395",
                "start":23871,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":193.9,
                        "code":"PF16911",
                        "end":386,
                        "start":199
                    }
                ],
                "end":25991,
                "id":"gnl_Bakta_MICCNF_06400",
                "start":24743,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":101.7,
                        "code":"PF06974",
                        "end":436,
                        "start":288
                    },
                    {
                        "bitscore":224.0,
                        "code":"PF03007",
                        "end":248,
                        "start":1
                    }
                ],
                "end":27366,
                "id":"gnl_Bakta_MICCNF_06405",
                "start":26001,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":157.0,
                        "code":"PF00106",
                        "end":207,
                        "start":12
                    }
                ],
                "end":28291,
                "id":"ydfG",
                "start":27472,
                "strand":1
            },
            {
                "domains":[],
                "end":28940,
                "id":"gnl_Bakta_MICCNF_06415",
                "start":28757,
                "strand":1
            },
            {
                "domains":[],
                "end":29777,
                "id":"evbL",
                "start":29012,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":145.9,
                        "code":"PF00069",
                        "end":262,
                        "start":12
                    }
                ],
                "end":31005,
                "id":"gnl_Bakta_MICCNF_06425",
                "start":29790,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.3,
                        "code":"PF00367",
                        "end":39,
                        "start":7
                    },
                    {
                        "bitscore":103.3,
                        "code":"PF02378",
                        "end":420,
                        "start":118
                    },
                    {
                        "bitscore":158.4,
                        "code":"PF00358",
                        "end":649,
                        "start":523
                    }
                ],
                "end":33090,
                "id":"gnl_Bakta_MICCNF_06430",
                "start":31047,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.3,
                        "code":"PF04075",
                        "end":150,
                        "start":6
                    }
                ],
                "end":33685,
                "id":"gnl_Bakta_MICCNF_06435",
                "start":33199,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
