var bs_data=[
    {
        "desc":"contig_512, whole genome shotgun sequence",
        "end":42607,
        "id":"CONCOCT.18.region002.contig_512",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":104.4,
                        "code":"PF09498",
                        "end":105,
                        "start":35
                    }
                ],
                "end":624,
                "id":"gnl_Bakta_DMCOKL_19540",
                "start":303,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":96.2,
                        "code":"PF09498",
                        "end":101,
                        "start":32
                    }
                ],
                "end":972,
                "id":"gnl_Bakta_DMCOKL_19545",
                "start":663,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":102.4,
                        "code":"PF09498",
                        "end":94,
                        "start":24
                    }
                ],
                "end":1359,
                "id":"gnl_Bakta_DMCOKL_19550",
                "start":1071,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.5,
                        "code":"PF06568",
                        "end":62,
                        "start":26
                    }
                ],
                "end":1891,
                "id":"gnl_Bakta_DMCOKL_19555",
                "start":1675,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":138.9,
                        "code":"PF13336",
                        "end":464,
                        "start":318
                    },
                    {
                        "bitscore":100.6,
                        "code":"PF02550",
                        "end":216,
                        "start":8
                    }
                ],
                "end":3701,
                "id":"aCH1",
                "start":2207,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":71.3,
                        "code":"PF02233",
                        "end":53,
                        "start":1
                    }
                ],
                "end":4048,
                "id":"gnl_Bakta_DMCOKL_19565",
                "start":3880,
                "strand":-1
            },
            {
                "domains":[],
                "end":4587,
                "id":"gnl_Bakta_DMCOKL_19570",
                "start":4170,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":97.1,
                        "code":"PF02233",
                        "end":113,
                        "start":9
                    }
                ],
                "end":4912,
                "id":"gnl_Bakta_DMCOKL_19575",
                "start":4564,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":118.0,
                        "code":"PF12769",
                        "end":95,
                        "start":11
                    }
                ],
                "end":5653,
                "id":"gnl_Bakta_DMCOKL_19580",
                "start":5128,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":142.2,
                        "code":"PF01262",
                        "end":150,
                        "start":3
                    }
                ],
                "end":6127,
                "id":"gnl_Bakta_DMCOKL_19585",
                "start":5668,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":49.1,
                        "code":"PF05222",
                        "end":79,
                        "start":1
                    }
                ],
                "end":6661,
                "id":"gnl_Bakta_DMCOKL_19590",
                "start":6376,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":35.2,
                        "code":"PF03466",
                        "end":69,
                        "start":1
                    }
                ],
                "end":7475,
                "id":"gnl_Bakta_DMCOKL_19600",
                "start":7247,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":33.4,
                        "code":"PF03466",
                        "end":82,
                        "start":30
                    }
                ],
                "end":7955,
                "id":"gnl_Bakta_DMCOKL_19605",
                "start":7664,
                "strand":-1
            },
            {
                "domains":[],
                "end":8130,
                "id":"gnl_Bakta_DMCOKL_19610",
                "start":7995,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":134.6,
                        "code":"PF02771",
                        "end":132,
                        "start":20
                    }
                ],
                "end":8802,
                "id":"gnl_Bakta_DMCOKL_19615",
                "start":8286,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":55.3,
                        "code":"PF00441",
                        "end":104,
                        "start":1
                    }
                ],
                "end":9398,
                "id":"gnl_Bakta_DMCOKL_19620",
                "start":9047,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":116.4,
                        "code":"PF02515",
                        "end":131,
                        "start":3
                    }
                ],
                "end":10386,
                "id":"CONCOCT.18.region002.contig_512_ORF18",
                "start":9987,
                "strand":1
            },
            {
                "domains":[],
                "end":17323,
                "id":"gnl_Bakta_DMCOKL_19655",
                "start":16813,
                "strand":1
            },
            {
                "domains":[],
                "end":18026,
                "id":"gnl_Bakta_DMCOKL_19660",
                "start":17291,
                "strand":1
            },
            {
                "domains":[],
                "end":18186,
                "id":"gnl_Bakta_DMCOKL_19665",
                "start":18039,
                "strand":-1
            },
            {
                "domains":[],
                "end":18702,
                "id":"gnl_Bakta_DMCOKL_19670",
                "start":18552,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.9,
                        "code":"PF10604",
                        "end":152,
                        "start":15
                    }
                ],
                "end":19202,
                "id":"gnl_Bakta_DMCOKL_19675",
                "start":18737,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":26.6,
                        "code":"PF07993",
                        "end":65,
                        "start":3
                    }
                ],
                "end":19770,
                "id":"gnl_Bakta_DMCOKL_19680",
                "start":19221,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":48.9,
                        "code":"PF07993",
                        "end":850,
                        "start":773
                    },
                    {
                        "bitscore":53.6,
                        "code":"PF00550",
                        "end":734,
                        "start":668
                    },
                    {
                        "bitscore":243.7,
                        "code":"PF00501",
                        "end":511,
                        "start":172
                    }
                ],
                "end":22607,
                "id":"gnl_Bakta_DMCOKL_19685",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":62.3,
                        "code":"PF11583",
                        "end":292,
                        "start":8
                    }
                ],
                "end":23542,
                "id":"aurF",
                "start":22603,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":158.6,
                        "code":"PF11251",
                        "end":168,
                        "start":1
                    }
                ],
                "end":24072,
                "id":"mgoB",
                "start":23538,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":78.2,
                        "code":"PF11251",
                        "end":69,
                        "start":13
                    }
                ],
                "end":24296,
                "id":"gnl_Bakta_DMCOKL_19700",
                "start":24083,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":66.2,
                        "code":"PF07729",
                        "end":191,
                        "start":70
                    },
                    {
                        "bitscore":65.6,
                        "code":"PF00392",
                        "end":60,
                        "start":1
                    }
                ],
                "end":25259,
                "id":"gnl_Bakta_DMCOKL_19705",
                "start":24620,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":139.2,
                        "code":"PF02668",
                        "end":232,
                        "start":18
                    }
                ],
                "end":26313,
                "id":"CONCOCT.18.region002.contig_512_ORF30",
                "start":25599,
                "strand":1
            },
            {
                "domains":[],
                "end":27162,
                "id":"CONCOCT.18.region002.contig_512_ORF31",
                "start":26508,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":112.7,
                        "code":"PF00005",
                        "end":324,
                        "start":182
                    }
                ],
                "end":28387,
                "id":"gnl_Bakta_DMCOKL_19720",
                "start":27106,
                "strand":1
            },
            {
                "domains":[],
                "end":29046,
                "id":"gnl_Bakta_DMCOKL_19725",
                "start":28398,
                "strand":1
            },
            {
                "domains":[],
                "end":29246,
                "id":"gnl_Bakta_DMCOKL_19730",
                "start":29060,
                "strand":1
            },
            {
                "domains":[],
                "end":30287,
                "id":"gnl_Bakta_DMCOKL_19735",
                "start":29834,
                "strand":1
            },
            {
                "domains":[],
                "end":30855,
                "id":"farB",
                "start":30441,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":37.7,
                        "code":"PF07690",
                        "end":293,
                        "start":1
                    }
                ],
                "end":31976,
                "id":"gnl_Bakta_DMCOKL_19745",
                "start":30854,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.5,
                        "code":"PF16576",
                        "end":291,
                        "start":39
                    }
                ],
                "end":33051,
                "id":"hlyD",
                "start":31992,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":80.1,
                        "code":"PF02321",
                        "end":257,
                        "start":64
                    },
                    {
                        "bitscore":88.2,
                        "code":"PF02321",
                        "end":467,
                        "start":283
                    }
                ],
                "end":34493,
                "id":"gnl_Bakta_DMCOKL_19755",
                "start":33047,
                "strand":1
            },
            {
                "domains":[],
                "end":35070,
                "id":"CONCOCT.18.region002.contig_512_ORF40",
                "start":34854,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":54.7,
                        "code":"PF11340",
                        "end":192,
                        "start":86
                    }
                ],
                "end":36063,
                "id":"gnl_Bakta_DMCOKL_19765",
                "start":35358,
                "strand":-1
            },
            {
                "domains":[],
                "end":36257,
                "id":"gnl_Bakta_DMCOKL_19770",
                "start":36059,
                "strand":-1
            },
            {
                "domains":[],
                "end":37498,
                "id":"yfiO",
                "start":36253,
                "strand":-1
            },
            {
                "domains":[],
                "end":38222,
                "id":"gnl_Bakta_DMCOKL_19780",
                "start":37529,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":57.7,
                        "code":"PF13437",
                        "end":246,
                        "start":147
                    }
                ],
                "end":40478,
                "id":"gnl_Bakta_DMCOKL_19785",
                "start":38384,
                "strand":1
            },
            {
                "domains":[],
                "end":40750,
                "id":"gnl_Bakta_DMCOKL_19790",
                "start":40477,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":29.8,
                        "code":"PF02163",
                        "end":158,
                        "start":47
                    }
                ],
                "end":41617,
                "id":"CONCOCT.18.region002.contig_512_ORF47",
                "start":40885,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":37.6,
                        "code":"PF13533",
                        "end":48,
                        "start":4
                    }
                ],
                "end":42052,
                "id":"gnl_Bakta_DMCOKL_19800",
                "start":41812,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":24.3,
                        "code":"PF13437",
                        "end":112,
                        "start":1
                    }
                ],
                "end":42576,
                "id":"hlyD",
                "start":42090,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_1708, whole genome shotgun sequence",
        "end":74239,
        "id":"CONCOCT.18.region003.contig_1708",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":54.2,
                        "code":"PF13550",
                        "end":547,
                        "start":380
                    }
                ],
                "end":2430,
                "id":"gnl_Bakta_DMCOKL_13185",
                "start":69,
                "strand":1
            },
            {
                "domains":[],
                "end":2903,
                "id":"gnl_Bakta_DMCOKL_13190",
                "start":2426,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":84.0,
                        "code":"PF09327",
                        "end":173,
                        "start":93
                    }
                ],
                "end":3652,
                "id":"gnl_Bakta_DMCOKL_13195",
                "start":2899,
                "strand":1
            },
            {
                "domains":[],
                "end":5453,
                "id":"gnl_Bakta_DMCOKL_13200",
                "start":4685,
                "strand":1
            },
            {
                "domains":[],
                "end":5743,
                "id":"gnl_Bakta_DMCOKL_13205",
                "start":5452,
                "strand":1
            },
            {
                "domains":[],
                "end":6126,
                "id":"gnl_Bakta_DMCOKL_13210",
                "start":5739,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.0,
                        "code":"PF00182",
                        "end":115,
                        "start":9
                    }
                ],
                "end":6584,
                "id":"gnl_Bakta_DMCOKL_13215",
                "start":6134,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":35.1,
                        "code":"PF03245",
                        "end":169,
                        "start":41
                    }
                ],
                "end":7150,
                "id":"gnl_Bakta_DMCOKL_13220",
                "start":6580,
                "strand":1
            },
            {
                "domains":[],
                "end":7374,
                "id":"gnl_Bakta_DMCOKL_13225",
                "start":7146,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":71.7,
                        "code":"PF00126",
                        "end":63,
                        "start":4
                    },
                    {
                        "bitscore":45.1,
                        "code":"PF03466",
                        "end":162,
                        "start":88
                    }
                ],
                "end":8843,
                "id":"lysR",
                "start":8297,
                "strand":1
            },
            {
                "domains":[],
                "end":10181,
                "id":"CONCOCT.18.region003.contig_1708_ORF11",
                "start":9584,
                "strand":-1
            },
            {
                "domains":[],
                "end":10661,
                "id":"gnl_Bakta_DMCOKL_13245",
                "start":10382,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":217.6,
                        "code":"PF00593",
                        "end":695,
                        "start":232
                    },
                    {
                        "bitscore":84.1,
                        "code":"PF07715",
                        "end":182,
                        "start":77
                    }
                ],
                "end":13027,
                "id":"gnl_Bakta_DMCOKL_13250",
                "start":10855,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":168.9,
                        "code":"PF13523",
                        "end":318,
                        "start":173
                    }
                ],
                "end":14145,
                "id":"gnl_Bakta_DMCOKL_13255",
                "start":13125,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":241.4,
                        "code":"PF01032",
                        "end":660,
                        "start":355
                    },
                    {
                        "bitscore":230.3,
                        "code":"PF01032",
                        "end":330,
                        "start":19
                    }
                ],
                "end":16293,
                "id":"gnl_Bakta_DMCOKL_13260",
                "start":14304,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.9,
                        "code":"PF01497",
                        "end":274,
                        "start":37
                    }
                ],
                "end":17197,
                "id":"gnl_Bakta_DMCOKL_13265",
                "start":16285,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":54.2,
                        "code":"PF00664",
                        "end":278,
                        "start":15
                    },
                    {
                        "bitscore":93.4,
                        "code":"PF00005",
                        "end":483,
                        "start":345
                    }
                ],
                "end":19043,
                "id":"gnl_Bakta_DMCOKL_13270",
                "start":17396,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":144.2,
                        "code":"PF00975",
                        "end":231,
                        "start":8
                    }
                ],
                "end":19961,
                "id":"gnl_Bakta_DMCOKL_13275",
                "start":19217,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":167.2,
                        "code":"PF02668",
                        "end":317,
                        "start":9
                    }
                ],
                "end":20981,
                "id":"gnl_Bakta_DMCOKL_13280",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":132.5,
                        "code":"PF00501",
                        "end":219,
                        "start":16
                    }
                ],
                "end":21814,
                "id":"gnl_Bakta_DMCOKL_13285",
                "start":21031,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.9,
                        "code":"PF00550",
                        "end":231,
                        "start":167
                    },
                    {
                        "bitscore":308.6,
                        "code":"PF00668",
                        "end":691,
                        "start":248
                    },
                    {
                        "bitscore":170.6,
                        "code":"PF02668",
                        "end":1038,
                        "start":739
                    }
                ],
                "end":25497,
                "id":"gnl_Bakta_DMCOKL_13295",
                "start":22308,
                "strand":1
            },
            {
                "domains":[],
                "end":25637,
                "id":"gnl_Bakta_DMCOKL_13300",
                "start":25508,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.9,
                        "code":"PF00668",
                        "end":275,
                        "start":96
                    }
                ],
                "end":27076,
                "id":"CONCOCT.18.region003.contig_1708_ORF24",
                "start":25633,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":161.5,
                        "code":"PF00501",
                        "end":272,
                        "start":1
                    },
                    {
                        "bitscore":29.1,
                        "code":"PF13193",
                        "end":403,
                        "start":327
                    },
                    {
                        "bitscore":60.2,
                        "code":"PF00550",
                        "end":496,
                        "start":430
                    }
                ],
                "end":28655,
                "id":"gnl_Bakta_DMCOKL_13310",
                "start":27035,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":308.2,
                        "code":"PF00668",
                        "end":472,
                        "start":30
                    },
                    {
                        "bitscore":310.8,
                        "code":"PF00501",
                        "end":836,
                        "start":491
                    },
                    {
                        "bitscore":31.9,
                        "code":"PF13193",
                        "end":961,
                        "start":894
                    },
                    {
                        "bitscore":56.4,
                        "code":"PF00550",
                        "end":1051,
                        "start":988
                    },
                    {
                        "bitscore":218.4,
                        "code":"PF00668",
                        "end":1514,
                        "start":1064
                    },
                    {
                        "bitscore":245.8,
                        "code":"PF00668",
                        "end":1971,
                        "start":1531
                    },
                    {
                        "bitscore":310.6,
                        "code":"PF00501",
                        "end":2335,
                        "start":1990
                    },
                    {
                        "bitscore":30.8,
                        "code":"PF13193",
                        "end":2460,
                        "start":2393
                    },
                    {
                        "bitscore":62.0,
                        "code":"PF00550",
                        "end":2551,
                        "start":2487
                    }
                ],
                "end":36437,
                "id":"gnl_Bakta_DMCOKL_13315",
                "start":28703,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.4,
                        "code":"PF00668",
                        "end":146,
                        "start":56
                    }
                ],
                "end":36982,
                "id":"gnl_Bakta_DMCOKL_13320",
                "start":36433,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":185.2,
                        "code":"PF00668",
                        "end":273,
                        "start":10
                    },
                    {
                        "bitscore":311.2,
                        "code":"PF00501",
                        "end":637,
                        "start":292
                    },
                    {
                        "bitscore":33.0,
                        "code":"PF13193",
                        "end":762,
                        "start":695
                    },
                    {
                        "bitscore":58.8,
                        "code":"PF00550",
                        "end":852,
                        "start":789
                    },
                    {
                        "bitscore":216.2,
                        "code":"PF00668",
                        "end":1312,
                        "start":867
                    }
                ],
                "end":41118,
                "id":"gnl_Bakta_DMCOKL_13325",
                "start":37137,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":268.4,
                        "code":"PF00668",
                        "end":443,
                        "start":6
                    },
                    {
                        "bitscore":233.4,
                        "code":"PF00501",
                        "end":812,
                        "start":462
                    },
                    {
                        "bitscore":43.0,
                        "code":"PF13193",
                        "end":946,
                        "start":870
                    },
                    {
                        "bitscore":49.1,
                        "code":"PF00550",
                        "end":1036,
                        "start":973
                    },
                    {
                        "bitscore":39.6,
                        "code":"PF00668",
                        "end":1116,
                        "start":1049
                    }
                ],
                "end":44531,
                "id":"gnl_Bakta_DMCOKL_13330",
                "start":41099,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":174.0,
                        "code":"PF00668",
                        "end":369,
                        "start":3
                    },
                    {
                        "bitscore":281.3,
                        "code":"PF00668",
                        "end":817,
                        "start":386
                    },
                    {
                        "bitscore":311.9,
                        "code":"PF00501",
                        "end":1182,
                        "start":837
                    },
                    {
                        "bitscore":32.4,
                        "code":"PF13193",
                        "end":1307,
                        "start":1240
                    },
                    {
                        "bitscore":60.8,
                        "code":"PF00550",
                        "end":1398,
                        "start":1334
                    }
                ],
                "end":48753,
                "id":"gnl_Bakta_DMCOKL_13335",
                "start":44475,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":259.1,
                        "code":"PF00668",
                        "end":389,
                        "start":45
                    }
                ],
                "end":49975,
                "id":"gnl_Bakta_DMCOKL_13340",
                "start":48754,
                "strand":1
            },
            {
                "domains":[],
                "end":50277,
                "id":"gnl_Bakta_DMCOKL_13345",
                "start":49971,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":208.2,
                        "code":"PF00501",
                        "end":331,
                        "start":1
                    },
                    {
                        "bitscore":37.6,
                        "code":"PF13193",
                        "end":462,
                        "start":389
                    },
                    {
                        "bitscore":43.1,
                        "code":"PF00550",
                        "end":554,
                        "start":487
                    },
                    {
                        "bitscore":38.5,
                        "code":"PF00975",
                        "end":815,
                        "start":574
                    }
                ],
                "end":52811,
                "id":"gnl_Bakta_DMCOKL_13350",
                "start":50273,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":372.9,
                        "code":"PF13434",
                        "end":359,
                        "start":9
                    }
                ],
                "end":54239,
                "id":"gnl_Bakta_DMCOKL_13355",
                "start":52883,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":66.7,
                        "code":"PF06276",
                        "end":212,
                        "start":62
                    },
                    {
                        "bitscore":25.4,
                        "code":"PF11575",
                        "end":240,
                        "start":220
                    }
                ],
                "end":55086,
                "id":"fhuF",
                "start":54330,
                "strand":1
            },
            {
                "domains":[],
                "end":55360,
                "id":"gnl_Bakta_DMCOKL_13365",
                "start":55126,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":25.3,
                        "code":"PF00005",
                        "end":82,
                        "start":1
                    }
                ],
                "end":55659,
                "id":"gnl_Bakta_DMCOKL_13370",
                "start":55356,
                "strand":-1
            },
            {
                "domains":[],
                "end":57225,
                "id":"gnl_Bakta_DMCOKL_13375",
                "start":56526,
                "strand":1
            },
            {
                "domains":[],
                "end":57629,
                "id":"gnl_Bakta_DMCOKL_13380",
                "start":57350,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.8,
                        "code":"PF13426",
                        "end":102,
                        "start":31
                    }
                ],
                "end":58070,
                "id":"gnl_Bakta_DMCOKL_13385",
                "start":57713,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":34.3,
                        "code":"PF08447",
                        "end":79,
                        "start":8
                    }
                ],
                "end":58768,
                "id":"gnl_Bakta_DMCOKL_13390",
                "start":58231,
                "strand":1
            },
            {
                "domains":[],
                "end":59559,
                "id":"gnl_Bakta_DMCOKL_13400",
                "start":59262,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":64.1,
                        "code":"PF00593",
                        "end":437,
                        "start":32
                    }
                ],
                "end":61021,
                "id":"CONCOCT.18.region003.contig_1708_ORF44",
                "start":59596,
                "strand":1
            },
            {
                "domains":[],
                "end":61380,
                "id":"gnl_Bakta_DMCOKL_13410",
                "start":61140,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.0,
                        "code":"PF02954",
                        "end":173,
                        "start":141
                    },
                    {
                        "bitscore":39.8,
                        "code":"PF00158",
                        "end":44,
                        "start":1
                    }
                ],
                "end":61917,
                "id":"gnl_Bakta_DMCOKL_13415",
                "start":61389,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.6,
                        "code":"PF01590",
                        "end":216,
                        "start":72
                    }
                ],
                "end":63297,
                "id":"CONCOCT.18.region003.contig_1708_ORF47",
                "start":62025,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":21.8,
                        "code":"PF08402",
                        "end":212,
                        "start":140
                    }
                ],
                "end":64594,
                "id":"ugpC",
                "start":63901,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":66.0,
                        "code":"PF00005",
                        "end":171,
                        "start":25
                    }
                ],
                "end":65193,
                "id":"gnl_Bakta_DMCOKL_13430",
                "start":64593,
                "strand":1
            },
            {
                "domains":[],
                "end":66531,
                "id":"gnl_Bakta_DMCOKL_13435",
                "start":65874,
                "strand":1
            },
            {
                "domains":[],
                "end":66941,
                "id":"gnl_Bakta_DMCOKL_13440",
                "start":66530,
                "strand":1
            },
            {
                "domains":[],
                "end":67521,
                "id":"gnl_Bakta_DMCOKL_13445",
                "start":66990,
                "strand":-1
            },
            {
                "domains":[],
                "end":69027,
                "id":"gnl_Bakta_DMCOKL_13450",
                "start":68691,
                "strand":1
            },
            {
                "domains":[],
                "end":69550,
                "id":"gnl_Bakta_DMCOKL_13455",
                "start":69169,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":89.1,
                        "code":"PF14518",
                        "end":273,
                        "start":103
                    }
                ],
                "end":71368,
                "id":"gnl_Bakta_DMCOKL_13460",
                "start":69988,
                "strand":1
            },
            {
                "domains":[],
                "end":71528,
                "id":"gnl_Bakta_DMCOKL_13465",
                "start":71378,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":68.2,
                        "code":"PF05175",
                        "end":180,
                        "start":64
                    }
                ],
                "end":72063,
                "id":"CONCOCT.18.region003.contig_1708_ORF57",
                "start":71514,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":43.1,
                        "code":"PF04107",
                        "end":155,
                        "start":82
                    }
                ],
                "end":72865,
                "id":"gnl_Bakta_DMCOKL_13480",
                "start":72331,
                "strand":1
            },
            {
                "domains":[],
                "end":73452,
                "id":"gnl_Bakta_DMCOKL_13485",
                "start":73089,
                "strand":1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
