var bs_data=[
    {
        "desc":"contig_1047, whole genome shotgun sequence",
        "end":21294,
        "id":"502.region001.contig_1047",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":565,
                "id":"gnl_Bakta_PEOBOA_04495",
                "start":43,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":116.5,
                        "code":"PF00465",
                        "end":133,
                        "start":1
                    }
                ],
                "end":1139,
                "id":"gnl_Bakta_PEOBOA_04500",
                "start":713,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":41.3,
                        "code":"PF08448",
                        "end":155,
                        "start":47
                    },
                    {
                        "bitscore":57.5,
                        "code":"PF00512",
                        "end":243,
                        "start":168
                    },
                    {
                        "bitscore":47.1,
                        "code":"PF02518",
                        "end":395,
                        "start":287
                    }
                ],
                "end":2434,
                "id":"gnl_Bakta_PEOBOA_04505",
                "start":1243,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":103.9,
                        "code":"PF00072",
                        "end":116,
                        "start":6
                    },
                    {
                        "bitscore":138.3,
                        "code":"PF00158",
                        "end":274,
                        "start":144
                    }
                ],
                "end":3316,
                "id":"gnl_Bakta_PEOBOA_04510",
                "start":2485,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":34.4,
                        "code":"PF00158",
                        "end":44,
                        "start":1
                    },
                    {
                        "bitscore":67.0,
                        "code":"PF02954",
                        "end":174,
                        "start":133
                    }
                ],
                "end":3824,
                "id":"gnl_Bakta_PEOBOA_04515",
                "start":3287,
                "strand":1
            },
            {
                "domains":[],
                "end":4792,
                "id":"gnl_Bakta_PEOBOA_04520",
                "start":4420,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.5,
                        "code":"PF04015",
                        "end":112,
                        "start":4
                    }
                ],
                "end":5341,
                "id":"gnl_Bakta_PEOBOA_04525",
                "start":4921,
                "strand":1
            },
            {
                "domains":[],
                "end":6026,
                "id":"gnl_Bakta_PEOBOA_04530",
                "start":5321,
                "strand":1
            },
            {
                "domains":[],
                "end":6374,
                "id":"gnl_Bakta_PEOBOA_04535",
                "start":6137,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.7,
                        "code":"PF04015",
                        "end":145,
                        "start":2
                    }
                ],
                "end":6963,
                "id":"gnl_Bakta_PEOBOA_04540",
                "start":6402,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":287.8,
                        "code":"PF10609",
                        "end":276,
                        "start":29
                    }
                ],
                "end":7958,
                "id":"gnl_Bakta_PEOBOA_04545",
                "start":6989,
                "strand":1
            },
            {
                "domains":[],
                "end":8334,
                "id":"gnl_Bakta_PEOBOA_04550",
                "start":8007,
                "strand":1
            },
            {
                "domains":[],
                "end":8708,
                "id":"gnl_Bakta_PEOBOA_04555",
                "start":8351,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":183.6,
                        "code":"PF13561",
                        "end":265,
                        "start":12
                    }
                ],
                "end":9707,
                "id":"gnl_Bakta_PEOBOA_04560",
                "start":8897,
                "strand":1
            },
            {
                "domains":[],
                "end":9976,
                "id":"gnl_Bakta_PEOBOA_04565",
                "start":9829,
                "strand":1
            },
            {
                "domains":[],
                "end":10282,
                "id":"mftB",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":95.6,
                        "code":"PF04055",
                        "end":170,
                        "start":18
                    },
                    {
                        "bitscore":34.3,
                        "code":"PF13186",
                        "end":302,
                        "start":240
                    }
                ],
                "end":11294,
                "id":"mftC",
                "start":10262,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":24.7,
                        "code":"PF02540",
                        "end":100,
                        "start":13
                    }
                ],
                "end":12210,
                "id":"gnl_Bakta_PEOBOA_04580",
                "start":11325,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.3,
                        "code":"PF00731",
                        "end":262,
                        "start":119
                    }
                ],
                "end":13051,
                "id":"larB",
                "start":12202,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":501.0,
                        "code":"PF01969",
                        "end":383,
                        "start":4
                    }
                ],
                "end":14383,
                "id":"gnl_Bakta_PEOBOA_04590",
                "start":13171,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":194.3,
                        "code":"PF02730",
                        "end":208,
                        "start":2
                    },
                    {
                        "bitscore":119.9,
                        "code":"PF01314",
                        "end":366,
                        "start":223
                    }
                ],
                "end":15719,
                "id":"502.region001.contig_1047_ORF21",
                "start":14564,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":149.0,
                        "code":"PF01314",
                        "end":209,
                        "start":1
                    }
                ],
                "end":16309,
                "id":"gnl_Bakta_PEOBOA_04600",
                "start":15676,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":157.5,
                        "code":"PF08495",
                        "end":220,
                        "start":34
                    },
                    {
                        "bitscore":103.9,
                        "code":"PF10442",
                        "end":365,
                        "start":222
                    }
                ],
                "end":17548,
                "id":"gnl_Bakta_PEOBOA_04605",
                "start":16387,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.0,
                        "code":"PF13426",
                        "end":162,
                        "start":61
                    },
                    {
                        "bitscore":38.9,
                        "code":"PF00989",
                        "end":277,
                        "start":170
                    },
                    {
                        "bitscore":79.6,
                        "code":"PF02518",
                        "end":519,
                        "start":412
                    },
                    {
                        "bitscore":63.6,
                        "code":"PF00072",
                        "end":654,
                        "start":539
                    }
                ],
                "end":19579,
                "id":"gnl_Bakta_PEOBOA_04610",
                "start":17551,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":66.5,
                        "code":"PF03358",
                        "end":216,
                        "start":21
                    }
                ],
                "end":20401,
                "id":"gnl_Bakta_PEOBOA_04615",
                "start":19600,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_220, whole genome shotgun sequence",
        "end":10786,
        "id":"502.region001.contig_220",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":116.0,
                        "code":"PF11066",
                        "end":174,
                        "start":29
                    }
                ],
                "end":1553,
                "id":"gnl_Bakta_PEOBOA_12675",
                "start":896,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":108.6,
                        "code":"PF04244",
                        "end":108,
                        "start":8
                    }
                ],
                "end":1933,
                "id":"gnl_Bakta_PEOBOA_12680",
                "start":1576,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.2,
                        "code":"PF04244",
                        "end":68,
                        "start":1
                    }
                ],
                "end":3122,
                "id":"gnl_Bakta_PEOBOA_12685",
                "start":2057,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":93.9,
                        "code":"PF00174",
                        "end":158,
                        "start":40
                    }
                ],
                "end":3723,
                "id":"gnl_Bakta_PEOBOA_12690",
                "start":3198,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":51.5,
                        "code":"PF03404",
                        "end":105,
                        "start":2
                    }
                ],
                "end":4253,
                "id":"gnl_Bakta_PEOBOA_12695",
                "start":3926,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":25.7,
                        "code":"PF01814",
                        "end":82,
                        "start":2
                    }
                ],
                "end":4645,
                "id":"gnl_Bakta_PEOBOA_12700",
                "start":4396,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":234.1,
                        "code":"PF04454",
                        "end":246,
                        "start":1
                    }
                ],
                "end":5786,
                "id":"gnl_Bakta_PEOBOA_12705",
                "start":5000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.5,
                        "code":"PF13561",
                        "end":109,
                        "start":1
                    }
                ],
                "end":6640,
                "id":"gnl_Bakta_PEOBOA_12710",
                "start":6292,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.6,
                        "code":"PF01593",
                        "end":218,
                        "start":74
                    }
                ],
                "end":7414,
                "id":"gnl_Bakta_PEOBOA_12715",
                "start":6742,
                "strand":-1
            },
            {
                "domains":[],
                "end":8227,
                "id":"gnl_Bakta_PEOBOA_12720",
                "start":8002,
                "strand":-1
            },
            {
                "domains":[],
                "end":8680,
                "id":"gnl_Bakta_PEOBOA_12725",
                "start":8269,
                "strand":-1
            },
            {
                "domains":[],
                "end":9710,
                "id":"gnl_Bakta_PEOBOA_12730",
                "start":8660,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_3352, whole genome shotgun sequence",
        "end":11752,
        "id":"502.region001.contig_3352",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":58.1,
                        "code":"PF00977",
                        "end":184,
                        "start":120
                    }
                ],
                "end":1536,
                "id":"gnl_Bakta_PEOBOA_17445",
                "start":903,
                "strand":-1
            },
            {
                "domains":[],
                "end":2516,
                "id":"gnl_Bakta_PEOBOA_17450",
                "start":1835,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":203.4,
                        "code":"PF00475",
                        "end":179,
                        "start":36
                    }
                ],
                "end":3135,
                "id":"gnl_Bakta_PEOBOA_17455",
                "start":2535,
                "strand":-1
            },
            {
                "domains":[],
                "end":3640,
                "id":"gnl_Bakta_PEOBOA_17460",
                "start":3436,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":248.6,
                        "code":"PF02624",
                        "end":383,
                        "start":77
                    },
                    {
                        "bitscore":17.6,
                        "code":"PF13432",
                        "end":465,
                        "start":398
                    },
                    {
                        "bitscore":33.2,
                        "code":"PF00515",
                        "end":529,
                        "start":496
                    },
                    {
                        "bitscore":21.9,
                        "code":"PF13181",
                        "end":563,
                        "start":533
                    }
                ],
                "end":6752,
                "id":"ycaO",
                "start":5000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.3,
                        "code":"PF00350",
                        "end":298,
                        "start":57
                    }
                ],
                "end":9185,
                "id":"gnl_Bakta_PEOBOA_17475",
                "start":6938,
                "strand":-1
            },
            {
                "domains":[],
                "end":9533,
                "id":"gnl_Bakta_PEOBOA_17480",
                "start":9332,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":169.4,
                        "code":"PF02622",
                        "end":175,
                        "start":17
                    }
                ],
                "end":10191,
                "id":"gnl_Bakta_PEOBOA_17485",
                "start":9624,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_3383, whole genome shotgun sequence",
        "end":13485,
        "id":"502.region001.contig_3383",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":494,
                "id":"gnl_Bakta_PEOBOA_18875",
                "start":56,
                "strand":1
            },
            {
                "domains":[],
                "end":1161,
                "id":"gnl_Bakta_PEOBOA_18880",
                "start":573,
                "strand":-1
            },
            {
                "domains":[],
                "end":2023,
                "id":"gnl_Bakta_PEOBOA_18885",
                "start":1207,
                "strand":1
            },
            {
                "domains":[],
                "end":2509,
                "id":"gnl_Bakta_PEOBOA_18890",
                "start":2062,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":40.6,
                        "code":"PF05402",
                        "end":91,
                        "start":27
                    }
                ],
                "end":3485,
                "id":"gnl_Bakta_PEOBOA_18895",
                "start":3200,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":86.4,
                        "code":"PF01740",
                        "end":106,
                        "start":2
                    }
                ],
                "end":3908,
                "id":"gnl_Bakta_PEOBOA_18900",
                "start":3575,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":99.5,
                        "code":"PF13581",
                        "end":136,
                        "start":10
                    }
                ],
                "end":4418,
                "id":"gnl_Bakta_PEOBOA_18905",
                "start":3992,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.1,
                        "code":"PF00027",
                        "end":133,
                        "start":46
                    }
                ],
                "end":5060,
                "id":"gnl_Bakta_PEOBOA_18910",
                "start":4502,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.8,
                        "code":"PF00005",
                        "end":271,
                        "start":147
                    }
                ],
                "end":6066,
                "id":"gnl_Bakta_PEOBOA_18915",
                "start":5034,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":64.6,
                        "code":"PF00005",
                        "end":185,
                        "start":49
                    }
                ],
                "end":6625,
                "id":"gnl_Bakta_PEOBOA_18920",
                "start":6028,
                "strand":-1
            },
            {
                "domains":[],
                "end":8629,
                "id":"gnl_Bakta_PEOBOA_18925",
                "start":8215,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":59.6,
                        "code":"PF20970",
                        "end":101,
                        "start":2
                    }
                ],
                "end":9274,
                "id":"gnl_Bakta_PEOBOA_18935",
                "start":8896,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.9,
                        "code":"PF20970",
                        "end":75,
                        "start":1
                    }
                ],
                "end":9491,
                "id":"gnl_Bakta_PEOBOA_18940",
                "start":9263,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":73.0,
                        "code":"PF09838",
                        "end":59,
                        "start":4
                    }
                ],
                "end":10097,
                "id":"gnl_Bakta_PEOBOA_18945",
                "start":9911,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":437.4,
                        "code":"PF02547",
                        "end":349,
                        "start":4
                    }
                ],
                "end":11269,
                "id":"gnl_Bakta_PEOBOA_18950",
                "start":10216,
                "strand":1
            },
            {
                "domains":[],
                "end":11448,
                "id":"gnl_Bakta_PEOBOA_18955",
                "start":11322,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":366.2,
                        "code":"PF01702",
                        "end":260,
                        "start":1
                    }
                ],
                "end":12589,
                "id":"gnl_Bakta_PEOBOA_18960",
                "start":11800,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":109.9,
                        "code":"PF01106",
                        "end":70,
                        "start":5
                    }
                ],
                "end":12994,
                "id":"nifU",
                "start":12775,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_274, whole genome shotgun sequence",
        "end":10819,
        "id":"CONCOCT.10.region001.contig_274",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2003,
                "id":"gnl_Bakta_DNKOAA_13090",
                "start":611,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":170.0,
                        "code":"PF05960",
                        "end":351,
                        "start":5
                    }
                ],
                "end":3073,
                "id":"gnl_Bakta_DNKOAA_13095",
                "start":2005,
                "strand":-1
            },
            {
                "domains":[],
                "end":3267,
                "id":"gnl_Bakta_DNKOAA_13100",
                "start":3105,
                "strand":1
            },
            {
                "domains":[],
                "end":3711,
                "id":"gnl_Bakta_DNKOAA_13105",
                "start":3465,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":175.9,
                        "code":"PF09996",
                        "end":120,
                        "start":6
                    }
                ],
                "end":4250,
                "id":"gnl_Bakta_DNKOAA_13110",
                "start":3863,
                "strand":1
            },
            {
                "domains":[],
                "end":4920,
                "id":"gnl_Bakta_DNKOAA_13115",
                "start":4674,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":237.6,
                        "code":"PF04454",
                        "end":256,
                        "start":1
                    }
                ],
                "end":5819,
                "id":"gnl_Bakta_DNKOAA_13120",
                "start":5000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":47.6,
                        "code":"PF01814",
                        "end":113,
                        "start":2
                    }
                ],
                "end":6382,
                "id":"gnl_Bakta_DNKOAA_13125",
                "start":5866,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.6,
                        "code":"PF13414",
                        "end":74,
                        "start":40
                    }
                ],
                "end":7078,
                "id":"gnl_Bakta_DNKOAA_13130",
                "start":6718,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":86.3,
                        "code":"PF17186",
                        "end":81,
                        "start":1
                    }
                ],
                "end":7818,
                "id":"gnl_Bakta_DNKOAA_13135",
                "start":7548,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":114.4,
                        "code":"PF07143",
                        "end":190,
                        "start":54
                    }
                ],
                "end":8687,
                "id":"gnl_Bakta_DNKOAA_13140",
                "start":7934,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.9,
                        "code":"PF02687",
                        "end":303,
                        "start":182
                    }
                ],
                "end":9653,
                "id":"gnl_Bakta_DNKOAA_13145",
                "start":8714,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_1602, whole genome shotgun sequence",
        "end":10855,
        "id":"CONCOCT.18.region001.contig_1602",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2037,
                "id":"gnl_Bakta_DMCOKL_03150",
                "start":1365,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":44.8,
                        "code":"PF13561",
                        "end":191,
                        "start":10
                    }
                ],
                "end":2734,
                "id":"gnl_Bakta_DMCOKL_03155",
                "start":2134,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":100.1,
                        "code":"PF03466",
                        "end":186,
                        "start":12
                    }
                ],
                "end":3749,
                "id":"lysR",
                "start":3161,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":56.1,
                        "code":"PF07681",
                        "end":126,
                        "start":24
                    }
                ],
                "end":4231,
                "id":"doxX",
                "start":3745,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":91.7,
                        "code":"PF09836",
                        "end":94,
                        "start":2
                    }
                ],
                "end":5004,
                "id":"gnl_Bakta_DMCOKL_03170",
                "start":4227,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":350.6,
                        "code":"PF05114",
                        "end":280,
                        "start":13
                    }
                ],
                "end":5855,
                "id":"gnl_Bakta_DMCOKL_03175",
                "start":5000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":76.9,
                        "code":"PF10048",
                        "end":87,
                        "start":33
                    }
                ],
                "end":6178,
                "id":"gnl_Bakta_DMCOKL_03180",
                "start":5881,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":124.1,
                        "code":"PF00005",
                        "end":162,
                        "start":17
                    }
                ],
                "end":7076,
                "id":"livF",
                "start":6374,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":44.4,
                        "code":"PF12399",
                        "end":223,
                        "start":199
                    },
                    {
                        "bitscore":113.7,
                        "code":"PF00005",
                        "end":150,
                        "start":1
                    }
                ],
                "end":7749,
                "id":"livG",
                "start":7077,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":197.4,
                        "code":"PF02653",
                        "end":384,
                        "start":97
                    },
                    {
                        "bitscore":40.7,
                        "code":"PF11862",
                        "end":90,
                        "start":5
                    }
                ],
                "end":9051,
                "id":"livM",
                "start":7839,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":179.4,
                        "code":"PF02653",
                        "end":291,
                        "start":10
                    }
                ],
                "end":10015,
                "id":"livH",
                "start":9091,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_512, whole genome shotgun sequence",
        "end":11320,
        "id":"CONCOCT.18.region001.contig_512",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":56.6,
                        "code":"PF12276",
                        "end":166,
                        "start":25
                    }
                ],
                "end":1819,
                "id":"gnl_Bakta_DMCOKL_18445",
                "start":1297,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":26.7,
                        "code":"PF13396",
                        "end":60,
                        "start":18
                    },
                    {
                        "bitscore":34.1,
                        "code":"PF13091",
                        "end":278,
                        "start":135
                    },
                    {
                        "bitscore":99.6,
                        "code":"PF13091",
                        "end":446,
                        "start":319
                    }
                ],
                "end":3390,
                "id":"cls",
                "start":1950,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":77.4,
                        "code":"PF02353",
                        "end":74,
                        "start":1
                    }
                ],
                "end":3755,
                "id":"gnl_Bakta_DMCOKL_18455",
                "start":3464,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":230.5,
                        "code":"PF02353",
                        "end":278,
                        "start":98
                    }
                ],
                "end":4651,
                "id":"cfaB",
                "start":3751,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":70.3,
                        "code":"PF09836",
                        "end":365,
                        "start":269
                    },
                    {
                        "bitscore":351.7,
                        "code":"PF05114",
                        "end":256,
                        "start":2
                    }
                ],
                "end":6320,
                "id":"gnl_Bakta_DMCOKL_18465",
                "start":5000,
                "strand":-1
            },
            {
                "domains":[],
                "end":6684,
                "id":"gnl_Bakta_DMCOKL_18470",
                "start":6432,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":64.6,
                        "code":"PF00702",
                        "end":523,
                        "start":317
                    },
                    {
                        "bitscore":172.5,
                        "code":"PF00122",
                        "end":300,
                        "start":127
                    }
                ],
                "end":8689,
                "id":"cadA",
                "start":6772,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.9,
                        "code":"PF01145",
                        "end":260,
                        "start":39
                    }
                ],
                "end":9720,
                "id":"hflK",
                "start":8685,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.9,
                        "code":"PF01145",
                        "end":149,
                        "start":12
                    }
                ],
                "end":10335,
                "id":"gnl_Bakta_DMCOKL_18485",
                "start":9837,
                "strand":-1
            },
            {
                "domains":[],
                "end":10652,
                "id":"gnl_Bakta_DMCOKL_18490",
                "start":10370,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_513, whole genome shotgun sequence",
        "end":20276,
        "id":"CONCOCT.18.region002.contig_513",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":50.6,
                        "code":"PF13404",
                        "end":45,
                        "start":4
                    },
                    {
                        "bitscore":61.1,
                        "code":"PF01037",
                        "end":140,
                        "start":70
                    }
                ],
                "end":2938,
                "id":"lrp",
                "start":2491,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":156.6,
                        "code":"PF01593",
                        "end":539,
                        "start":62
                    }
                ],
                "end":4787,
                "id":"yobN",
                "start":3083,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":199.7,
                        "code":"PF00795",
                        "end":245,
                        "start":2
                    }
                ],
                "end":5593,
                "id":"gnl_Bakta_DMCOKL_32585",
                "start":4798,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":91.6,
                        "code":"PF00675",
                        "end":161,
                        "start":19
                    },
                    {
                        "bitscore":46.6,
                        "code":"PF05193",
                        "end":337,
                        "start":178
                    }
                ],
                "end":7545,
                "id":"gnl_Bakta_DMCOKL_32590",
                "start":5652,
                "strand":1
            },
            {
                "domains":[],
                "end":8023,
                "id":"gnl_Bakta_DMCOKL_32595",
                "start":7627,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.4,
                        "code":"PF08042",
                        "end":20,
                        "start":2
                    }
                ],
                "end":8257,
                "id":"pqqA",
                "start":8182,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":165.6,
                        "code":"PF12706",
                        "end":270,
                        "start":50
                    }
                ],
                "end":9240,
                "id":"pqqB",
                "start":8328,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":216.6,
                        "code":"PF03070",
                        "end":223,
                        "start":12
                    }
                ],
                "end":10004,
                "id":"pqqC",
                "start":9251,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.0,
                        "code":"PF05402",
                        "end":88,
                        "start":25
                    }
                ],
                "end":10276,
                "id":"pqqD",
                "start":10000,
                "strand":1
            },
            {
                "domains":[],
                "end":11200,
                "id":"pqqE",
                "start":10639,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":30.4,
                        "code":"PF01679",
                        "end":51,
                        "start":2
                    }
                ],
                "end":11571,
                "id":"gnl_Bakta_DMCOKL_32625",
                "start":11409,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":97.4,
                        "code":"PF00202",
                        "end":125,
                        "start":6
                    }
                ],
                "end":12340,
                "id":"gnl_Bakta_DMCOKL_32635",
                "start":11962,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":124.8,
                        "code":"PF00202",
                        "end":231,
                        "start":30
                    }
                ],
                "end":13016,
                "id":"gnl_Bakta_DMCOKL_32640",
                "start":12311,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":80.7,
                        "code":"PF00126",
                        "end":62,
                        "start":3
                    },
                    {
                        "bitscore":129.3,
                        "code":"PF03466",
                        "end":293,
                        "start":86
                    }
                ],
                "end":14113,
                "id":"gnl_Bakta_DMCOKL_32645",
                "start":13213,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":129.2,
                        "code":"PF12806",
                        "end":359,
                        "start":239
                    },
                    {
                        "bitscore":66.7,
                        "code":"PF00441",
                        "end":228,
                        "start":54
                    }
                ],
                "end":15433,
                "id":"gnl_Bakta_DMCOKL_32655",
                "start":14341,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":45.9,
                        "code":"PF02771",
                        "end":159,
                        "start":37
                    },
                    {
                        "bitscore":47.3,
                        "code":"PF12418",
                        "end":34,
                        "start":3
                    }
                ],
                "end":16120,
                "id":"CONCOCT.18.region002.contig_513_ORF18",
                "start":15589,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":124.7,
                        "code":"PF12806",
                        "end":236,
                        "start":115
                    },
                    {
                        "bitscore":59.2,
                        "code":"PF00441",
                        "end":105,
                        "start":1
                    }
                ],
                "end":16971,
                "id":"gnl_Bakta_DMCOKL_32670",
                "start":16242,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.9,
                        "code":"PF02770",
                        "end":268,
                        "start":161
                    },
                    {
                        "bitscore":46.3,
                        "code":"PF02771",
                        "end":157,
                        "start":36
                    },
                    {
                        "bitscore":29.2,
                        "code":"PF12418",
                        "end":30,
                        "start":3
                    }
                ],
                "end":18013,
                "id":"gnl_Bakta_DMCOKL_32675",
                "start":16912,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":78.2,
                        "code":"PF00990",
                        "end":359,
                        "start":242
                    }
                ],
                "end":19396,
                "id":"gnl_Bakta_DMCOKL_32680",
                "start":18103,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_1708, whole genome shotgun sequence",
        "end":11599,
        "id":"CONCOCT.18.region004.contig_1708",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":131.5,
                        "code":"PF06445",
                        "end":289,
                        "start":135
                    },
                    {
                        "bitscore":71.5,
                        "code":"PF12833",
                        "end":114,
                        "start":34
                    }
                ],
                "end":935,
                "id":"araC",
                "start":65,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":90.3,
                        "code":"PF01810",
                        "end":204,
                        "start":14
                    }
                ],
                "end":1744,
                "id":"lysE",
                "start":1123,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":126.6,
                        "code":"PF06983",
                        "end":129,
                        "start":28
                    }
                ],
                "end":2303,
                "id":"gnl_Bakta_DMCOKL_17110",
                "start":1790,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":183.8,
                        "code":"PF00291",
                        "end":204,
                        "start":9
                    }
                ],
                "end":3040,
                "id":"CONCOCT.18.region004.contig_1708_ORF4",
                "start":2404,
                "strand":1
            },
            {
                "domains":[],
                "end":3198,
                "id":"gnl_Bakta_DMCOKL_17120",
                "start":3039,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":29.6,
                        "code":"PF00571",
                        "end":122,
                        "start":68
                    }
                ],
                "end":3751,
                "id":"gnl_Bakta_DMCOKL_17125",
                "start":3199,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":500.2,
                        "code":"PF01053",
                        "end":386,
                        "start":10
                    }
                ],
                "end":4948,
                "id":"gnl_Bakta_DMCOKL_17130",
                "start":3781,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":248.5,
                        "code":"PF18381",
                        "end":527,
                        "start":356
                    },
                    {
                        "bitscore":193.9,
                        "code":"PF02624",
                        "end":340,
                        "start":6
                    }
                ],
                "end":6599,
                "id":"ycaO",
                "start":5000,
                "strand":-1
            },
            {
                "domains":[],
                "end":7225,
                "id":"gnl_Bakta_DMCOKL_17140",
                "start":6622,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":30.8,
                        "code":"PF00989",
                        "end":82,
                        "start":9
                    }
                ],
                "end":7629,
                "id":"gnl_Bakta_DMCOKL_17145",
                "start":7365,
                "strand":1
            },
            {
                "domains":[],
                "end":8837,
                "id":"gnl_Bakta_DMCOKL_17150",
                "start":8420,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":163.3,
                        "code":"PF00015",
                        "end":261,
                        "start":90
                    }
                ],
                "end":9703,
                "id":"gnl_Bakta_DMCOKL_17155",
                "start":8818,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":25.2,
                        "code":"PF05076",
                        "end":266,
                        "start":82
                    }
                ],
                "end":10761,
                "id":"gnl_Bakta_DMCOKL_17160",
                "start":9951,
                "strand":1
            },
            {
                "domains":[],
                "end":11342,
                "id":"gnl_Bakta_DMCOKL_17165",
                "start":10760,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_2365, whole genome shotgun sequence",
        "end":12856,
        "id":"CONCOCT.4_sub.region001.contig_2365",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":59.4,
                        "code":"PF04977",
                        "end":87,
                        "start":5
                    }
                ],
                "end":502,
                "id":"gnl_Bakta_FEECGD_10675",
                "start":214,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":53.2,
                        "code":"PF09723",
                        "end":41,
                        "start":1
                    }
                ],
                "end":743,
                "id":"gnl_Bakta_FEECGD_10680",
                "start":536,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":32.9,
                        "code":"PF01381",
                        "end":43,
                        "start":6
                    }
                ],
                "end":1274,
                "id":"gnl_Bakta_FEECGD_10685",
                "start":902,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":74.0,
                        "code":"PF03167",
                        "end":254,
                        "start":100
                    }
                ],
                "end":2430,
                "id":"gnl_Bakta_FEECGD_10690",
                "start":1638,
                "strand":1
            },
            {
                "domains":[],
                "end":3730,
                "id":"gnl_Bakta_FEECGD_10700",
                "start":2809,
                "strand":-1
            },
            {
                "domains":[],
                "end":4532,
                "id":"gnl_Bakta_FEECGD_10705",
                "start":3734,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":33.0,
                        "code":"PF00027",
                        "end":106,
                        "start":47
                    }
                ],
                "end":4861,
                "id":"gnl_Bakta_FEECGD_10710",
                "start":4498,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.7,
                        "code":"PF00005",
                        "end":781,
                        "start":693
                    },
                    {
                        "bitscore":61.5,
                        "code":"PF00005",
                        "end":500,
                        "start":353
                    },
                    {
                        "bitscore":116.8,
                        "code":"PF00664",
                        "end":288,
                        "start":19
                    }
                ],
                "end":7397,
                "id":"gnl_Bakta_FEECGD_10715",
                "start":4835,
                "strand":-1
            },
            {
                "domains":[],
                "end":7944,
                "id":"gnl_Bakta_FEECGD_10720",
                "start":7467,
                "strand":-1
            },
            {
                "domains":[],
                "end":9257,
                "id":"gnl_Bakta_FEECGD_10725",
                "start":8645,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.4,
                        "code":"PF20580",
                        "end":114,
                        "start":59
                    }
                ],
                "end":9943,
                "id":"gnl_Bakta_FEECGD_10730",
                "start":9595,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":116.6,
                        "code":"PF20581",
                        "end":129,
                        "start":2
                    }
                ],
                "end":10652,
                "id":"gnl_Bakta_FEECGD_10735",
                "start":10136,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":27.3,
                        "code":"PF20581",
                        "end":188,
                        "start":124
                    }
                ],
                "end":11817,
                "id":"gnl_Bakta_FEECGD_10740",
                "start":11211,
                "strand":-1
            },
            {
                "domains":[],
                "end":12513,
                "id":"gnl_Bakta_FEECGD_10745",
                "start":12006,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_2844, whole genome shotgun sequence",
        "end":11020,
        "id":"CONCOCT.4_sub.region001.contig_2844",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":418.6,
                        "code":"PF02277",
                        "end":350,
                        "start":11
                    }
                ],
                "end":1073,
                "id":"gnl_Bakta_FEECGD_14750",
                "start":5,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":181.5,
                        "code":"PF02283",
                        "end":176,
                        "start":5
                    }
                ],
                "end":1620,
                "id":"gnl_Bakta_FEECGD_14755",
                "start":1080,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":178.6,
                        "code":"PF00300",
                        "end":191,
                        "start":3
                    }
                ],
                "end":2207,
                "id":"gnl_Bakta_FEECGD_14760",
                "start":1628,
                "strand":-1
            },
            {
                "domains":[],
                "end":2641,
                "id":"gnl_Bakta_FEECGD_14765",
                "start":2386,
                "strand":1
            },
            {
                "domains":[],
                "end":2896,
                "id":"gnl_Bakta_FEECGD_14770",
                "start":2617,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":111.6,
                        "code":"PF01890",
                        "end":249,
                        "start":128
                    },
                    {
                        "bitscore":54.3,
                        "code":"PF11760",
                        "end":44,
                        "start":1
                    }
                ],
                "end":3713,
                "id":"cbiG",
                "start":2951,
                "strand":-1
            },
            {
                "domains":[],
                "end":4529,
                "id":"gnl_Bakta_FEECGD_14780",
                "start":4271,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":25.1,
                        "code":"PF07719",
                        "end":126,
                        "start":93
                    }
                ],
                "end":5008,
                "id":"gnl_Bakta_FEECGD_14785",
                "start":4525,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":202.7,
                        "code":"PF02624",
                        "end":338,
                        "start":78
                    }
                ],
                "end":6020,
                "id":"CONCOCT.4_sub.region001.contig_2844_ORF9",
                "start":5000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":125.5,
                        "code":"PF02367",
                        "end":134,
                        "start":5
                    }
                ],
                "end":6610,
                "id":"tsaE",
                "start":6136,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":102.2,
                        "code":"PF00313",
                        "end":70,
                        "start":5
                    }
                ],
                "end":6970,
                "id":"cspA",
                "start":6754,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":251.4,
                        "code":"PF00496",
                        "end":535,
                        "start":124
                    }
                ],
                "end":9097,
                "id":"gnl_Bakta_FEECGD_14805",
                "start":7228,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":154.4,
                        "code":"PF01556",
                        "end":303,
                        "start":154
                    },
                    {
                        "bitscore":102.5,
                        "code":"PF00226",
                        "end":64,
                        "start":2
                    }
                ],
                "end":10154,
                "id":"gnl_Bakta_FEECGD_14810",
                "start":9185,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":148.0,
                        "code":"PF00436",
                        "end":105,
                        "start":2
                    }
                ],
                "end":10894,
                "id":"gnl_Bakta_FEECGD_14815",
                "start":10459,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_87, whole genome shotgun sequence",
        "end":10726,
        "id":"bins.002_sub.region001.contig_87",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":408,
                "id":"gnl_Bakta_FPLLNL_27555",
                "start":114,
                "strand":-1
            },
            {
                "domains":[],
                "end":1362,
                "id":"gnl_Bakta_FPLLNL_27560",
                "start":744,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":103.9,
                        "code":"PF00578",
                        "end":145,
                        "start":29
                    }
                ],
                "end":1916,
                "id":"resA",
                "start":1403,
                "strand":1
            },
            {
                "domains":[],
                "end":2405,
                "id":"gnl_Bakta_FPLLNL_27570",
                "start":2114,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":28.8,
                        "code":"PF04366",
                        "end":190,
                        "start":89
                    }
                ],
                "end":3465,
                "id":"gnl_Bakta_FPLLNL_27575",
                "start":2886,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":68.4,
                        "code":"PF07681",
                        "end":125,
                        "start":22
                    }
                ],
                "end":4201,
                "id":"doxX",
                "start":3556,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":99.4,
                        "code":"PF09836",
                        "end":104,
                        "start":18
                    }
                ],
                "end":5044,
                "id":"gnl_Bakta_FPLLNL_27585",
                "start":4249,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":315.5,
                        "code":"PF05114",
                        "end":225,
                        "start":1
                    }
                ],
                "end":5726,
                "id":"gnl_Bakta_FPLLNL_27590",
                "start":5000,
                "strand":-1
            },
            {
                "domains":[],
                "end":6247,
                "id":"gnl_Bakta_FPLLNL_27595",
                "start":5905,
                "strand":-1
            },
            {
                "domains":[],
                "end":6898,
                "id":"gnl_Bakta_FPLLNL_27600",
                "start":6580,
                "strand":1
            },
            {
                "domains":[],
                "end":7279,
                "id":"gnl_Bakta_FPLLNL_27605",
                "start":7120,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":110.9,
                        "code":"PF02508",
                        "end":101,
                        "start":1
                    }
                ],
                "end":7589,
                "id":"bins.002_sub.region001.contig_87_ORF12",
                "start":7268,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.4,
                        "code":"PF04205",
                        "end":146,
                        "start":102
                    }
                ],
                "end":8456,
                "id":"rnfG",
                "start":8009,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":187.2,
                        "code":"PF03116",
                        "end":172,
                        "start":1
                    }
                ],
                "end":8993,
                "id":"gnl_Bakta_FPLLNL_27620",
                "start":8465,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":147.7,
                        "code":"PF03116",
                        "end":136,
                        "start":1
                    }
                ],
                "end":9412,
                "id":"rsxD",
                "start":8989,
                "strand":-1
            },
            {
                "domains":[],
                "end":9670,
                "id":"gnl_Bakta_FPLLNL_27630",
                "start":9487,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"contig_3440, whole genome shotgun sequence",
        "end":20504,
        "id":"bins.24.region001.contig_3440",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":118.8,
                        "code":"PF03713",
                        "end":140,
                        "start":1
                    }
                ],
                "end":788,
                "id":"gnl_Bakta_CBPBPM_07540",
                "start":350,
                "strand":-1
            },
            {
                "domains":[],
                "end":1548,
                "id":"gnl_Bakta_CBPBPM_07545",
                "start":1035,
                "strand":-1
            },
            {
                "domains":[],
                "end":2845,
                "id":"gnl_Bakta_CBPBPM_07550",
                "start":1801,
                "strand":-1
            },
            {
                "domains":[],
                "end":3795,
                "id":"gnl_Bakta_CBPBPM_07555",
                "start":2859,
                "strand":-1
            },
            {
                "domains":[],
                "end":4546,
                "id":"gnl_Bakta_CBPBPM_07560",
                "start":3838,
                "strand":1
            },
            {
                "domains":[],
                "end":4835,
                "id":"gnl_Bakta_CBPBPM_07565",
                "start":4529,
                "strand":1
            },
            {
                "domains":[],
                "end":7544,
                "id":"gnl_Bakta_CBPBPM_07570",
                "start":6464,
                "strand":1
            },
            {
                "domains":[],
                "end":8426,
                "id":"gnl_Bakta_CBPBPM_07575",
                "start":7967,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":32.8,
                        "code":"PF10609",
                        "end":424,
                        "start":225
                    }
                ],
                "end":9883,
                "id":"gnl_Bakta_CBPBPM_07580",
                "start":8395,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.9,
                        "code":"PF05402",
                        "end":146,
                        "start":76
                    }
                ],
                "end":10504,
                "id":"gnl_Bakta_CBPBPM_07585",
                "start":10000,
                "strand":1
            },
            {
                "domains":[],
                "end":11713,
                "id":"gnl_Bakta_CBPBPM_07590",
                "start":10693,
                "strand":1
            },
            {
                "domains":[],
                "end":12581,
                "id":"gnl_Bakta_CBPBPM_07595",
                "start":11681,
                "strand":1
            },
            {
                "domains":[],
                "end":13263,
                "id":"gnl_Bakta_CBPBPM_07600",
                "start":12717,
                "strand":-1
            },
            {
                "domains":[],
                "end":14096,
                "id":"gnl_Bakta_CBPBPM_07605",
                "start":13433,
                "strand":-1
            },
            {
                "domains":[],
                "end":14957,
                "id":"gnl_Bakta_CBPBPM_07610",
                "start":14276,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.0,
                        "code":"PF01571",
                        "end":143,
                        "start":9
                    }
                ],
                "end":16249,
                "id":"gnl_Bakta_CBPBPM_07620",
                "start":15298,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":78.4,
                        "code":"PF01475",
                        "end":130,
                        "start":12
                    }
                ],
                "end":16707,
                "id":"gnl_Bakta_CBPBPM_07625",
                "start":16245,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":189.5,
                        "code":"PF08768",
                        "end":162,
                        "start":11
                    }
                ],
                "end":17198,
                "id":"gnl_Bakta_CBPBPM_07630",
                "start":16703,
                "strand":-1
            },
            {
                "domains":[],
                "end":17310,
                "id":"gnl_Bakta_CBPBPM_07635",
                "start":17208,
                "strand":-1
            },
            {
                "domains":[],
                "end":17929,
                "id":"gnl_Bakta_CBPBPM_07640",
                "start":17368,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":77.6,
                        "code":"PF00246",
                        "end":202,
                        "start":46
                    }
                ],
                "end":18831,
                "id":"gnl_Bakta_CBPBPM_07645",
                "start":18027,
                "strand":-1
            },
            {
                "domains":[],
                "end":20073,
                "id":"gnl_Bakta_CBPBPM_07650",
                "start":19140,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
